bcgov/cas-registration

erd.md

card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-registration/13

docs: 13 first draft of ERD

---

client/Dockerfile

[ZH CARD 31](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-registration/31)

Chore: 31 add client Dockerfile

---

bc_obps/Makefile
bc_obps/registration/fixtures/naicsCode.json
bc_obps/registration/fixtures/operation.json
bc_obps/registration/fixtures/operator.json
bc_obps/registration/fixtures/user.json
docs/developer-environment-setup.md

Fixture creation to support https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/26

chore: 26 create fixtures

---

README.md
bc_obps/registration/fixtures/contact.json
bc_obps/registration/fixtures/document.json
bc_obps/registration/tests.py

Test: 152 db tests

---

CHANGELOG.md
package.json

early alpha version with limited workflow implementations

chore: release v0.1.0-alpha-1

---

bc_obps/registration/admin.py
bc_obps/registration/fixtures/user.json
bc_obps/registration/migrations/0001_initial.py
bc_obps/registration/models.py
bc_obps/registration/tests/test_models.py
docs/developer-guide.md

Chore: add role table

---

Makefile
devops/dev.gcs.tfbackend
devops/openshift/deploy/job/provision-tf-state-buckets.yaml
devops/scripts/create-state-bucket.sh
docs/state-and-container-setup.md

a couple fixes to scripts/makefile to allow shipit to deploy after terraform was added

Chore: terraform deploys with shipit

---

bc_obps/bc_obps/settings.py
bc_obps/registration/api/operator.py
bc_obps/registration/middleware/current_user_middleware.py
bc_obps/registration/tests/test_middleware.py

chore: add `current_user_middleware` for user authentication

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/fixtures/user.json
bc_obps/registration/fixtures/userOperator.json
bc_obps/registration/schema/generic.py
bc_obps/registration/schema/user_operator.py
bc_obps/registration/tests/test_endpoints.py
client/app/api/auth/[...nextauth]/route.ts

card: https://github.com/bcgov/cas-registration/issues/321

BCEID roles

---

client/app/components/form/FormBase.tsx
client/app/components/form/widgets/PostalCodeWidget.tsx
client/app/components/form/widgets/index.ts
client/app/utils/jsonSchema/operations.ts
client/app/utils/jsonSchema/userOperator.ts
docs/rjsf-forms.md

319 postal code widget

---

bc_obps/registration/api/operator.py
bc_obps/registration/api/user_operator.py
bc_obps/registration/tests/test_endpoints.py
bc_obps/registration/utils.py
client/app/(authenticated)/bceidbusiness/industry_user/dashboard/select-operator/(request-access)/user-operator/[id]/page.tsx
client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/select-operator/(request-access)/user-operator/[id]/page.tsx
client/app/components/button/RequestAccessButton.tsx
client/app/components/form/ConfirmSelectedOperatorForm.tsx
client/app/components/form/SelectOperatorForm.tsx
client/app/components/form/SubmitButton.tsx
client/app/components/form/UserOperatorForm.tsx
client/app/components/form/UserOperatorMultiStepForm.tsx
client/app/components/form/formDataTypes.ts
client/app/components/form/widgets/RadioWidget.tsx
client/app/components/form/widgets/TextWidget.tsx
client/app/components/routes/select-operator/Page.tsx
client/app/components/routes/select-operator/form/AccessRequestReceived.tsx
client/app/components/routes/select-operator/form/ConfirmSelectedOperator.tsx
client/app/components/routes/select-operator/form/SelectOperator.tsx
client/app/components/routes/select-operator/form/UserOperator.tsx
client/app/components/routes/select-operator/request-access/user-operator/Page.tsx
client/app/styles/rjsf/FieldTemplate.tsx
client/app/styles/rjsf/FieldTemplateWithSubmitButton.tsx
client/app/styles/rjsf/InlineFieldTemplate.tsx
client/app/utils/jsonSchema/selectOperator.ts
client/app/utils/jsonSchema/userOperator.ts

[ZH CARD 299](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/299)

feat: prime admin request access existing operator

---

client/app/components/form/FormBase.tsx
client/app/utils/customTransformErrors.ts
client/app/utils/jsonSchema/operations.ts

card: https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/380
For manual testing, if you use the operations form, you can find postal code and BC Corporate # by adding a multiple operator, and phone #  in the application lead section (email and url won't show up until #316 is in)

380 custom error messages

---

client/app/components/routes/operations/form/OperationReview.tsx

fix: restrict operations review to cas internal

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/schema/user_operator.py
bc_obps/registration/tests/test_02_endpoints.py
client/app/(authenticated)/bceidbusiness/industry_user/dashboard/select-operator/(request-access)/pending/page.tsx
client/app/components/routes/select-operator/Page.tsx

card: https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/395

395 pending page

---

bc_obps/registration/api/operation.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py
bc_obps/registration/utils.py
client/app/components/datagrid/Note.tsx
client/app/components/routes/operations/Operations.tsx
client/app/components/routes/operations/Page.tsx

card: https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/421
Note: endpoint tests for this one will be done/updated in https://github.com/bcgov/cas-registration/pull/365/files#diff-7005d218482c3e6376907505440ee05d887e6364f099fff3f4a728d8309841f1

421 ops table

---

client/app/(authenticated)/idir/cas_admin/dashboard/operations/[operation]/[formSection]/page.tsx
client/app/(authenticated)/idir/cas_analyst/dashboard/operations/[operation]/[formSection]/page.tsx
client/app/(authenticated)/idir/cas_analyst/dashboard/operations/page.tsx

fix: add missing operations pages in idir routes

---

bc_obps/registration/api/operator.py
client/app/components/button/RequestAccessButton.tsx
client/app/components/form/UserOperatorContactForm.tsx
client/app/components/form/UserOperatorForm.tsx
client/app/components/form/UserOperatorMultiStepForm.tsx
client/app/components/routes/select-operator/form/UserOperator.tsx
client/app/components/routes/select-operator/request-access/user-operator/Page.tsx

[ZH CARD 498](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/498)

Fix 498 prime admin request when operator exists

---

client/app/components/routes/operations/form/Operation.tsx

Small PR to display the naics description beside the code in the naics dropdown for extra context.

chore: display naics description in naics dropdown

---

bc_obps/.dockerignore
bc_obps/Dockerfile
bc_obps/bc_obps/settings.py
bc_obps/poetry.lock
bc_obps/pyproject.toml

[Issue 513](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49835390)
At this stage, adding Nginx is not necessary since we are not using the Django template engine and therefore we don't serve static files often.

chore: replace Django dev server with gunicorn

---

bc_obps/registration/api/naics.py
bc_obps/registration/api/operator.py
bc_obps/registration/api/user_operator.py
bc_obps/registration/schema/user_operator.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py
client/app/components/datagrid/ChangeUserOperatorStatusColumnCell.tsx
client/app/components/routes/access-requests/form/UserOperatorReview.tsx
client/app/components/routes/select-operator/Page.tsx

[ISSUE 379](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48609618) and [ISSUE 640](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=50561029)

379 delete rejected prime admin

---

client/app/(authenticated)/dashboard/problem/page.tsx
client/app/data/dashboard/cas_admin.json
client/app/data/dashboard/cas_analyst.json
client/app/data/dashboard/industry_user.json
client/app/data/dashboard/industry_user_admin.json

Chore: replace /problem page with mailto link
Card: https://github.com/bcgov/cas-registration/issues/399

399 - Report a Problem mailto link

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py
client/app/(authenticated)/bceidbusiness/industry_user/dashboard/select-operator/(request-access)/user-operator/[id]/[formSection]/page.tsx
client/app/(authenticated)/bceidbusiness/industry_user/dashboard/select-operator/(request-access)/user-operator/create/[formSection]/page.tsx
client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/select-operator/(request-access)/user-operator/[id]/[formSection]/page.tsx
client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/select-operator/(request-access)/user-operator/create/[formSection]/page.tsx
client/app/components/form/MultiStepFormBase.tsx
client/app/components/form/OperationsForm.tsx
client/app/components/form/UserOperatorMultiStepForm.tsx
client/app/components/routes/select-operator/Page.tsx
client/app/components/routes/select-operator/form/UserOperator.tsx
client/app/components/routes/select-operator/request-access/user-operator/Page.tsx

Implements #441 
Previous PR for reference. It was old and getting unmanageable: https://github.com/bcgov/cas-registration/pull/487

441 - operator tile

---

helm/cas-registration/templates/frontend/deployment.yaml

Add necessary env var from #669 to frontend deployment.yaml

chore: add missing env var to deployment yaml

---

bc_obps/registration/fixtures/mock/operation.json
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py
client/app/(authenticated)/dashboard/page.tsx
client/app/(authenticated)/dashboard/profile/page.tsx
client/app/components/button/Review.tsx
client/app/components/datagrid/ChangeUserOperatorStatusColumnCell.tsx
client/app/components/datagrid/Note.tsx
client/app/components/form/ConfirmSelectedOperatorForm.tsx
client/app/components/form/OperationsForm.tsx
client/app/components/form/formDataTypes.ts
client/app/components/routes/access-requests/AccessRequests.tsx
client/app/components/routes/access-requests/form/UserOperatorReview.tsx
client/app/components/routes/operations/Operations.tsx
client/app/components/routes/operations/Page.tsx
client/app/components/routes/operations/form/Operation.tsx
client/app/components/routes/operations/form/OperationReview.tsx
client/app/components/routes/select-operator/form/UserOperator.tsx
client/app/data/dashboard/industry_user.json
client/app/data/dashboard/industry_user_admin.json

https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49836037

552 copy changes

---

bc_obps/registration/api/operation.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py

[ISSUE 584](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=50159779)

feat: approve operator when granting boro id

---

client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/users/page.tsx

[ISSUE 641](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=50566783)

chore: update `userRole` to `accessType` in user dashboard page

---

bc_obps/registration/schema/operation.py
client/app/components/routes/operations/form/Operation.tsx
client/app/components/routes/operations/types.ts

https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51077093
There's a lot of work in flight re the operation form right now, so this PR just fixes the bug. I'll make a tech debt card to finish moving data transformation out of the front-end and into the schema.

fix: correct operation id

---

client/app/(authenticated)/dashboard/profile/page.tsx

chore: text change

---

bc_obps/.env.example
bc_obps/bc_obps/settings.py
bc_obps/registration/api/user.py

chore: add `BYPASS_ROLE_ASSIGNMENT` flag

---

client/app/components/button/RequestAccessButton.tsx
client/app/components/form/ConfirmSelectedOperatorForm.tsx
client/app/components/routes/select-operator/form/AccessRequestReceived.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51308566

chore: text changes

---

bc_obps/registration/api/user.py
bc_obps/registration/migrations/0001_initial.py
bc_obps/registration/models.py
bc_obps/registration/schema/user.py
bc_obps/registration/tests/endpoints/test_user_endpoints.py
bc_obps/registration/tests/test_models.py
client/app/api/auth/[...nextauth]/route.ts
client/app/components/routes/profile/form/UserForm.tsx
client/app/types/next-auth.d.ts

Fetches the bceid business name/guid from the keycloak token & saves these values to the database for the user.

Fix: 770 save business guids

---

bc_obps/.env.example
bc_obps/bc_obps/settings.py
bc_obps/poetry.lock
bc_obps/pyproject.toml
client/.env.example
client/.gitignore
client/app/(authenticated)/error.tsx
client/app/(onboarding)/error.tsx
client/app/global-error.tsx
client/app/utils/actions.ts
client/next.config.js
client/package.json
client/sentry.client.config.ts
client/sentry.edge.config.ts
client/sentry.server.config.ts
client/yarn.lock
helm/cas-registration/templates/backend/deployment.yaml
helm/cas-registration/templates/frontend/deployment.yaml

[ISSUE 164](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48610025)

164 setup sentry

---

bc_obps/registration/api/operation.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py
bc_obps/registration/tests/utils/bakers.py

https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51179688

fix: operators can only edit their own operations

---

client/app/(onboarding)/home/page.tsx
client/app/(onboarding)/layout.tsx
client/app/components/navigation/Session.tsx

Implements #750 
This also removes the login buttons in the nav which I will miss for ease of access. Though I'm sure we'll get used to using the landing page logins instead.

750 refine homepage

---

bc_obps/.env.example
bc_obps/Makefile
bc_obps/registration/management/commands/create_superuser.py
bc_obps/registration/schema/operator.py
bc_obps/registration/tests/endpoints/test_operator_endpoints.py

[ISSUE 786](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=51682433)

786 operator physical address not showing

---

client/app/components/button/Review.tsx
client/app/components/form/UserOperatorMultiStepForm.tsx
client/app/components/routes/access-requests/form/UserOperatorReview.tsx

Implements #806 
Added a couple comments below for your consideration thanks!

Remove "Request Changes" feature for Operators

---

bc_obps/registration/api/operation.py
bc_obps/registration/api/operator.py
bc_obps/registration/api/user.py
bc_obps/registration/api/user_operator.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py

https://github.com/orgs/bcgov/projects/122?pane=issue&itemId=51329638
To manually test, I raised an error in the `transaction.atomic()` block and tried to submit the form. It errored and the form was still editable.

fix: operation form in undefined state

---

bc_obps/bc_obps/settings.py

chore: set gcs overwrite to false

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/fixtures/mock/user.json
bc_obps/registration/schema/user_operator.py
client/app/components/accordion/Accordion.tsx
client/app/components/button/Review.tsx
client/app/components/datagrid/OperationDataGrid.tsx
client/app/components/form/MultiStepAccordion.tsx
client/app/components/form/UserOperatorForm.tsx
client/app/components/form/UserOperatorReviewForm.tsx
client/app/components/form/formDataTypes.ts
client/app/components/routes/access-requests/form/UserOperatorReview.tsx
client/app/components/routes/select-operator/form/UserOperator.tsx
client/app/utils/jsonSchema/userOperator.ts

As a CAS user, I want to see user information when approving prime admins #869

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/api/utils/handle_parent_operators.py
bc_obps/registration/schema/parent_operator.py
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py
client/app/utils/jsonSchema/userOperator.ts

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=52562357
Please pay special attention to the python--I'm fairly confident that it works, but less confident it's good python and sonarcloud agrees
I'll dimiss the sonarcloud fails in the testing files if the reviewer is okay with it. There's an open PR with a slight refactor to the baker files to make for less repetition, but not in yet: https://github.com/bcgov/cas-registration/pull/871/files#diff-f0d287d6538eb3a422d5728bcffb9fa1cd9bc62c78eb9326a2394f2f715c1a9d

840 fix parent operators

---

bc_obps/registration/fixtures/mock/bc_obps_regulated_operation.json
bc_obps/registration/fixtures/mock/operation.json
client/app/components/form/MultiStepButtons.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53303290
To test:
- to see the save and continue, go into an approved or not started operation
- to see the next, go into a pending operation

923 save and continue

---

client/app/components/form/titles/operationsTitles.tsx

chore: update statutory declaration page link and copy

---

client/e2e/pages/authenticated/dashboard/profile/page.spec.ts
client/e2e/pages/onboarding/home/page.spec.ts
client/e2e/poms/profile.ts
client/e2e/utils/helpers.ts
client/e2e/utils/queries.ts
client/e2e/workflows/bceidbusiness/new_user.spec.ts

Addresses [916](https://github.com/bcgov/cas-registration/issues/916)
- new file:   client/e2e/utils/queries.ts
- new file:  client/e2e/pages/authenticated/dashboard/profile/page.spec.ts
- ` client/e2e/pages/authenticated/dashboard/profile/page.spec.ts` for comprehensive coverage of Profile page's functionality for each role
**Option 1:** Download artefact files from `GitHub Actions\Test Registration App` to your `client/playwright-report` folder and run command `cd client && yarn playwright show-report`
[CI artefact](https://github.com/bcgov/cas-registration/actions/runs/7978090736#artifacts)
[CI artefact download](https://github.com/bcgov/cas-registration/actions/runs/7978090736/artifacts/1260453300)
**Option 2:** Local e2e testing:
**Pre-reqs** 
1. From file …

916 e2e test\pages\profile

---

bc_obps/registration/fixtures/mock/parent_operator.json
client/app/styles/rjsf/ArrayFieldTemplate.tsx

fix: hide parent operator button if form is disabled

---

client/app/components/datagrid/Note.tsx
client/app/components/form/UserOperatorForm.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54180122

chore: update operator form text

---

client/app/components/form/FormBase.tsx
client/app/utils/customTransformErrors.ts

[ISSUE 904](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53170466)

904 error message for statutory declaration field

---

bc_obps/registration/schema/operation.py

[ISSUE 985](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54763048)

985 Fix BCGHG ID validation error

---

bc_obps/registration/api/operator.py
bc_obps/registration/schema/operator.py
bc_obps/registration/tests/endpoints/test_operator_endpoints.py
client/app/components/form/SelectOperatorForm.tsx
client/app/components/form/widgets/OperatorSearchWidget.tsx

Part of API security checks [ISSUE 217](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48610037)
AND
[ISSUE 943](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53916182)
AND
[ISSUE 895](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53049591)

217 api security checks - Operator ONLY

---

client/app/components/button/RequestChanges.tsx
client/app/components/button/Review.tsx
client/app/components/routes/operations/form/Operation.tsx
client/app/components/routes/operations/form/OperationReview.tsx

[ISSUE 888](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53043481)

888 display changes requested section

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54768130

fix: update error message when declining prime admins

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py

NOTE: Temp fix until we get to the full implementation in ticket #470

fix: adjust role assignment for approved user operators

---

bc_obps/registration/schema/user_operator.py
client/app/components/datagrid/OperationDataGrid.tsx
client/app/components/datagrid/OperatorDataGrid.tsx
client/app/components/form/OperationsForm.tsx
client/app/components/form/SelectOperatorForm.tsx
client/app/components/navigation/Bread.tsx
client/app/components/routes/select-operator/Page.tsx
docs/developer-guide.md

[Card](https://github.com/bcgov/cas-registration/issues/1000)
- Replaces UUID in breadcrumbs with a more descriptive text 
**Pre-reqs**
```
cd bc_obps
make reset_db
make run
```  
```
cd client && yarn build && yarn start
```  
3. From terminal command, add your IDIR user as `cas_admin` role through psql tool
```
cd bc_obps && psql
```
```
\c registration
```
```
INSERT INTO erc.user (user_guid, app_role_id, first_name, last_name , position_title , email, phone_number, business_guid, bceid_business_name )
VALUES ('YOUR_USER_GUID_NO_HYPHENS','cas_admin','first_name','last_name ','position_title ','email@email.com','16044015477','efb76d57-88b7-4eb6-9f26-ec12b49c14c1','bceid_business_n …
```

1000 breadcrumb title

---

client/app/components/form/widgets/FileWidget.tsx

[ISSUE 986](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54765288)

fix: store the state to prevent loosing it when switching tabs

---

client/e2e/workflows/idir/cas_pending.spec.ts

[ISSUE 846](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=52567549)

Test: add test for `cas_pending` role

---

client/app/components/datagrid/UserOperatorDataGrid.tsx

chore: remove user id from user management table

---

bc_obps/registration/api/user_operator.py
bc_obps/registration/fixtures/mock/user.json
bc_obps/registration/schema/user_operator.py
client/app/components/routes/access-requests/AccessRequests.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=49865585

480 bceid in table

---

deploy.sh
shipit.yml

Modifying the deploy process to run a bash script instead of having the commands coded into the shipit.yml file. I was unable to create another stack in shipit to test the branch on, so this is the test, on giraffe-develop.

Create deploy script

---

deploy.sh

Just adding a print statement to figure out whats going on

chore: add debug statement

---

bc_obps/registration/api/operation.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=55765151

1053 fix: set user audit columns for documents

---

CHANGELOG.md
helm/cas-registration/templates/backend/deployment.yaml
helm/cas-registration/templates/frontend/deployment.yaml
package.json

quick helm template fix + release

Chore: release v1.2.2

---

client/app/components/datagrid/UserOperatorDataGrid.tsx
client/app/components/datagrid/cells/StatusStyleColumnCell.tsx
client/app/components/datagrid/helpers.tsx
client/app/components/routes/access-requests/AccessRequests.tsx
client/app/components/routes/operations/Operations.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=52081252

811 myself pill

---

helm/cas-registration/templates/NetworkPolicy/mailhog-allow-from-openshift-ingress.yaml
helm/cas-registration/values-dev.yaml
helm/cas-registration/values-test.yaml

fix openshift runAsUser uid and allow ingress from openshift

chore: mailhog fixes

---

client/app/components/routes/operations/form/OperationReview.tsx
client/e2e/utils/enums.ts

card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=58047477

chore: change text in approve/decline messages

---

bc_obps/registration/api/operators.py
bc_obps/registration/schema/operator.py
bc_obps/registration/tests/endpoints/test_operator_endpoints.py
client/app/components/routes/access-requests/form/UserOperatorReview.tsx

1244 decline operator and user operators

---

helm/cas-registration/templates/backend/deployment.yaml

points the backend env vars to the secret created by cas-pipeline

chore: update backend deployment ches secrets

---

bc_obps/poetry.lock
bc_obps/pyproject.toml
bc_obps/registration/api/_operations/_operation_id/update_status.py
bc_obps/registration/api/_operations/operation_id.py
bc_obps/registration/api/operations.py
bc_obps/registration/tests/endpoints/test_operations_endpoints.py
bc_obps/registration/utils.py
bc_obps/service/operator_service.py
bc_obps/service/user_operator_service.py

[ISSUE 1300](https://github.com/bcgov/cas-registration/issues/1300)

chore: replace pytz with zoneinfo

---

bciers/apps/registration/app/components/operations/OperationsForm.tsx
bciers/apps/registration/app/components/userOperators/AccessRequestReceived.tsx

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=62558998
This PR updates the confirmation message on:
- admin access request
- subsequent access request
- add an operation request
Note: some of the happo diffs are flake, but there are also real (intended) changes because the confirmation message has changed.

Update confirmation message text

---

bciers/apps/registration/e2e/poms/operations.ts
bciers/apps/registration/e2e/poms/operators.ts
bciers/apps/registration/e2e/utils/enums.ts
bciers/apps/registration/e2e/workflows/bceidbusiness/industry_user_admin.spec.ts
bciers/apps/registration/e2e/workflows/idir/cas_admin.spec.ts
bciers/apps/registration/e2e/workflows/idir/cas_analyst.spec.ts

card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=61334238
This PR is part 2/? and:
- fixes the table row diff from hover
- fixes the pending operator detail page diff
- fixes accordions (?) I hope
Once the diffs settle, I'll refactor the tests so the assertions are in the POMs. It's easier to write experimental code directly in the test files so it's to find/edit/remove.
Note: Anytime someone merges a PR, since the diffs are currently flaky, our baseline accepted screenshots change. The screenshots I'm introducing in this PR should be the new more stable baseline accepted shots.

chore: debug happo

---

.github/actions/dev-env-setup/action.yml
.sonarcloud.properties
.tool-versions
bc_obps/.tool-versions
bc_obps/Dockerfile
bc_obps/bc_obps/settings.py
bc_obps/poetry.lock
bc_obps/pyproject.toml
erd_diagrams/erd_registration.md

[ISSUE 947](https://github.com/bcgov/cas-registration/issues/947)

947 bump django and python

---

docs/registration_part_2/backend-structure.md
docs/registration_part_2/data-models.md

card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=62182422
Most of the documentation of the card was already completed. I added a file for models and a little more info about testing to meet the AC.

docs: model and testing docs for v2

---

bc_obps/registration/management/commands/create_superuser.py
helm/cas-registration/templates/backend/job/add-django-admin.yaml

[ISSUE 1774](https://github.com/bcgov/cas-registration/issues/1774)

Job to add django admin in dev

---

bciers/apps/reporting/src/app/components/datagrid/models/operationColumns.tsx
bciers/apps/reporting/tests/pages/operationsColumns.test.tsx

Card: https://github.com/bcgov/cas-reporting/issues/223
Adding a more column to the operations table.

223 operations table more column

---

bc_obps/common/api/__init__.py
bc_obps/common/api/create_superuser.py
bc_obps/registration/management/commands/create_superuser.py
helm/cas-registration/templates/backend/job/add-django-admin.yaml

@dleard I added a logger to make CodeQL happy. The str(e) part was only raising `raise Exception('Superuser not created.')` if that command fails, and it is not sensitive data.

Fix django admin job

---

bc_obps/bc_obps/settings.py
helm/cas-bciers/templates/backend/deployment.yaml
helm/cas-registration/templates/backend/deployment.yaml

Adding `BACKEND_HOST` to deployment so we can use it in the `settings.py`

chore: add backend host var to deployment

---

.github/workflows/test-e2e.yaml
bciers/apps/registration1/playwright.config.ts

Addresses [1913](https://github.com/bcgov/cas-registration/issues/1931#issue-2401314528)

chore: remove Firefox from E2E CI

---

.github/workflows/build-coam.yaml
.github/workflows/main.yaml
bciers/apps/coam/next.config.js
bciers/apps/coam/project.json
helm/cas-bciers/templates/coam/deployment.yaml
helm/cas-bciers/templates/coam/route.yaml
helm/cas-bciers/templates/coam/service.yaml
helm/cas-bciers/values-dev.yaml
helm/cas-bciers/values.yaml

ci: configure coam for ci and deployment

---

bc_obps/common/migrations/0010_dashboarddata.py
bciers/apps/administration/app/components/contacts/ContactDataGrid.tsx
bciers/apps/administration/app/components/facilities/FacilityDataGrid.tsx
bciers/apps/administration/app/components/operations/OperationDataGrid.tsx
bciers/libs/components/src/datagrid/cells/ActionCellFactory.tsx
bciers/libs/components/src/datagrid/cells/OperationsActionCell.tsx
bciers/libs/components/src/navigation/Bread.tsx

I seem to remember the useEffect being necessary to keep the state while navigating with back/forward buttons, though this seems to be working? Sorry if I am missing something here 😅 
Either way the useEffect and state is required let me know, I think I can still make this work without the flicker.

chore: fix breadcrumb title flickering

---

bc_obps/registration/tests/utils/bakers.py
bc_obps/service/data_access_service/facility_service.py

[ISSUE 2019](https://github.com/bcgov/cas-registration/issues/2019)

fix: not showing facilities with end date

---

bc_obps/registration/api/v1/_contacts/contact_id.py
bc_obps/registration/fixtures/mock/address.json
bc_obps/registration/fixtures/mock/contact.json
bc_obps/registration/tests/endpoints/v1/_contacts/test_contact_id.py
bc_obps/registration/tests/utils/bakers.py
bc_obps/service/contact_service.py
bc_obps/service/data_access_service/contact_service.py
bc_obps/service/tests/data_access_service/test_data_access_contact_service.py
bc_obps/service/tests/test_contact_service.py
bciers/apps/administration/app/bceidbusiness/industry_user/contacts/[contactId]/page.tsx
bciers/apps/administration/app/bceidbusiness/industry_user/contacts/page.tsx
bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/[contactId]/page.tsx
bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/add-contact/page.tsx
bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/page.tsx
bciers/apps/administration/app/components/contacts/ContactForm.tsx
bciers/apps/administration/app/components/contacts/ContactPage.tsx
bciers/apps/administration/app/components/contacts/ContactsDataGrid.tsx
bciers/apps/administration/app/components/contacts/ContactsPage.tsx
bciers/apps/administration/app/components/contacts/types.ts
bciers/apps/administration/app/idir/cas_admin/contacts/[contactId]/page.tsx
bciers/apps/administration/app/idir/cas_admin/contacts/page.tsx
bciers/apps/administration/app/idir/cas_analyst/contacts/[contactId]/page.tsx
bciers/apps/administration/app/idir/cas_analyst/contacts/page.tsx
bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx
bciers/apps/administration/tests/components/contacts/ContactPage.test.tsx
bciers/apps/administration/tests/components/contacts/Contacts.test.tsx
bciers/apps/administration/tests/components/contacts/ContactsDataGrid.test.tsx
bciers/libs/components/src/form/SingleStepTaskListForm.test.tsx
bciers/libs/components/src/form/SingleStepTaskListForm.tsx

[ISSUE 1607](https://github.com/bcgov/cas-registration/issues/1607)

1607 edit contact

---

bc_obps/common/management/commands/truncate_dev_data_tables.py
bc_obps/reporting/migrations/0007_prod_data.py

Adds migration reversal for `reporting_year`.

chore: add reversal for reporting years

---

.github/actions/run-backend/action.yml
bc_obps/.env.example
bc_obps/bc_obps/settings.py
bc_obps/common/api/create_superuser.py
bc_obps/registration/api/v1/e2e_test_setup.py
helm/cas-bciers/values-dev.yaml
helm/cas-registration/values-dev.yaml
helm/cas-registration/values-prod.yaml

we were interchangeably using "develop"/"production" & "dev"/"prod". This can cause comparison errors down the line.
This PR syncs the usage to be "dev"/"prod"

chore: use dev/prod rather than develop/production

---

bc_obps/bandit.yaml
bc_obps/common/management/commands/check_migrations_with_prod_data.py
bc_obps/common/management/commands/custom_migrate.py

Part of [ISSUE 2012](https://github.com/bcgov/cas-registration/issues/2012)

Command to check migrations with prod data

---

bciers/libs/components/src/navigation/Bread.test.tsx
bciers/libs/components/src/navigation/Bread.tsx

Addresses: 
[2063](https://github.com/bcgov/cas-registration/issues/2063)
- Refactored  `Bread` for `register-an-operation`
- Added `Bread` vitest
```
cd bc_obps
make reset_db
make run
```  
```
```  
- http://localhost:3000/registration/register-an-operation
- http://localhost:3000/registration/register-an-operation/e8f913c5-7636-42f8-92f1-b90cad5f9ecc/2
- http://localhost:3000/administration/contacts/10?contacts_title=Henry%20Ives
- http://localhost:3000/administration/contacts/add-contact
- http://localhost:3000/administration/operations
- http://localhost:3000/administration/operations/002d5a9e-32a6-4191-938c-2c02bfec592d/facilities?operations_title=Ope …

Breadcrumbs refactor for register an operation

---

helm/cas-bciers/templates/administration/deployment.yaml
helm/cas-bciers/templates/registration/deployment.yaml

missing keycloak & nextauth env vars

chore: add missing env vars to administration module

---

bciers/libs/components/src/form/fields/NestedArrayFieldTemplate.tsx

Fixed Spacing issue for activity page mentioned in card: https://github.com/bcgov/cas-reporting/issues/302
We also have a ticket https://github.com/bcgov/cas-reporting/issues/319

chore:fixed spacing issue in activity page

---

bciers/apps/administration/app/components/facilities/FacilityForm.tsx
bciers/apps/administration/app/data/jsonSchema/facilitiesLfo.ts
bciers/apps/administration/app/data/jsonSchema/facilitiesSfo.ts
bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx
bciers/libs/components/src/form/fields/InlineArrayFieldTemplate.tsx
bciers/libs/components/src/form/fields/index.ts

#2006
- chore: Add missing formats for facility date from last PR
- feat: Create inline array field template for well auth numbers

2006 well auth

---

.github/workflows/test-backend.yaml
bc_obps/reporting/tests/service/test_reporting_dashboard_service.py

just adding some logging to a test that was previously flaky. Re-enabling test & waiting for it to fail

chore: add logging to flaky test

---

bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts
bciers/apps/reporting/src/app/components/activities/uiSchemas/gscOtherThanNonCompression.ts
bciers/apps/reporting/src/app/components/activities/uiSchemas/gscUiSchema.ts
bciers/apps/reporting/src/app/components/activities/uiSchemas/refineryFuelGasUiSchema.ts

add missing fuelClassification to uiOrder in the uiSchemas that were missing it

chore: add fuelClassification to uiSchemas

---

bciers/package.json
bciers/yarn.lock

Don't merge until we have reg1 e2e tests running in CI again--good to go now, #2201 is merged
No card, yarn audit in CI failed

chore: update next

---

bciers/apps/administration/app/components/contacts/ContactForm.tsx
bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx

card: https://github.com/bcgov/cas-registration/issues/2092
Most of the work for this was completed in #2187 . This PR is just a cleanup to the url

chore: fix new contact redirect url

---

bc_obps/service/facility_service.py
bc_obps/service/tests/test_facility_service.py
bciers/apps/administration/app/components/facilities/FacilitiesPage.tsx
bciers/apps/administration/tests/components/facilities/FacilitiesPage.test.tsx

fix: Remove add facility button for SFO and include check on backed POST to ensure SFO has 1 facility

---

bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/sign-off/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/sign-off/page.tsx
bciers/apps/reporting/src/app/components/signOff/Success.tsx
bciers/apps/reporting/src/app/components/signOff/signOffPage.tsx
bciers/apps/reporting/src/app/components/signOff/types.ts
bciers/apps/reporting/src/app/utils/formatDate.ts
bciers/apps/reporting/src/data/jsonSchema/signOff.ts
bciers/apps/reporting/tests/components/SignOffPage.test.tsx
bciers/libs/components/src/form/FormBase.tsx
bciers/libs/components/src/form/MultiStepFormWithTaskList.tsx
bciers/libs/components/src/form/widgets/CheckboxWidget.tsx

Card: https://github.com/bcgov/cas-reporting/issues/207
Changes:
- Added Sign Off Page
- Added Schema for Sign off page
- Modified MultiStepFormWithTaskList Component to have optional props
- Modified format date file- added two more functions
- Modified Formbase: added custom error for signature
- Modified checkbox widget to have alignment option

Reports Sign Off Page

---

bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx
bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
bciers/libs/components/src/form/MultiStepBase.test.tsx
bciers/libs/components/src/form/widgets/DateWidget.test.tsx
bciers/libs/components/src/form/widgets/SelectWidget.test.tsx

Fixes tests that were failing/flaky in PRs recently. I created a card for ones that required further research: https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration+make+sure&pane=issue&itemId=82117219

test: add await to MultiStepBase

---

package.json

Adding migration tags to release commits to automate the process.

Add migration tags to release commits automatically

---

bciers/apps/reporting/src/app/components/facility/FacilityReview.tsx
bciers/apps/reporting/tests/components/FacilityReview.test.tsx

quick edit to the facility review page that connects it to the first activity page on save & continue.

chore: facility review connects to activities

---

bciers/apps/registration/app/components/operations/registration/OperationInformationForm.tsx
bciers/apps/registration/app/components/operations/registration/enums.ts
bciers/apps/registration/app/data/jsonSchema/operationInformation/registrationPurpose.ts
bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
bciers/libs/components/src/form/widgets/MultiSelectWidget.tsx

[ISSUE 2313](https://github.com/bcgov/cas-registration/issues/2313)
**TEST:**
- Log in as an industry user (bc-cas-dev)
- Navigate to the operation registration form
- Choose a registration purpose from the dropdown
- View the relevant help text located below the dropdown

2313 Descriptions for each purpose

---

bc_obps/reporting/tests/service/test_report_activity_save_service/test_save_report_activity.py

Should fix the sonarcloud reliability rating warning

test: fix comparison in test to address sonarcloud reliability rating

---

bc_obps/registration/models/operation.py
bc_obps/registration/schema/v2/operation.py
bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/_registration/test_operation.py
bc_obps/registration/tests/endpoints/v2/_operations/test_operation_id.py
bc_obps/registration/tests/endpoints/v2/test_operations.py
bc_obps/service/operation_service_v2.py
bc_obps/service/tests/test_operation_service_v2.py
bciers/apps/administration/app/data/jsonSchema/operationInformation/operationInformation.ts
bciers/apps/administration/tests/components/operations/OperationInformationPage.test.tsx
bciers/apps/registration/app/data/jsonSchema/operationInformation/registrationPurpose.ts
bciers/apps/registration/app/data/jsonSchema/operationRegistration/operationInformationText.tsx
bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx

[ISSUE 2324](https://github.com/bcgov/cas-registration/issues/2324)

2324 - Remove equipment list document from operation

---

bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx
bciers/apps/reporting/src/data/jsonSchema/personResponsible.ts
bciers/apps/reporting/src/data/jsonSchema/personResponsibleInfoText.tsx

Card: https://github.com/bcgov/cas-reporting/issues/364
Changes:-
- Added Sync button
- Added Sync button handler

chore:added sync button

---

bc_obps/registration/api/v1/_contacts/contact_id.py
bc_obps/registration/api/v1/_user_operators/_current/operator_users.py
bc_obps/registration/api/v1/_user_operators/user_operator_id.py
bc_obps/registration/api/v1/_users/user_id.py
bc_obps/registration/api/v1/contacts.py

[ISSUE 2089](https://github.com/bcgov/cas-registration/issues/2089)

2089 Grant access to restricted endpoints for both admin and non-admin external users

---

bciers/apps/administration/app/data/jsonSchema/facilitiesLfo.ts
bciers/apps/registration/app/data/jsonSchema/operationRegistration/facilityInformation.ts
bciers/libs/components/src/form/fields/ArrayFieldTemplate.tsx

fix: Add boolean option to allow deletion of first array field template item

---

bciers/apps/administration/app/components/facilities/FacilitiesDataGrid.tsx
bciers/apps/administration/app/components/facilities/types.ts
bciers/apps/administration/tests/components/facilities/FacilitiesDataGrid.test.tsx

[ISSUE 2415](https://github.com/bcgov/cas-registration/issues/2415)

Fix facility data grid old id reference

---

docs/team_release_process.md

From our team discussion around the non-technical release process & how to address tickets when being reviewed in develop.
Did I miss anything?

docs: team process release documentation

---

bciers/apps/administration/app/components/operations/OperationInformationPage.tsx
bciers/apps/administration/app/data/jsonSchema/operationInformation/administrationOperationInformation.ts
bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx
bciers/apps/administration/tests/components/operations/OperationInformationPage.test.tsx

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=85592917&issue=bcgov%7Ccas-registration%7C2438
This PR:
- checks for status in the rjsf schema-generating function
- new vitest and updates to existing ones
Happo is flake

2438: conditionally show registration info based on status

---

bc_obps/Dockerfile

my previous attempt to do this programatically didn't work. Just fixing the version and hardcoding again for now

chore: hardcode poetry version in docker ENV

---

bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/_registration/test_opted_in_operation.py
bc_obps/registration/tests/integration/test_operation_registration.py
bc_obps/registration/tests/models/test_operation.py
bc_obps/registration/tests/utils/baker_recipes.py
bc_obps/service/operation_service_v2.py
bc_obps/service/tests/test_operation_service_v2.py

[ISSUE 2376](https://github.com/bcgov/cas-registration/issues/2376)
**NOTES:**
- Added a missing test for the `user_has_access` function (for Operation)
- Corrected the endpoint name in the test.
- Populated the `submission_date` field when the user submits an operation.
- Added an integration test covering all registration purposes workflows.

2376 Integration test for registration workflow

---

bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/final-review/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/final-review/page.tsx
bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx
bciers/apps/reporting/src/app/components/finalReview/FinalReviewPage.tsx
bciers/apps/reporting/src/app/components/taskList/5_signOffSubmit.ts

Placeholder PR for the Final review page, to unblock the full SFO workflow

Final review page: Placeholder for SFO workflow

---

bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx
bciers/apps/reporting/src/data/jsonSchema/facility/facilityEmissionAllocation.tsx
bciers/apps/reporting/src/tests/components/additionalInformation/AdditionalReportingData.test.tsx
bciers/libs/components/src/form/widgets/TextAreaWidget.test.tsx
bciers/libs/components/src/form/widgets/TextAreaWidget.tsx
bciers/libs/components/src/form/widgets/index.ts

Navigation button issues introduced in #2546 
- Missing `Back` button
- `Save` routes to next page
**Bug:**
**Fix:**

fix: additional data nav buttons

---

bciers/apps/reporting/src/app/components/operations/OperationReview.tsx

Card: N/A
Changes:- A small fix for post url

Chore fixed submit url

---

bciers/apps/administration/app/data/jsonSchema/operationInformation/multipleOperatorsInformation.ts

[ISSUE 2565](https://github.com/bcgov/cas-registration/issues/2565)

2565 Fix confusing error on extraprovincial operator toggle

---

bciers/apps/reporting/src/data/jsonSchema/personResponsible.ts
bciers/apps/reporting/src/tests/components/operations/personResponsible/PersonResponsible.test.tsx

Card - N/A
Small PR to fix title of person responsible page

chore:fixed person responsible page title

---

bc_obps/reporting/service/compliance_service.py

Show zeroes in the calculated values for new entrants on the compliance summary

chore: show zeroes in calculated fields for new entrants compliance

---

bc_obps/registration/fixtures/mock/bc_greenhouse_gas_id.json
bc_obps/registration/fixtures/mock/facility.json
bc_obps/registration/fixtures/mock/facility_designated_operation_timeline.json
bc_obps/registration/fixtures/mock/operation.json
bc_obps/reporting/service/compliance_service.py

Makes operation 19 a New Entrant & adds a designated facility for that SFO so it can complete the report flow

chore: update dev data to have new entrant & proper default activities

---

bciers/apps/administration/tests/components/operations/OperationDataGrid.test.tsx
bciers/libs/components/src/datagrid/cells/operations/OperationsActionCell.tsx

No card
This PR:
- changes the Link tag to an a because even with passHref, Link seemed flaky

Fix grid link

---

bciers/apps/reporting/src/data/jsonSchema/reviewOperationInformationText.tsx

Card: https://github.com/bcgov/cas-reporting/issues/432
changes: fixed alert box content

chore: fixed alert box content

---

bc_obps/registration/admin.py
bc_obps/registration/schema/v2/operation_timeline.py
bc_obps/registration/tests/endpoints/v2/test_operations.py
bciers/apps/administration/app/components/datagrid/models/operations/operationColumns.ts
bciers/apps/administration/app/components/operations/types.ts
bciers/apps/administration/tests/components/operations/OperationDataGrid.test.tsx

[Issue 2414](https://github.com/bcgov/cas-registration/issues/2414)

2414 operations grid shows more details for boro id

---

bc_obps/reporting/service/report_verification_service.py
bc_obps/reporting/tests/service/test_report_verification_service.py
bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx
bciers/apps/reporting/src/app/components/activities/uiSchemas/aluminumUiSchema.ts

#272 update
- fix: replace , with & in sourceType join aggregation to build_schema to avoid undefined type
- style: Move smeltertechtype on alumina page below the annual emissions

alumina update

---

bciers/apps/reporting/src/app/components/datagrid/models/operations/operationColumns.tsx
bciers/apps/reporting/src/app/utils/createReport.ts
bciers/apps/reporting/src/tests/components/dataGrid/model/operations/operationColumns.test.tsx

Addresses:
[462](https://github.com/bcgov/cas-reporting/issues/462)
[422](https://github.com/bcgov/cas-reporting/issues/442)
Impact:
- Add check to redirect of start button on reporting dashboard so redirect doesn't go to undefined page
Testing:
- go to reporting dashboard
- spam click a start button

462 Start button redirects to undefined if clicked multiple times

---

bciers/libs/components/src/datagrid/DataGrid.tsx

Card: N/A
A small PR to remove console statement from Data grid component

chore: removed console statement from Data grid

---

bciers/libs/components/src/navigation/Bread.test.tsx
bciers/libs/components/src/navigation/Bread.tsx

[352](https://github.com/bcgov/cas-reporting/issues/352)

352 filter out Facilities crumb from breadcrumb component

---

bc_obps/reporting/json_schemas/2024/aluminum_production/anode_consumption_acbgcc.json
bc_obps/reporting/json_schemas/2024/aluminum_production/anode_effects.json
bc_obps/reporting/json_schemas/2024/aluminum_production/cover_gas_from_electrolysis.json

[509](https://github.com/bcgov/cas-reporting/issues/509)

509 alumina emission doesn't have default

---

bciers/apps/registration/app/data/jsonSchema/operationRegistration/newEntrantOperation.ts
bciers/apps/registration/tests/components/operations/registration/NewEntrantOperationForm.test.tsx
bciers/libs/utils/src/urls.ts

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=85282920&issue=bcgov%7Ccas-registration%7C2426
This PR:
- add links
- vitests

2426 new entrant links

---

bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx
bciers/apps/reporting/src/app/components/finalReview/FinalReviewPage.tsx
bciers/apps/reporting/src/tests/components/finalReview/FinalReviewForm.test.tsx

Addresses [523](https://github.com/bcgov/cas-reporting/issues/523)

523 Final Report Review - "Continue" conditional routing

---

bciers/libs/components/src/form/widgets/MultiSelectWidget.tsx

[430](https://github.com/bcgov/cas-reporting/issues/430)

chore: wrap text in chips in MultiSelectWidget

---

bciers/apps/reporting/src/app/components/facility/FacilityReviewForm.tsx
bciers/apps/reporting/src/app/components/facility/FacilityReviewPage.tsx
bciers/apps/reporting/src/data/jsonSchema/facilities.ts
bciers/apps/reporting/src/tests/components/facility/FacilityReviewForm.test.tsx

Card: https://github.com/bcgov/cas-reporting/issues/320
Changes:-
1. FIxed the header steps
2. Added tasklist elements
3. FIxed - facility name, Facility BCGHG ID
4. changed facility type to select
To test:-
http://localhost:3000/reporting/reports/2/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aec/review

chore: fixed facility review page

---

bc_obps/service/report_service.py
bc_obps/service/tests/test_report_service.py

Card: https://github.com/bcgov/cas-reporting/issues/524
Changes:-
Added Regulated Products on saving reports

chore:fixed the bug for regulated products

---

bc_obps/reporting/service/reporting_dashboard_service.py
bc_obps/reporting/tests/service/test_reporting_dashboard_service.py

Card: https://github.com/bcgov/cas-reporting/issues/515
Changes:-
- Added filter while fetch operations for report table
- modified test(service)

chore:added filtering only registered operations

---

helm/cas-bciers/values-dev.yaml
helm/cas-bciers/values-test.yaml

- Updated memory resource configurations in values-test/dev.yaml for improved resource allocation:
- Increased memory limit from 6Mi to 256Mi
- Increased memory request from 32Mi to 128Mi
These changes align the memory settings with our standard resource configurations and ensure adequate memory allocation for the test environment components. Previous memory settings were causing frequent OOMKills in dev environment, leading to container restarts and service disruptions.
```
resources:
limits:
cpu: 200m
memory: 256Mi
requests:
cpu: 60m
memory: 128Mi
```

chore: increase compliance app resources for dev and test

---

bc_obps/common/tests/endpoints/auth/test_endpoint_permissions.py
bc_obps/reporting/api/__init__.py
bc_obps/reporting/api/report_review_facilties.py
bc_obps/reporting/schema/report_review_facility.py
bc_obps/reporting/service/report_facilities_service.py
bc_obps/reporting/tests/api/test_report_review_facilities_api.py
bc_obps/reporting/tests/service/test_report_facilities_service.py
bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/facilities/review-facilities-list/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/review-facilities-list/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/facilities/lfo-facilities/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/facilities/review-facilities-list/page.tsx
bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/review-facilities-list/page.tsx
bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx
bciers/apps/reporting/src/app/components/operations/reviewFacilities/ReviewFacilitiesForm.tsx
bciers/apps/reporting/src/app/components/operations/reviewFacilities/ReviewFacilitiesPage.tsx
bciers/apps/reporting/src/app/components/taskList/1_operationInformation.ts
bciers/apps/reporting/src/app/utils/getOperationFacilitiesList.ts
bciers/apps/reporting/src/data/jsonSchema/reviewFacilities/reviewFacilities.ts
bciers/apps/reporting/src/data/jsonSchema/reviewFacilities/reviewFacilitiesInfoText.tsx
bciers/apps/reporting/src/tests/components/operations/reviewFacilities/ReviewFacilities.test.tsx
bciers/libs/actions/src/api/getFacilities.ts
bciers/libs/components/src/form/NavigationForm.tsx
bciers/libs/components/src/form/fields/SectionFieldTemplate.tsx
bciers/libs/components/src/modal/SimpleModal.tsx

signed pr for https://github.com/bcgov/cas-registration/pull/2689

 review selected facilities page

---

bciers/apps/reporting/src/app/components/reportInformation/facilities/FacilitiesDataGrid.tsx
bciers/apps/reporting/src/app/components/taskList/1_operationInformation.ts

Card: N/A
A small PR to fix review facilities list url in the tasklist

chore: fixed review facility url on tasklist

---

bc_obps/common/fixtures/dashboard/bciers/dev/external.json
bc_obps/common/fixtures/dashboard/bciers/prod/external.json

Card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=91274136&issue=bcgov%7Ccas-registration%7C2609

chore: update text on registration tile

---

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx
bciers/apps/reporting/src/app/components/activities/ActivityInit.tsx
bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx
bciers/apps/reporting/src/app/components/facility/FacilityReviewForm.tsx
bciers/apps/reporting/src/tests/components/activities/ActivityForm.test.tsx

Card: N/a
A small PR to fix activities url and url for end of facility report page

chore: fixed activity url

---

Makefile
helm/cas-bciers/Chart.lock
helm/cas-bciers/Chart.yaml
helm/cas-bciers/templates/reporting/deployment.yaml
helm/cas-bciers/values-dev.yaml

chore: added logging

---

bciers/apps/registration/app/components/operations/registration/enums.ts

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=91275305&issue=bcgov%7Ccas-registration%7C2612
This PR:
- updates text
- that's it! there were no vitests to update

Update opt-in help text description

---

bc_obps/registration/fixtures/mock/operation.json
bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx
bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataPage.tsx
bciers/apps/reporting/src/app/components/attachments/AttachmentsForm.tsx
bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx
bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/facilityActivitiesFactoryItem.ts
bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/factory.ts
bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/operationEmissionSummaryFactoryItem.ts
bciers/apps/reporting/src/tests/components/attachments/AttachmentsForm.test.tsx

Addresses [398](https://github.com/bcgov/cas-reporting/issues/398)
- Implements "LFO" Final Review
- Corrects "SFO" `Additional Data\Save and Continue` url
- Corrects  `Attachments\Save and Continue` url
```
cd bc_obps
make reset_db
make run
```  
```
```  
1. Navigate to http://localhost:3000
1. Navigate to `Bugle SFO - Registered` 
2. Complete all steps till `Final Review`
**Report Final Review display in read-only sections:**
- Review operation information
- Person Responsible for Submitting Report
- Report Information section with:
- Activity data
- Non-Attributable Emissions
- Emissions …

feat: LFO final review

---

helm/cas-bciers/Chart.yaml
helm/cas-bciers/templates/administration/deployment.yaml
helm/cas-bciers/templates/backend/deployment.yaml
helm/cas-bciers/templates/compliance/deployment.yaml
helm/cas-bciers/templates/registration/deployment.yaml

**Card**: https://github.com/bcgov/cas-registration/issues/2541
**Changes:**
- Added configuration to the deployment file to include the cas-logging-sidecar template.
- Integrated sidecar containers for logging.
- Updated volumes section to include logging-sidecar volumes.
- Configured containers to use sidecar container for log management.

chore:added logging for all apps

---

bc_obps/registration/middleware/current_user.py

[ISSUE 2906](https://github.com/bcgov/cas-registration/issues/2906)

chore: update get_or_cache_user to handle non-existent users gracefully

---

helm/cas-bciers/Chart.lock
helm/cas-bciers/Chart.yaml

A small PR to update version(pipeline) in charts to align with the latest changes in fluent bit config

chore: updated chart version

---

bciers/apps/dashboard/app/data/home/events.json
bciers/apps/dashboard/app/onboarding/page.tsx
bciers/apps/registration/tests/components/operations/registration/FacilityInformationForm.test.tsx
bciers/apps/registration/tests/components/transfers/TransferDetailForm.test.tsx
bciers/apps/registration1/app/(onboarding)/home/page.tsx
bciers/apps/registration1/app/data/home/events.json
bciers/apps/reporting/src/tests/components/operations/OperationReviewForm.test.tsx
bciers/apps/reporting/src/tests/components/operations/reviewFacilities/ReviewFacilities.test.tsx
bciers/libs/components/src/layout/RootLayout.tsx
bciers/libs/components/src/navigation/Bread.tsx
bciers/libs/utils/src/urls.ts

card: https://github.com/bcgov/cas-registration/issues/2747
This PR:
- adds a banner to the reg1 landing page
- disables the button 
- no need for a growthbook flag since we're not doing regular releases to reg1 prod and reg1 and 2 have different urls

chore: update landing page

---

helm/cas-bciers/values-prod.yaml
helm/cas-bciers/values-test.yaml

- scales FE deployments in test to 1 replica
- adds sidecar values to values-test yaml
- adds a values-prod yaml file

Chore: logging sidecar configmap + prod values file

---

bciers/apps/registration/app/data/jsonSchema/operationRegistration/operationRepresentative.ts
bciers/libs/components/src/form/widgets/OperationRepresentativeWidget.tsx
bciers/libs/components/src/form/widgets/readOnly/OperationRepresentativeWidget.test.tsx

[ISSUE 2933](https://github.com/bcgov/cas-registration/issues/2933)

Fix: 2933 cannot save operation rep

---

bc_obps/reporting/schema/report_operation.py
bciers/apps/reporting/src/data/jsonSchema/operations.tsx

Card: N/A
Chages: made bcghid as null or string

chore:fixed bcghid

---

bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/nonAttributableEmissionsFactoryItem.ts

Card: N/A
A small PR to fix gas types in final review page
It was showing this in final review page 
changed to

chore: fixed gas type in final review

---

bciers/apps/reporting/src/app/components/activities/uiSchemas/pulpAndPaperUiSchema.ts

Card: https://github.com/bcgov/cas-reporting/issues/402
Just changing the Description of the checkbox on pulp and paper activity

chore: update title for woody biomass emission methodology

---

bc_obps/service/tests/test_user_operator_service.py
bc_obps/service/user_operator_service.py

[ISSUE 2957](https://github.com/bcgov/cas-registration/issues/2957)

Feat: 2957 create contact when creating new operator

---

bc_obps/reporting/service/report_verification_service.py
bc_obps/reporting/tests/service/test_report_verification_service.py
bciers/apps/reporting/src/app/components/activities/uiSchemas/petroleumRefiningUiSchema.ts

Addresses: [615](https://github.com/bcgov/cas-reporting/issues/615)

chore: update needs verification to use emissions attributable for reporting threshold

---

bc_obps/reporting/migrations/0008_prod_data.py
bc_obps/reporting/tests/models/test_fuel_type.py

Card: https://github.com/bcgov/cas-reporting/issues/551
A very small PR to fix the fuel name typo

chore: fixed oil name

---

bc_obps/Makefile
bc_obps/bc_obps/settings.py
bc_obps/common/management/commands/create_empty_migrations.py
bc_obps/common/management/commands/custom_migrate.py
bc_obps/rls/apps.py
bc_obps/rls/tests/utils/test_manager.py
bc_obps/rls/utils/manager.py

[ISSUE 2939](https://github.com/bcgov/cas-registration/issues/2939)

Chore: 2939 prepare django commands for prod launch

---

bciers/apps/registration/app/data/jsonSchema/operationRegistration/operationInformationText.tsx
bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=101907329&issue=bcgov%7Ccas-registration%7C3016
This PR:
- adds link
- vitest

3016 glossary link

---

bc_obps/registration/api/_operations/operation_id.py
bc_obps/registration/schema/operation.py
bc_obps/registration/schema/operation_timeline.py
bc_obps/service/data_access_service/operation_service.py
bciers/apps/administration/app/components/datagrid/models/facilities/facilityColumns.ts
bciers/apps/administration/app/components/datagrid/models/facilities/facilityGroupColumns.ts
bciers/apps/administration/app/components/datagrid/models/operations/operationColumns.ts
bciers/apps/administration/app/components/datagrid/models/operations/operationGroupColumns.ts
bciers/apps/administration/tests/components/facilities/FacilitiesDataGrid.test.tsx
bciers/apps/administration/tests/components/operations/OperationDataGrid.test.tsx

[ISSUE 3010](https://github.com/bcgov/cas-registration/issues/3010)

Chore: 3010 modify status column for facility and operation tables

---

bciers/apps/registration/app/components/operations/registration/FacilityInformationForm.tsx
bciers/apps/registration/tests/components/operations/registration/FacilityInformationForm.test.tsx

card: https://github.com/bcgov/cas-registration/issues/2998
This PR:
- add conditions in the data manipulation function to not create any formData if the form is blank
- adds conditions in the handle submit to handle a blank form or no facilities
- vitests

2998 facility grid bugs

---

docs/devops/hotfix.md

Hotfix documentation pulled from our CIF app

docs: add documentation on the steps to apply a hotfix

---

bciers/apps/reporting/src/app/components/taskList/taskListPages/2_facilitiesInformation.ts

Card: https://github.com/bcgov/cas-reporting/issues/638
A very small PR to fix xontinue url

chore: fixed continue url

---

bciers/apps/reporting/src/app/components/taskList/taskListPages/1_operationInformation.ts
bciers/apps/reporting/src/app/components/taskList/taskListPages/2_facilitiesInformation.ts

chore: fixed tasklist

---

bciers/apps/registration/app/components/operations/registration/FacilityInformationForm.tsx
bciers/apps/registration/tests/components/operations/registration/FacilityInformationForm.test.tsx

card: https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration++-status%3Adone&pane=issue&itemId=102914917&issue=bcgov%7Ccas-registration%7C3058
This PR:
- fixes bug (the condition for if a the form is blank but there are existing facilities was wrong)
- regression test

3058 facility does not save

---

bc_obps/compliance/enums.py
bc_obps/compliance/models/rls_configs/elicensing_link.py
bc_obps/rls/tests/utils/test_manager.py
bc_obps/rls/utils/manager.py

https://www.loom.com/share/47df71a01e2c40d8a5414ee7b5652485?sid=52f24eb1-b363-4923-83f6-7dafec32ddad

chore: add grants for django_content_type table

---

bciers/apps/administration/app/components/contacts/ContactForm.tsx
bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx

[ISSUE 2610](https://github.com/bcgov/cas-registration/issues/2610)

Chore: 2610 Update inline message wording in ContactForm

---

bc_obps/reporting/schema/report_history.py
bc_obps/reporting/service/report_history_dashboard_service.py
bc_obps/reporting/tests/service/test_report_history_dashboard_service.py
bciers/apps/reporting/src/app/components/datagrid/models/reportHistory/reportHistoryColumns.tsx
bciers/apps/reporting/src/app/components/operations/cells/MoreActionsCell.tsx
bciers/apps/reporting/src/app/components/submitted/SubmittedForm.tsx
bciers/libs/components/src/navigation/Bread.tsx

Card: [#669](https://github.com/bcgov/cas-reporting/issues/669), [#661](https://github.com/bcgov/cas-reporting/issues/661)
Changes:-
- Fixed breadcumbs for report-history
- modified schema and report history service to display by date of submission in descending order
- fixed Format for the date of submission

chore: fix report history

---

bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx
bciers/apps/reporting/src/app/components/signOff/types.ts
bciers/apps/reporting/src/tests/components/signOff/SignOffForm.test.tsx

Card: [#673](https://github.com/bcgov/cas-reporting/issues/673)
A small PR to add signature check for enabling button

chore: added signature check for enabling button

---

bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsibleForm.tsx
bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsiblePage.tsx
bciers/apps/reporting/src/app/components/operations/personResponsible/createPersonResponsibleSchema.ts
bciers/apps/reporting/src/data/jsonSchema/personResponsible.ts
bciers/apps/reporting/src/data/jsonSchema/personResponsibleWidgets.tsx
bciers/libs/components/src/form/fields/FieldTemplateFullWidth.tsx
bciers/libs/components/src/form/fields/index.ts
bciers/libs/components/src/icons/ErrorCircle.tsx
bciers/libs/components/src/icons/index.ts

Addresses: 
[555](https://github.com/bcgov/cas-reporting/issues/555)
[594](https://github.com/bcgov/cas-reporting/issues/594)
- Displays message if person responsible is missing address information
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
2. Select an operation and open the report
3. Navigate to `/person-responsible`
4. Select a contact with complete address information
✅ 
- Missing address information message does not display
5. Select a contact with missing address information
✅ 
- …

chore: 555 display message when person responsible address is missing

---

bc_obps/reporting/service/report_submission_service.py

Card:  https://github.com/bcgov/cas-reporting/issues/659
A small to use the newly added pgtrigger(https://github.com/bcgov/cas-registration/pull/3101) for pgtrigger ignore

chore: added trigger ignore

---

bciers/apps/administration/app/components/facilities/FacilityPageBanner.tsx
bciers/apps/administration/tests/components/facilities/FacilityPageBanner.test.tsx

This PR is to reword the banner in #3005

Reword 3005 banner

---

bciers/apps/reporting/src/app/components/facility/FacilityReviewForm.tsx
bciers/apps/reporting/src/app/components/operations/OperationReviewForm.tsx
bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsibleForm.tsx
bciers/apps/reporting/src/app/components/operations/reviewFacilities/ReviewFacilitiesForm.tsx
bciers/apps/reporting/src/app/utils/getUpdatedFacilityReportDetails.ts
bciers/apps/reporting/src/app/utils/getUpdatedReportOperationDetails.ts

Card: https://github.com/bcgov/cas-reporting/issues/685
A PR to add Snack bar after the sync on the following Review Operation Information,Person Responsible,Review Facilities,Review Facility Information

chore: added confirmation after sync

---

bc_obps/common/tests/endpoints/auth/constants.py
bc_obps/reporting/api/__init__.py
bc_obps/reporting/api/reports.py
bc_obps/reporting/schema/report.py
bc_obps/reporting/tests/api/test_reports.py
bc_obps/service/report_service.py
bc_obps/service/report_version_service.py
bc_obps/service/tests/test_report_service.py
bciers/apps/reporting/src/app/components/facility/FacilityReviewPage.tsx
bciers/apps/reporting/src/app/components/operations/OperationDataGrid.tsx
bciers/apps/reporting/src/app/components/operations/cells/ActionCell.tsx
bciers/apps/reporting/src/app/components/operations/cells/MoreActionsCell.tsx
bciers/apps/reporting/src/app/utils/createReportVersion.ts
bciers/apps/reporting/src/app/utils/deleteReportVersion.ts

Addresses: 
[612](https://github.com/bcgov/cas-reporting/issues/612)
[670](https://github.com/bcgov/cas-reporting/issues/670)
- Added endpoint api `bc_obps/reporting/api/reports.py\delete_report_version`
- Updated `bc_obps/service/report_version_service.py\delete_report_version` to return boolean to endpoint api
- Added server action `deleteReportVersion` to call endpoint `delete-report-version`
- Added menu item `MoreActionsCell.tsx\Delete draft` to trigger call to `deleteReportVersion` server action
- Added menu item action context confirmation messaging for `Delete Draft`
- Added endpoint api  `bc_obps/reporting/api/reports.py\create_report_version` to create a new draft report version on an existing report
- Added server action `createReportVersion` to call endpoint …

chore: 612 delete report version

---

bc_obps/common/fixtures/dashboard/reporting/external.json
bc_obps/common/fixtures/dashboard/reporting/internal.json

Card: https://github.com/bcgov/cas-reporting/issues/672
A very small PR to update the tile content

updated tile content for reporting sub dashboard

---

bc_obps/Dockerfile
bc_obps/registration/management/commands/check_document_file_status.py
helm/cas-bciers/templates/cronJobs/check-file-status.yaml

Replaces cronjob-within-cronjobpod with a loop in the Python command.

chore: replace cron job with python loop for status checker

---

bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx
bciers/apps/reporting/src/app/components/products/ProductionDataForm.tsx
bciers/apps/reporting/src/app/components/products/ProductionDataPage.tsx
bciers/apps/reporting/src/tests/components/products/ProductionDataForm.test.tsx

- **fix: Emission allocation page allows saving without validation if methodology is not applicable**
- **chore: require products to be selected from non-small/medium facilities before proceeding**

422 - Post PO review edits

---

bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx

fix: allow resubmitting a report after validation errors

---

bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx
bciers/apps/registration/tests/components/operations/registration/NewEntrantOperationForm.test.tsx
bciers/libs/components/src/form/widgets/FileWidget.test.tsx
bciers/libs/components/src/form/widgets/FileWidget.tsx
bciers/libs/components/src/form/widgets/readOnly/ReadOnlyFileWidget.test.tsx

card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=105565307&issue=bcgov%7Ccas-registration%7C3172
This PR:
- updates the message in the FileWidget
- updates the tests

UX: Update file scanning message #3172

---

bciers/libs/components/src/layout/Header.tsx
bciers/libs/components/src/layout/HelpDrawer.test.tsx
bciers/libs/components/src/layout/HelpDrawer.tsx

- **feat: Create help drawer menu component with links in the nav header**
- **test: add test for helpdrawer component**

389 - help drawer

---

bc_obps/registration/api/user/user_app_role.py
bc_obps/registration/api/user/user_is_archived.py
bc_obps/registration/api/user/user_profile.py
bc_obps/service/data_access_service/user_service.py
bciers/apps/administration/app/components/profile/ProfilePage.tsx
bciers/libs/actions/src/actions.ts
bciers/libs/utils/src/getUUIDFromEndpoint.test.ts
bciers/libs/utils/src/getUUIDFromEndpoint.ts

[ISSUE 3325](https://github.com/bcgov/cas-registration/issues/3325)

[Sentry] 3325 fix nonetype error for new users

---

bciers/apps/reporting/src/data/jsonSchema/signOff/signOff.ts

Card: N/A
Fixed EIO sign off statement 
from 
**_I certify that the amount of total emissions reported, and all other information included in this report, is complete and accurate._**
to 
**_I have reviewed this report and certify that the amount of total emissions reported, and all other information included in this report, is complete and accurate._**

chore: fixed eio sign off statement

---

bc_obps/common/exceptions.py
bc_obps/compliance/service/compliance_obligation_service.py
bc_obps/compliance/tests/service/test_compliance_obligation_service.py
bc_obps/registration/api/_operations/_operation_id/_registration/submission.py
bc_obps/service/application_access_service.py
bc_obps/service/contact_service.py
bc_obps/service/data_access_service/operator_service.py
bc_obps/service/error_service/handle_exception.py
bc_obps/service/facility_service.py
bc_obps/service/operation_service.py
bc_obps/service/operator_service.py
bc_obps/service/report_service.py
bc_obps/service/tests/test_application_access_service.py
bc_obps/service/tests/test_handle_exception.py
bc_obps/service/transfer_event_service.py
bc_obps/service/user_service.py

[ISSUE 3326](https://github.com/bcgov/cas-registration/issues/3326)
**NOTE:**
- Introduced a new error type to handle user-facing errors, making them distinguishable from other error types.
- Refactored the existing `exception_handler` function and added test coverage for it.

[Sentry] 3326 not logging user errors in sentry

---

bciers/apps/reporting/src/app/components/operations/OperationsPage.tsx

Card: https://github.com/bcgov/cas-reporting/issues/784

chore: fixed date in reports table page

---

bciers/libs/components/src/auth/SessionTimeoutHandler.test.tsx
bciers/libs/components/src/auth/SessionTimeoutHandler.tsx

#3268 
This PR:
- manually redirects users to the logout page/fallback page after they've been signed out (signout's redirectTo doesn't work with our versions of nextauth/next-js per https://github.com/nextauthjs/next-auth/issues/10944)
- updates vitests
- sonar fail is duplication in tests, not an actual problem

3268 2 logout redirect

---

bciers/apps/reporting/src/app/components/operations/OperationReviewForm.tsx
bciers/apps/reporting/src/tests/components/operations/OperationReviewForm.test.tsx
bciers/libs/components/src/form/NavigationForm.tsx
bciers/libs/components/src/form/components/ReportingStepButtons.test.tsx
bciers/libs/components/src/form/components/ReportingStepButtons.tsx

Card: https://github.com/bcgov/cas-reporting/issues/671
Changes: 
1. Added prop backButtonText
2. Passed this from Operation Review Information form
3. Added tests

chore: fixed back button text

---

bc_obps/common/tests/endpoints/auth/constants.py
bc_obps/compliance/api/__init__.py
bc_obps/compliance/api/payments.py
bc_obps/compliance/schema/payments.py
bc_obps/compliance/service/compliance_dashboard_service.py
bc_obps/compliance/service/elicensing/elicensing_api_client.py
bc_obps/compliance/tests/service/test_compliance_dashboard_service.py
bciers/apps/compliance/src/app/bceidbusiness/industry_user_admin/compliance-summaries/page.tsx
bciers/apps/compliance/src/app/bceidbusiness/industry_user_admin/payment-summaries/page.tsx
bciers/apps/compliance/src/app/components/compliance-summaries/ComplianceSummariesPage.tsx
bciers/apps/compliance/src/app/components/datagrid/models/payment-summaries/paymentSummaryColumns.tsx
bciers/apps/compliance/src/app/components/datagrid/models/payment-summaries/paymentSummaryGroupColumns.tsx
bciers/apps/compliance/src/app/components/payment-summaries/PaymentSummariesDataGrid.tsx
bciers/apps/compliance/src/app/components/payment-summaries/PaymentSummariesPage.tsx
bciers/apps/compliance/src/app/types.ts
bciers/apps/compliance/src/app/utils/getPaymentSummariesPageData.ts

[Issue 20](https://github.com/bcgov/cas-compliance/issues/20) 
Testing steps:
- Go to reporting & submit the report for the "Compliance SFO - Obligation not met" operation
- Follow the steps @fviduya has laid out on creating payments & create at least one payment for the newly created fee/invoice
- Go to compliance and navigate to the payment-summaries page
- The payments should appear in the table as below:

feat: 20 - Payment summary page

---

bc_obps/registration/fixtures/mock/operation_designated_operator_timeline.json

Addresses: 
[203](https://github.com/bcgov/cas-compliance/issues/203)
- Created fixtures for operation timeline for compliance reporting: 
- Compliance SFO - Obligation not met
- Compliance SFO - Earned credits
- Compliance SFO - Obligation fully met
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
1.  Navigate to http://localhost:3000/administration/operations
✅  
- Grid displays records including:
- Compliance SFO - Obligation not met
- Compliance SFO - Earned credits
- Compliance SFO - Obligation fully met
1.  Navigate to …

chore: update operation timeline fixtures for compliance

---

helm/cas-bciers/templates/administration/deployment.yaml
helm/cas-bciers/templates/backend/deployment.yaml
helm/cas-bciers/templates/compliance/deployment.yaml
helm/cas-bciers/templates/registration/deployment.yaml
helm/cas-bciers/templates/reporting/deployment.yaml

Card: N/A
A small PR to fix the log file name

chore: fix logname

---

helm/cas-bciers/templates/administration/deployment.yaml

Card: N/A
A small PR to update logname and app Name for Administration

chore: update administration logs

---

docs/backend/api-design.md

card: https://github.com/bcgov/cas-registration/issues/2691

docs: add how-to for atomic transactions to the API docs

---

bciers/apps/reporting/src/app/components/operations/reviewFacilities/ReviewFacilitiesForm.tsx

Card: https://github.com/bcgov/cas-reporting/issues/835
Fixes typo: "faclities" --> "facilities"

fix: corrected typo in ReviewFacilitiesForm.tsx

---

docs/devops/release.md
docs/team_release_process.md

No card. Since it was my first time releasing, I added some info to the docs in the places where I got confused or things had changed.

docs: update release docs

---

bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.tsx
bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsSuccessAlertNote.tsx
bciers/apps/compliance/src/app/data/jsonSchema/manageObligation/applyComplianceUnitsSchema.tsx
bciers/apps/compliance/src/app/types.ts
bciers/apps/compliance/src/app/widgets/ApplyComplianceUnitsWidget.tsx
bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.test.tsx
bciers/apps/compliance/src/tests/components/widgets/ApplyComplianceUnitsWidget.test.tsx
bciers/apps/compliance/src/tests/components/widgets/BccrHoldingAccountWidget.test.tsx

**[ISSUE 209](https://github.com/bcgov/cas-compliance/issues/209)**
Implement UI enhancements for the **"Apply Compliance Units"** workflow to align with backend capabilities introduced in (https://github.com/bcgov/cas-compliance/issues/147) and (https://github.com/bcgov/cas-compliance/issues/168). These updates ensure dynamic rendering of compliance data and improve form validation and user confirmation mechanisms, as per the [[Figma wireframe](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=41078-8187&t=NLUiL4xapbBeUW0Z-4)](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=41078-8187&t=NLUiL4xapbBeUW0Z-4).
- **`ApplyComplianceUnitsComponent`**:
- Dynamically renders BCCR Trading Name and checkbox confirmation when account details are …

chore: 209 apply compliance units changes

---

bc_obps/compliance/service/supplementary_version_service.py
bc_obps/compliance/tests/service/test_supplementary_version_service.py

card: https://github.com/bcgov/cas-compliance/issues/246
This PR:
- uncomments the increased credits handler
- implements the handler
- pytests
- manual testing instructions in the card

246 handle increased earned credits

---

docs/devops/release.md

docs: add note about check-migrations check

---

bciers/apps/reporting/src/app/components/reportInformation/facilities/FacilitiesPage.tsx
bciers/apps/reporting/src/app/components/taskList/taskListPages/2_facilitiesInformation.ts

Card: https://github.com/bcgov/cas-reporting/issues/859
Changes:- 
1. added check for facilities in facilities page
2. Added check for facilityId in Facilities Information

chore: added fix for facilities table page

---

bc_obps/reporting/service/report_supplementary_version_service.py
bc_obps/reporting/tests/service/test_report_supplementary_version_service.py

Refactored some tests to mirror database structure a bit better

fix: selected activities without emissions reports get deselected when creating a supplementary report

---

bciers/apps/compliance/src/middleware.ts

no card, to fix downloads no longer working

fix: put api back into the middleware matcher

---

bc_obps/compliance/service/automated_process_service.py
bc_obps/compliance/tasks.py
bc_obps/compliance/tests/service/test_automated_process_service.py

[ISSUE 215](https://github.com/bcgov/cas-compliance/issues/215)

feat: refresh all obligation invoices daily

---

bc_obps/compliance/service/compliance_report_version_service.py
bc_obps/compliance/service/supplementary_version_service.py
bc_obps/compliance/tests/service/test_compliance_report_version_service.py

[ISSUE 252](https://github.com/bcgov/cas-compliance/issues/252)

252 fix outstanding balance decimal digits

---

bc_obps/compliance/service/compliance_dashboard_service.py
bc_obps/compliance/tests/service/test_compliance_dashboard_service.py

Addresses:
[243](https://github.com/bcgov/cas-compliance/issues/243)
[244](https://github.com/bcgov/cas-compliance/issues/244)

chore: 243 filter compliance dashboard by current report year

---

bc_obps/common/migrations/0076_notice_of_earned_credits_generated_notification_email_template.py

follow up to https://github.com/bcgov/cas-compliance/issues/318 to fix a typo in the template

chore: fix typo

---

bc_obps/common/fixtures/dashboard/compliance/internal.json
bc_obps/common/migrations/0079_update_internal_dashboard_data.py

Addresses: 
[175](https://github.com/bcgov/cas-compliance/issues/175) update -  see [conversation](https://github.com/bcgov/cas-compliance/issues/175#issuecomment-3267947443)
- Updates internal compliance dashboard tile
---
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
1. Navigate to [http://localhost:3000](http://localhost:3000)  
2. Click the **"Log in with IDIR"** button
3. Navigate to compliance http://localhost:3000/compliance
**Expected results:**  
- Tiles reflect design

chore: update internal dashboard

---

bc_obps/common/tests/endpoints/auth/constants.py
bc_obps/registration/api/contacts.py
bc_obps/service/contact_service.py
bc_obps/service/data_access_service/contact_service.py
bc_obps/service/tests/data_access_service/test_data_access_contact_service.py
bciers/apps/administration/app/components/profile/ProfileForm.tsx
bciers/apps/administration/app/components/profile/ProfilePage.tsx
bciers/apps/administration/tests/components/profile/ProfileForm.test.tsx
bciers/apps/dashboard/middlewares/withAuthorizationDashboard.test.ts
bciers/libs/testConfig/src/data/tokens.ts

Help text on User Profile page

---

bc_obps/reporting/service/report_review_changes_service.py
bciers/apps/reporting/src/app/components/changeReview/ChangeReviewForm.tsx
bciers/apps/reporting/src/app/components/changeReview/ChangeReviewPage.tsx
bciers/apps/reporting/src/app/components/changeReview/constants/types.ts
bciers/apps/reporting/src/app/components/changeReview/templates/ReviewChanges.tsx
bciers/apps/reporting/src/app/components/taskList/reportingFlows.ts
bciers/apps/reporting/src/tests/components/changeReview/ChangeReviewForm.test.tsx
bciers/apps/reporting/src/tests/components/changeReview/ChangeReviewPage.test.tsx
bciers/apps/reporting/src/tests/components/changeReview/ReviewChanges.test.tsx

PR to fix issues being caused in test

chore: fixed review changes errors

---

helm/cas-bciers/templates/backend/check-file-status-deployment.yaml

A small PR to fix check document file status appname

chore: fixed check document app name

---

bc_obps/compliance/emails.py
bc_obps/compliance/service/compliance_report_version_service.py
bc_obps/compliance/service/earned_credits_service.py
bc_obps/compliance/tests/service/test_compliance_earned_credits_service.py
bc_obps/compliance/tests/test_emails.py

[ISSUE 353](https://github.com/bcgov/cas-compliance/issues/353)

chore: prevent email notifications for earned credits under threshold

---

bciers/apps/reporting/src/app/idir/cas_admin/reports/[version_id]/annual-report/facility/[facility_id]/page.tsx
bciers/apps/reporting/src/app/idir/cas_admin/reports/[version_id]/annual-report/page.tsx

Card: N/A
A small PR to add annual reports view for cas-admin

chore: fixed cas-admin internal user view
