bcgov/cas-registration

.github/workflows/test.yaml
Updated the "needs" list for `backend-tests` job to match the needs for `e2e` job in workflows/test.yaml
=> Chore: Updated list of needs for backend-tests action

client/app/components/form/MultiStepHeader.tsx, client/app/components/form/widgets/FileWidget.tsx, client/app/components/theme/theme.ts, client/app/styles/colors.ts, client/app/styles/globals.css, client/app/styles/rjsf/GroupTitleFieldTemplate.tsx, client/app/utils/jsonSchema/userOperator.ts, client/tailwind.config.js, docs/css-theme-guide.md, docs/developer-guide.md
A a lot of this was already completed in previous PRs and without a proper design system implemented there wasn't too much to do for this ticket, though it's something we've flagged with the designers.
I've tried to simplify the colour names to be a little bit less verbose as the old ones made for some long tailwind classes. Let me know if you have other naming suggestions though I think we should keep them fairly short.
I've also setup documentation linking to our global css file, Tailwind config and Mui theme.
=> 232 update css theme

client/app/(onboarding)/home/page.tsx, client/app/components/layout/Header.tsx, client/app/components/theme/theme.ts
Fix for the homepage header colour. This was caused by the MUI theme update PR. I also added a small change to typography so by default it will use the text colour from the bc gov design system.
=> fix: header colour regression from mui theme update

client/app/components/form/widgets/ComboBox.tsx, client/app/components/form/widgets/SelectWidget.tsx, client/app/components/form/widgets/TextWidget.tsx, client/app/components/theme/theme.ts, client/app/styles/globals.css, docs/rjsf-forms.md
In this I refactored and moved some of the shared widget styles to the MUI theme that didn't need to be reactive before I figured out that we might not need a specific `NumberWidget`. Setting the `type` as I have in the `URLWidget` for example doesn't actually get passed in RJSF to the widget, even if I extend the widget props.  As such will be getting rid of that and `EmailWidget` in #316 using the `format` option.
Now in a fields schema if  `type: 'number'` is set then the `TextWidget` will be set to `type="number"`, the input won't accept letters and the value is saved as a number in the form data.  I looked into it and we can limit the decimal places in the future easily if needed.
The arrow increment buttons are disabled globally for number inputs via CSS in the `globals.css` file. …
=> 173 number widget

client/app/components/form/widgets/MultiSelectWidget.tsx, client/app/components/form/widgets/index.ts, client/app/components/routes/operations/form/Operation.tsx, client/app/utils/jsonSchema/operations.ts, docs/rjsf-forms.md
Implements #318 
This one took a lot of experimentation to do and not trigger RJSF validation issues. I initially tried to do it using `anyOf` as we use for many select fields using the `ComboBox` widget though storing the values as an array triggered a lot of validation errors. Rather than removing those errors on the front end I wanted to use a way that was supported by RJSF.
I ended up using `enum` as these fields initially were so the values are saved the same as before this PR as an array of the selected `enum` values. I ended up using `enumNames` to set custom labels for each selection though that might be depreciated eventually. Open to other suggestions if you have any other ideas.
While there was talk of just adding onto the functionality of `ComboBox` I decided to make …
=> 318 multiselect widget

bc_obps/registration/api/user.py, bc_obps/registration/schema/user.py, bc_obps/registration/tests/test_endpoints.py, client/app/(authenticated)/dashboard/profile/page.tsx, client/app/api/auth/[...nextauth]/route.ts, client/app/api/auth/token/route.ts, client/app/components/form/SubmitButton.tsx, client/app/components/form/formDataTypes.ts, client/app/components/loading/SkeletonSpinner.tsx, client/app/components/navigation/Profile.tsx, client/app/components/routes/profile/User.tsx, client/app/components/routes/profile/form/UserForm.tsx, client/app/loading.tsx, client/app/utils/actions.ts, client/app/utils/jsonSchema/user.ts, client/e2e/.env.local.example, client/e2e/auth/auth-setup.ts, client/e2e/auth/authentication.spec.ts, client/middlewares/withAuthorization.tsx
Addresses [283](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/283) 
- Modify client/app/api/auth/[...nextauth]/route.ts
- Modify client/middlewares/withAuthorization.tsx
- Add client/app/api/auth/token/route.ts
- Modify client/app/utils/actions.ts 
- Modify client/app/(authenticated)/dashboard/profile/page.tsx
- Add client/app/components/routes/profile/*
- Add client/app/utils/jsonSchema/user.ts
- Modify client/app/components/form/formDataTypes.ts
- Modify client/app/components/navigation/Profile.tsx
- Modify client/app/components/form/SubmitButton.tsx
- Add client/app/components/loading/SkeletonSpinner.tsx
- Modify client/app/loading.tsx
- Add UserProfileOut to bc_obps/registration/schema.py
- Add GET endpoint for user …
=> feat: New User Form & Endpoints

bc_obps/registration/api/operator.py, bc_obps/registration/api/user_operator.py, bc_obps/registration/schema/user_operator.py, bc_obps/registration/tests/test_02_endpoints.py, client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/users/page.tsx, client/app/components/datagrid/ChangeUserOperatorStatusColumnCell.tsx, client/app/components/datagrid/DataGrid.tsx, client/app/components/datagrid/userPageHelpers.tsx, client/app/types/types.ts, client/app/utils/actions.ts, client/app/utils/users/adminUserOperators.ts
Addresses [#28](https://app.zenhub.com/workspaces/team-moose-sprint-board-60d216175a2689000ec774d0/issues/gh/bcgov/cas-registration/28). Adds backend API and frontend interface for an Organization Admin to view, approve/deny user access requests.
- Add GET endpoint to retrieve all user access request statuses for a particular Operator `/operators/{operator_id}/user-operators`.
- Add GET endpoint to retrieve all of a user's associated Operators `/get-users-operators/{user_id}`.
- Add PUT endpoint to change access request status of a UserOperator `/select-operator/user-operator/{user_id}/update-status`.
- Add page for `/dashboard/users` for External Admin.
- Lists all users for External Admin's Operators and their access request statuses.
- Ability to Approve/Deny/Undo (set to pending) user …
=> feat: View and manage user access requests as an Op/Org admin

client/app/components/form/FormBase.tsx, client/app/styles/rjsf/InlineFieldTemplate.tsx, client/app/utils/jsonSchema/operations.ts, client/app/utils/jsonSchema/userOperator.ts, docs/rjsf-forms.md
Implements #316 
We were going to use a custom validator for URLs since the RJSF `uri` format is strict and requires `https://` though Nan said that's okay for now and to just updated the error messaging.
=> 316 rjsf url email validation

client/app/components/form/OperationsForm.tsx, client/app/components/navigation/Bread.tsx, client/app/components/routes/operations/Page.tsx, client/app/components/routes/operations/form/Operation.tsx, client/app/components/routes/operations/form/OperationReview.tsx
Small PR to fix using `0` as the query param value for creating a new operation form back to `create`. 
Shon and I decided to fix this as part of the breadcrumb work.
=> refactor: change new operation '0' param to 'create'

client/app/components/form/widgets/CheckboxWidget.tsx, client/app/components/form/widgets/index.ts, client/app/utils/jsonSchema/userOperator.ts, docs/rjsf-forms.md
Implements #419 
Created a MUI checkbox widget so the styling would match the rest of our widgets. `label: false` now just hides the label in the `InlineFieldTemplate` instead of both the widget and the template.
=> 419 senior officer checkbox has no text

client/app/components/routes/profile/User.tsx, client/app/types/types.ts
Fix for #422 
This seems like something that should be unified in SSO app though I imagine they'd risk breaking a bunch of projects if they changed it. IDIR user names come in the format `lastname, firstname` instead of `firstname lastname` like `BCeiD` users so I added some logic to fix it.
=> fix: idir names entered into the db incorrectly

client/app/components/form/MultiStepButtons.tsx
#475 
Steps to reproduce the behaviour:
Log in as `CAS` admin or analyst
Go to Operations form
The form should be read only
The `Next` button will be disabled which blocks the user from reviewing the form
=> fix: multistep form disabled next button

client/app/components/form/MultiStepButtons.tsx, client/app/components/form/MultiStepFormBase.tsx, client/app/components/form/OperationsForm.tsx, client/app/components/form/UserOperatorMultiStepForm.tsx
https://github.com/bcgov/cas-registration/issues/490
I manually tested submitting and viewing all the forms (except this currently broken one: https://github.com/bcgov/cas-registration/issues/491) since changing the multistep component affects a lot of the app.
Backend tests are failing because it's 2024 now. They're fixed in https://github.com/bcgov/cas-registration/pull/489 (and possibly other PRs) that will be merged in before this one, so they'll start passing once I rebase.
=> fix: all user roles can navigate the multistep forms

helm/cas-registration/templates/backend/deployment.yaml, helm/cas-registration/values.yaml
This will roll back all the migrations before the backend pod is run. This way any changes to the migrations made during development will be deployed properly.
=> Chore: 517 roll back dev migrations

client/app/components/form/FormBase.tsx, client/app/components/form/MultiStepFormBase.tsx, client/app/components/form/OperationsForm.tsx, client/app/components/form/UserOperatorContactForm.tsx, client/app/components/form/UserOperatorMultiStepForm.tsx
Fixes #528 
More explanation and steps to reproduce the bug/check that it's fixed in the issue. I couldn't find anything in RJSF form props that looked like it would handle this: 
https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/
The easy fix is handling form state externally though let me know if you have other ideas!
=> fix: handle form state externally to prevent data loss on error

client/app/components/form/FormBase.tsx
Fix for performance issues caused by handling form state externally `onChange`. Now setting the form state on form submission.
=> fix: set external form state on submit

bc_obps/registration/api/operation.py, bc_obps/registration/schema/operation.py, bc_obps/registration/tests/endpoints/test_operations_endpoints.py, bc_obps/registration/tests/utils/helpers.py, client/app/components/form/OperationsForm.tsx, client/app/components/routes/operations/form/Operation.tsx, client/app/components/routes/operations/types.ts, client/app/utils/jsonSchema/operations.ts
Implements #510 
We were designing this as I was doing it so take a close look and let me know if I missed or misunderstood something 🙇
=> 510: is_application_lead_external 'no' error

client/app/api/auth/[...nextauth]/route.ts, client/app/components/navigation/Session.tsx, client/app/components/routes/profile/User.tsx, client/app/components/routes/select-operator/Page.tsx, client/app/types/next-auth.d.ts, client/app/utils/getUserFullName.ts
Fixes the issue where ministry codes were being added to the user data by parsing the given_name and family_name attributes from the jwt and using those for IDIR users.
I still had to use the .name attribute in some places for the bceid users as it appears that both the given_name and family_name end up in the given_name attribute of the jwt for these users.
=> Fix: 447 save correct user names

client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/users/page.tsx, client/app/(authenticated)/idir/cas_admin/dashboard/operators/page.tsx, client/app/(authenticated)/idir/cas_analyst/dashboard/operators/page.tsx, client/app/components/datagrid/DataGrid.tsx, client/app/components/datagrid/Note.tsx, client/app/components/datagrid/helpers.tsx, client/app/components/routes/access-requests/AccessRequests.tsx, client/app/components/routes/operations/Operations.tsx
Implements #469 
Acceptance criteria 1: I wrote a comment in the issue explaining that after a discussion it was decided to leave the `Request ID` column in for now and perhaps revisit post MVP.
Acceptance criteria 2: Admittedly I went far past the scope of this as it just said to add the status pill if it was easy. I started to make some improvements and got a bit carried away though I think it was worth spending a few hours on and looks very close to what is in the Figma designs. The `Datagrid` is now styled so the work will carry over to the `Operations` table style update.
The `Operations` table looks slightly weird due to this update, the `Action` column is still oversized though looks a bit off since the content is centered like the design. I'm working on the Operations table issue …
=> 469 make operator table match wireframe

client/app/components/form/MultiStepButtons.tsx, client/app/components/form/MultiStepFormBase.tsx, client/app/components/form/OperationsForm.tsx, client/app/components/form/SubmitButton.tsx, client/app/components/form/UserOperatorContactForm.tsx, client/app/components/form/UserOperatorMultiStepForm.tsx
Implements #556
This disabled the form buttons on submit in forms that use the `MultistepFormBase` as well as the single `UserOperatorContactForm`.
If there is an error during form submission we reenable the submit buttons.
=> 556 disable form buttons on submit

client/app/components/navigation/Profile.tsx
WIP:
**Issue:** https://cas-reg-frontend-dev.apps.silver.devops.gov.bc.ca/ Log Out flow returns to `/home` instead of  the expected `xx/openid-connect/logout` page and SiteMinder-Keycloak logout is not completed (as seen in cookie values)
**Troubleshooting**
Locally, the SiteMinder-Keycloak logout page is displayed and  **seems** to initiate a complete SiteMinder-Keycloak logout (as seen in cookie values) allowing for multiple user login-logout-login.
Perhaps, the DEV server's redirect callback after SignOut overrides the navigation to the SiteMinder-Keycloak logout page.
**Possible Resolution**
Prevent any SignOut app callback redirect: `  await signOut({ redirect: false });`
=> fix: prevent redirect on signout

client/app/api/auth/[...nextauth]/route.ts, client/app/components/navigation/Profile.tsx
WIP:
**Issue:** https://cas-reg-frontend-dev.apps.silver.devops.gov.bc.ca/ Log Out flow stays on same page instead of  the expected `xx/openid-connect/logout` page and SiteMinder-Keycloak logout is not completed (as seen in cookie values)
**Troubleshooting**
Potentially, the open function fails to set the location href  because it is being prevented by security ensuring the window is in  "active interaction" state (activating or focusing a browser window in response to a user gesture).
**Possible Resolution**
Remove dependency on window.open and leverage nextauth signOut function's callbackUrl parameter in combination with customising nextauth route.ts redirect function to allow callbacks to the identity server.
=> fix: allow custom redirect

helm/cas-registration/templates/frontend/deployment.yaml, helm/cas-registration/values.yaml
Increases the backend deployment memory limits to allow for the newly implemented gunicorn workers to initialize
Updates the LOGOUT env vars to include the open-id protocol, this was missing & causing issues with our logout workflow.
=> Chore: update deployment yaml files

client/app/components/navigation/Profile.tsx
signout() call needs to be awaited, otherwise it redirects too fast & doesn't sign out
=> chore: await signout() on logout button click

bc_obps/registration/schema/multiple_operator.py, bc_obps/registration/schema/operation.py, bc_obps/registration/schema/user_operator.py
Some fields were made to be nullable in #616, these fields need a `None` default set in their OUT schemas so that requests for this information do not error out when that nullable data is null.
=> chore: update OUT schemas to allow for newly nullable fields

client/app/components/form/MultiStepFormBase.tsx, client/app/components/form/MultiStepHeader.tsx, client/app/components/form/OperationsForm.tsx, client/app/components/form/defaultTheme.ts, client/app/components/form/titles/operationsTitles.tsx, client/app/styles/rjsf/FieldTemplate.tsx, client/app/styles/rjsf/InlineFieldTemplate.tsx, client/app/styles/rjsf/TitleFieldTemplate.tsx, client/app/styles/rjsf/TitleOnlyFieldTemplate.tsx, client/app/utils/jsonSchema/operations.ts, client/app/utils/jsonSchema/userOperator.ts
Implements #604 
Also fixes missing form headers on both Operations and User Operator forms
Took me awhile to think of a good way to have different titles in the `MultiStepHeader` than what is in the form header (Statutory Declaration instead of the full `Statutory Declaration and Disclaimer`. I have added a `customHeaderTitles` option to the `MultiStepFormBase` that takes an array of strings and uses that for the titles instead of pulling from the form schema. 
I added a custom `jsxTitle` for the upload field itself since the design has bold text over a link to a download for the template. It's mostly commented out until we are given a link to the template download for the `statutory_declaration` field though it's styled and should be ready to go. I've created a follow up ticket as a …
=> 604 add doc upload page

bc_obps/Dockerfile
Since switching to gunicorn, no logs have been appearing in the openshift stdout logging. This flag should fix that
=> chore: show access logs in stdout

helm/cas-registration/templates/backend/deployment.yaml, helm/cas-registration/templates/backend/route.yaml, helm/cas-registration/templates/frontend/deployment.yaml, helm/cas-registration/values-dev.yaml, helm/cas-registration/values-prod.yaml, helm/cas-registration/values-test.yaml, helm/cas-registration/values.yaml
Directs the frontend to hit the backend service which is only accessible from within the cluster instead of a route.
No backend route is created in test/prod.
A route is still created in the develop environment in case we want to explore anything in django admin & to allow our dev data setup job to complete.
=> chore: backend is only available from within the cluster

client/app/components/datagrid/DataGrid.tsx
Fix for #765 
Follow up tech debt issue to support server side pagination: #782 
Show the footer again and enable pagination even if it's not in the design:
Re-enables pagination and sets page size to 20 as discussed at standup. If you want to actually test the pagination you will have to somehow get over 20 records (Operators or Operations) in the database. I just ran my load testing PR for a few mins which created hundreds.
=> fix: re-enable pagination on mui datagrid

bc_obps/registration/api/operation.py, bc_obps/registration/schema/operation.py, bc_obps/registration/tests/endpoints/test_operations_endpoints.py, bc_obps/registration/tests/utils/helpers.py, client/app/components/form/OperationsForm.tsx
Card: [706](https://github.com/bcgov/cas-registration/issues/706)
Original purpose of card was to ensure that operations that are already Approved don't have their status reset to "Pending" when an edit is made (PUT request sent for the operation). This PR addresses that and some other issues:
- deletes/comments out Operation fields that are no longer required for MVP (such as multiple_operators, reporting_activities, addresses, etc.)
- fixes logic on the PUT endpoint for operations. We weren't saving some of the fields being sent to the backend correctly. There's still room for improvement on this IMO - it gets ugly because part of the payload being sent via the PUT request is actually default values from the frontend, which is why I introduced the `form_section` param on the endpoint so …
=> Task/edit operation wo status reset/706

client/app/components/form/formDataTypes.ts, client/app/components/routes/profile/User.tsx, client/app/components/routes/profile/form/UserForm.tsx
Fix for #550 
This was caused since an empty string still counts as a string in JSON Schema. I have created a `UserProfilePartialFormData` type to be used when we won't have all of the user profile form data and kept the original `UserProfileFormData` type for when it all needs to be there.
=> fix: user profile empty string values not triggering form validation

bc_obps/registration/api/user_operator.py, bc_obps/registration/middleware/current_user_middleware.py
Reducing the timout on the cache to 5 minutes. This way we're still not sending a request to the database on every request (there will be a request every 5 minutes for the user) but we also don't have to wait 1 hour for manual changes to apply when assigning internal permissions. We can revisit the timeout and increase it after we have implemented the user management workflow for internal users.
=> chore: reduce user cache timeout to 5 mins

bc_obps/registration/api/user_operator.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py
https://github.com/bcgov/cas-registration/issues/591
To test this, you need an approved user_operator with an 'Draft' operator that you'll change to an 'approved' operator to see the tile show up. I tested with bc-cas-dev-three, requested access, approved the request with psql, and then used the form to edit the operator data.
=> chore: editing operator sets status to pending

bc_obps/registration/api/operation.py, bc_obps/registration/api/user_operator.py, bc_obps/registration/constants.py, bc_obps/registration/fixtures/mock/operation.json, bc_obps/registration/fixtures/mock/user.json, bc_obps/registration/fixtures/mock/userOperator.json, bc_obps/registration/schema/operation.py, bc_obps/registration/schema/user_operator.py, bc_obps/registration/tests/endpoints/test_operations_endpoints.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/users/page.tsx, client/app/(authenticated)/idir/cas_admin/dashboard/operators/page.tsx, client/app/(authenticated)/idir/cas_analyst/dashboard/operators/page.tsx, client/app/components/datagrid/DataGrid.tsx, client/app/components/datagrid/OperationDataGrid.tsx, client/app/components/datagrid/OperatorDataGrid.tsx, client/app/components/datagrid/Pagination.tsx, client/app/components/routes/access-requests/AccessRequests.tsx, client/app/components/routes/access-requests/types.ts, client/app/components/routes/operations/Operations.tsx, client/app/components/routes/operators/OperatorsPage.tsx
Implements #782 
This enables serverside pagination for both Operator and Operations dashboards and works with sorting.
One thing that I could use a second set of eyes on is the updates to the `/operations` `GET` route have increased the amount of queries from 3 to 4 (Viewing through django-silk backend at `http://localhost:8000/silk/requests/`). Would be nice if we could get that back down to 3 though I am unsure of what the cause is.
Also found an example to add a numbered pagination component to the bottom of the datagrid. I found while testing that it was poor ux to make the user go through every page to get to later pages:
=> 782 mui datagrid serverside pagination

bc_obps/bc_obps/settings.py
Issue: #914 
**Manual testing**
I updated my local `bc_obps/.env` file with: `DB_PASSWORD=D)b7?m{hkukhklh*nk,8798}` and inserted a temporary print statement in `bc_obps/settings.py` to print out the parsed value of `default_db_url`, which output `postgres://awilliam:D%29b7%3Fm%7Bhkukhklh%2Ank%2C8798%7D@localhost:5432/registration`
=> Fix: URL encode DB_PASSWORD in database conn string

client/app/components/form/widgets/URLWidget.tsx
Fix for #887 
Steps to recreate this bug:
- Log in as `bc-cas-dev`
- Go to operator form
- Edit the `website` field and remove the URL all together and save
- Click edit again and try to save
- The URL validation triggers because django is returning empty string
To solve this I have added a useEffect which will convert an empty value to undefined so validation won't erroneously trigger.
=> fix: empty string causing url widget validation to trigger

bc_obps/registration/api/user_operator.py, bc_obps/registration/fixtures/mock/operator.json, bc_obps/registration/fixtures/mock/userOperator.json, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, client/app/components/datagrid/OperatorDataGrid.tsx, client/app/components/routes/operators/OperatorsPage.tsx
#866
I've also updated the fixtures so that we have multiple prime admin requests tied to different operators so the dashboard won't be empty once one is approved.
To test this you can sign in as `cas_admin` and approve the prime admin request of an operator. Once you return to the dashboard you should see no prime admin requests that are tied to that same operator.
=> 866 internal access requests view

bc_obps/registration/api/operator.py, bc_obps/registration/api/user_operator.py, bc_obps/registration/schema/operator.py, bc_obps/registration/schema/user_operator.py, bc_obps/registration/tests/endpoints/test_operator_endpoints.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, bc_obps/registration/tests/utils/bakers.py, bc_obps/registration/utils.py, client/app/components/form/formDataTypes.ts, client/app/components/routes/access-requests/form/UserOperatorReview.tsx, client/app/components/routes/select-operator/form/UserOperator.tsx
https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=48609943
To manually test this:
- login with your IDIR and go to the operators tile
- decline New Operator 3 Legal Name
- check in the db that New Operator 3 Legal Name and its user_operator have both been declined
PS: sonarcloud fails are all in test files so I'll dismiss them unless the reviewer has concerns
PPS: the approve operator workflow isn't working well atm, there's already a ticket: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=52823560
=> 474 rejection

client/app/(onboarding)/home/page.tsx, client/app/data/home/events.json
#668 - accidentally numbered this branch #163 which this is a follow up issue for.
There is a comment in #668 that says the exemption URL won't be ready for MVP so I've commented out that section. Also reduced the font size and padding in the `Key dates` section as that has been changed in Figma.
=> Add missing URLs to landing page and update key dates

bc_obps/registration/api/operation.py, bc_obps/registration/api/user_operator.py, bc_obps/registration/middleware/current_user_middleware.py, bc_obps/registration/schema/user_operator.py, bc_obps/registration/tests/endpoints/test_operations_endpoints.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, bc_obps/registration/utils.py, client/app/(authenticated)/bceidbusiness/industry_user_admin/dashboard/users/page.tsx, client/app/components/datagrid/ChangeUserOperatorStatusColumnCell.tsx, client/app/components/routes/select-operator/Page.tsx, client/app/components/routes/select-operator/form/ConfirmSelectedOperator.tsx, client/app/utils/users/adminUserOperators.ts
We made an incorrect assumption in many of our endpoints that users will have a 1:1 relationship with the user_operator table. A user can be declined (for example if they requested access to the incorrect operator) and then create a new request that is then approved. 
In this PR, many of our endpoints now ignore DECLINED statuses when fetching information and on the frontend a couple screens have been added to show that they have been declined when a user attempts to select an operator where their status is declined.
This PR has touch a lot of endpoints and will need thorough walkthroughs of all the workflows during review. 
Before pushing I tested the following workflows:
- External can request admin access
- Internal can decline admin access
- Internal sees the DECLINED request row
- …
=> Fix: 885 declined request side effects

bc_obps/registration/api/user_operator.py
Follow up fix for the work done in #929. A last minute change in that PR to the @authorize check for the new /operator-access-declined endpoint caused an issue where nobody could access it, which was in turn causing the app to always direct a user to the access declined message.
=> fix: fix authorize definition causing incorrect declined message

client/app/components/form/titles/operationsTitles.tsx, client/app/utils/jsonSchema/operations.ts
Some decisions around the operations form were made while investigating this bug:
- Remove the "Did you submit a GHG Report for 2022"  section entirely. It served no purpose and was the source of the bug
- Add a readonly bcghgid field to always display the bcghgid (if they have it, otherwise shows a message that it will be assigned by CAS)
- Add additional context around opt-ins and a link to the site with more information and opt-in application forms
=> Fix: 879 bcghgid opt ins

bc_obps/registration/api/user_operator.py
Bug details in #944
Fixed in this PR:
- Internal users cannot approve or decline access requests when operator is in DRAFT status
- External admin users cannot approve or decline subsequent access requests until their first BORO ID application approval.
=> Fix: 944 relax update user operator status conditions

client/app/utils/jsonSchema/operations.ts
Quick fix for major bug that meant that only 1 new operation could be created. In the BCGHG ID field on the Operations form, the string "New operations will be ...." was set to be a default value when it should have been a placeholder. That string was then being treated as a BCGHG ID, which must be unique, so no subsequent operations could be created nor could the value be changed because it's readonly in the form. 
No E2E tests for Operations yet, so instead here's manually created proof that I was able to log in as external user and create 2 new operations for my operator. As a bonus, in the Operations table, the BCGHG ID field is now empty (when null) instead of rendering "New operations will be..."
=> Fix: set text as placeholder on BCGHG ID field instead of default

bc_obps/registration/api/user_operator.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, client/app/components/routes/select-operator/Page.tsx
This PR fixes some access control in the API & fixes the redirects under certain conditions:
- API: Only external admins can access the PUT endpoint for updating an operator
- Client: If operator.status = DRAFT && operator.is_new = false then the user is redirected to the access received page instead of the edit operator form
=> Fix: 954 update draft operator flow

bc_obps/registration/api/user_operator.py, bc_obps/registration/fixtures/mock/userOperator.json, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, bc_obps/registration/tests/utils/bakers.py
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54066703
To manually test:
part 1:
- login with IDIR and go to the user_operator table (operators tile)
- approve someone, noting their operator
- you should see the person you approved, but everyone else from that operator should disappear from the list
part 2:
- Login as bc-cas-dev and go to the users tile
- approve someone
- logout and log back in as IDIR
- whoever you approved should not show up in the operator tile list
=> 956 user operator table

client/app/components/navigation/Tiles.tsx
The logic in the Tiles component had a bug where the dashboard was blank when operators were in draft status. This fixes that bug. 
To test: 
request access to an operator that is in draft status & get approved. The dashboard should show tiles where it previously wasn't
=> fix: Tile logic fixed so draft operators don't show blank dashboard

helm/cas-registration/templates/backend/deployment.yaml
Use pgbouncer to connect to db from backend instead of connecting to postgres directly
=> chore: use pgbouncer to connect to postgres from backend

bc_obps/registration/api/business_structure.py, bc_obps/registration/api/naics.py, bc_obps/registration/api/operation.py, bc_obps/registration/api/operator.py, bc_obps/registration/api/regulated_products.py, bc_obps/registration/api/reporting_activities.py, bc_obps/registration/api/user.py, bc_obps/registration/api/user_operator.py, bc_obps/registration/decorators.py, bc_obps/registration/models.py, bc_obps/registration/tests/endpoints/test_useroperator_endpoints.py, bc_obps/registration/tests/test_utils.py, bc_obps/registration/utils.py
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=54526586
This PR prevents unapproved industry_users from accessing endpoints by default. If an endpoint should be accessible to unapproved users, we can add an argument to the @authorize decorator. Therefore, manual testing for this PR is walking through all the industry user workflows to make sure people can still access everything they need to. I went through the workflows before posting the PR, but the reviewer should probably take a look too.
Sonarcloud fail is on duplicated code in tests
=> 976 authorize decorator

client/app/not-found.tsx, client/e2e/.env.local.example, client/e2e/pages/authenticated/routes/page.spec.ts, client/e2e/poms/operation.ts, client/e2e/poms/operations.ts, client/e2e/poms/operator.ts, client/e2e/poms/operators.ts, client/e2e/poms/users.ts, client/e2e/utils/enums.ts, client/e2e/utils/queries.ts
Addresses [1006](https://github.com/bcgov/cas-registration/issues/1006)
- ` client/e2e/pages/authenticated/dashboard/routes/page.spec.ts` for comprehensive coverage of route access for each role
**Option 1:** CI e2e test
Valid [e2e test](https://github.com/bcgov/cas-registration/actions/runs/8163648892) status is  `pass` 
**OR**
Download artefact files from `GitHub Actions\Test Registration App` to your `client/playwright-report` folder and run command `cd client && yarn playwright show-report`
[CI artefact](https://github.com/bcgov/cas-registration/actions/runs/8163648892#artifacts)
[CI artefact download](https://github.com/bcgov/cas-registration/actions/runs/8163648892/artifacts/1300215141)
**Option 2:** Local e2e testing:
**Pre-reqs** 
1. From file `client/e2e/.env.local.example` …
=> 1006 e2e route access by role

bc_obps/bc_obps/settings.py
Backend was missing DSN information necessary to report to sentry
=> chore: add sentry dsn config for backend

client/e2e/pages/authenticated/routes/page.spec.ts, client/e2e/poms/profile.ts, client/playwright.config.ts
[Card](https://github.com/bcgov/cas-registration/issues/1073)
and
[Card](https://github.com/bcgov/cas-registration/issues/1074)
- Increased in Playwright `timeout` configuration increased to improve test passing consistency.
- Run the entire test suite multiple times in [CI](https://github.com/bcgov/cas-registration/actions/runs/8249642888)
- Observe tests pass consistently
=> chore: increase global Playwright timeout

client/app/components/form/widgets/PhoneWidget.tsx
Fix for #816 
I had difficulty recreating this at first though it turns out it's an error with US phone numbers. Since both Canada and US use the same phone format a US number can pass our validation.
To recreate it log in as either `bc-cas-dev-three` or through IDIR on a fresh database so it brings you to the profile page. For the phone number use an American phone number eg `(234)-555-1234`, fill out the position field and submit the form.
Return to the profile page either by clicking back or clicking the user on the top right and the phone field will be a US number. If you try to edit it the widget will be locked out and show an error:
There are a couple options to fix this and I think we should go with adding US to the `onlyCountries` prop. In the edge case that someone uses a US …
=> fix: phone widget lockout error

client/e2e/pages/authenticated/dashboard/page.spec.ts, client/e2e/pages/authenticated/dashboard/profile/page.spec.ts, client/e2e/pages/authenticated/routes/page.spec.ts, client/e2e/poms/profile.ts, client/e2e/utils/enums.ts
[Card](https://github.com/bcgov/cas-registration/issues/1074)
- Fixes flaky ` Test Profile Page › Test Role none › Test Update `
- Redesign looping to improve test describe details
**Option 1:** CI e2e test
Validate [e2e test](https://github.com/bcgov/cas-registration/actions/runs/8300523821) status is  `pass` 
**OR**
Download artefact files from `GitHub Actions\Test Registration App` to your `client/playwright-report` folder and run command `cd client && yarn playwright show-report`
[CI artefact](https://github.com/bcgov/cas-registration/actions/runs/8300523821#artifacts)
[CI artefact download](https://github.com/bcgov/cas-registration/actions/runs/8300523821/artifacts/1330478519)
**Option 2:** Local e2e testing:
**Pre-reqs** 
1. From file `client/e2e/.env.local.example` create …
=> 1074 fix e2e flaky tests

.github/workflows/test.yaml, client/e2e/.env.local.example, client/e2e/pages/authenticated/dashboard/page.spec.ts, client/e2e/pages/authenticated/dashboard/profile/page.spec.ts, client/e2e/pages/authenticated/routes/page.spec.ts, client/e2e/poms/dashboard.ts, client/e2e/poms/profile.ts, client/e2e/utils/enums.ts, client/e2e/workflows/bceidbusiness/industry_user.ts, client/e2e/workflows/bceidbusiness/industry_user_admin.ts, client/e2e/workflows/bceidbusiness/new_user.spec.ts, client/e2e/workflows/idir/cas_admin.spec.ts, client/e2e/workflows/idir/cas_analyst.spec.ts, client/e2e/workflows/idir/cas_pending.spec.ts, client/playwright.config.ts
[Card](https://github.com/bcgov/cas-registration/issues/1101)
[Card](https://github.com/bcgov/cas-registration/issues/1102)
- Removes dependency on `client/e2e/setup` login and file save for storageStates
- Shards the e2e tests into chunks for faster test execution
- Merges shard reports to one report
**Option 1:** CI e2e test
Validate [e2e test](https://github.com/bcgov/cas-registration/actions/runs/8327573284) status is  `pass` 
**OR**
Download artefact files from `GitHub Actions\Test Registration App` to your `client/playwright-report` folder and run command `cd client && yarn playwright show-report`
[CI artefact](https://github.com/bcgov/cas-registration/actions/runs/8327573284#artifacts)
[CI artefact download](https://github.com/bcgov/cas-registration/actions/runs/8327573284/artifacts …
=> e2e performance optimization

bc_obps/registration/fixtures/mock/operator.json, bc_obps/registration/fixtures/mock/userOperator.json, client/app/components/form/UserOperatorReviewForm.tsx, client/app/components/routes/access-requests/form/UserOperatorReview.tsx
Fix for #1007 
Also fixed the User Operator fixtures that were tied to a new Operator. Many of them were tied to the same new Operator which can't happen in the app since you can't create a new operator with the same CRA number or BC corporate registry number. To fix this I created a bunch of new Operators to tie to each of the offending User Operators.
=> fix: hide prime admin review when operator is declined

Makefile, helm/cas-registration/values-giraffe.yaml, shipit.yml
task: https://github.com/orgs/bcgov/projects/123/views/2?pane=issue&itemId=54817515
Created a new make target for deploying from the ```giraffe-develop``` branch to the ```CIF-tools``` namespace. I added some logic to the ```shipit.yml``` file to determine which branch it is being run from and choose the appropriate make target. 
The new make target is hard-coded to pull values from values-giraffe.yaml, which has a frontend route of cas-reg-giraffe-dev.apps.silver.devops.gov.bc.ca, which is subject to change.
=> chore: add new make target and logic for shipit.yml

.github/workflows/test.yaml
[Card](https://github.com/bcgov/cas-registration/issues/1113)
- Reduces CI pipeline's e2e Playwright tests run time
- Restricts CI pipeline's e2e Playwright tests report artifacts to failures
- Cancels current job when pushing new commit into the PR
- Implementing playwright binary cache using `shard` matrix variables results in test(s) finding the cache but then failing due to missing browsers installs 🤷 
- Implementing playwright binary cache using `browser` matrix results in 1 of 3 tests, the `e2e test webkit`,  NOT finding cache; so, that test takes extra 30 seconds to install Playwright deps 🤷 
**Possible Explanation** [This is expected...](https://github.com/microsoft/playwright/issues/22146#issuecomment-1493902369)
- Overall, we have reduced e2e test run by ~40 seconds 🎯
Validate …
=> 1113 e2e ci matrix cache

.github/workflows/test.yaml
Implements issue #1168
Merging Happo reports after the recent PR which runs parallel using shards.
Happo docs for this here: https://docs.happo.io/docs/playwright#parallel-builds
One thing I could use some feedback on is the addition of yet another e2e job, `happo-finalize`. I had considered putting it in the `e2e report` job to keep the job list cleaner but left it here for now.
=> Happo merge reports

client/app/(onboarding)/home/page.tsx, client/app/components/form/titles/operationsTitles.tsx, client/app/components/routes/operations/form/Operation.tsx, client/app/utils/urls.ts
Implements #1153 
I thought it would be good practice to store links in a constants file so I created a `app/utils/urls.ts` file. I didn't want to go too far beyond the scope of this ticket so I just added the 3 urls on the home page. I also replaced a repeated URL that is in the Operations form as you will need to go there to test these work anyways.
To test the two URLs in the Operations page you need to log in as `bc-cas-dev` and click `View Details` for the `Approved` Operation and check these two urls:
=> feat: add carbon tax exemption link

.github/actions/dev-env-setup/action.yml, .github/actions/yarn-cache/action.yml, .github/workflows/test.yaml, client/e2e/workflows/bceidbusiness/industry_user.spec.ts
Follow up PR to #1168 
- Fixes a bug from using `github.event.pull_request.head.sha` as the `HAPPO_NONCE` variable. Since the pull request head sha doesn't exist when this is ran from develop it fails. I am using `github.sha` instead which is the sha of the commit that started the job. 
- Move the `yarn cache` step from `dev-env-action` into it's own composite action. This greatly reduces the time of the `happo-finalize` step and hopefully will be useful in the future when we need to run a command from a dependency that is in our `node_modules` folder.
- Added a timeout since we keep getting a Firefox screenshot diff which gives the text 500ms to settle and render correctly. If you use the zoom feature in Happo, set it to 400% and zoom into one of the affected characters using the swipe …
=> happo e2e optimize

bc_obps/.env.example, bc_obps/bc_obps/settings.py, client/.env.example, client/app/utils/actions.ts, client/sentry.client.config.ts, client/sentry.edge.config.ts, client/sentry.server.config.ts, helm/cas-registration/templates/backend/deployment.yaml, helm/cas-registration/templates/frontend/deployment.yaml, helm/cas-registration/values-prod.yaml
[ISSUE 1189](https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=57110752)
We have made some changes to the sentry `traceSampleRate`. It will now only send 10% of the transactions to the sentry server. Additionally, we have added `traceSampleRate` as a deployment variable for better control. We can now manually change its value in Openshift and shuffle pods instead of making a release every time we want to change its value.
Furthermore, we have put the sentry exception handler in a try/catch block to track the number of errors we receive with this implementation. However, if we receive a lot of emails, we might want to remove the handler from the `try` block.
=> Reduce sentry trace rate

bc_obps/registration/fixtures/mock/operation.json, client/app/components/navigation/Bread.tsx, client/e2e/poms/operation.ts, client/e2e/workflows/bceidbusiness/industry_user.spec.ts, client/yarn.lock
Follow up to #843 as I introduced some flakey screenshots in that PR.
- Add assertions to make sure the `Operation name` breadcrumb is visible before taking a screenshot as it takes a second to appear.
- Add `created_at` values to ensure the Operations table is always in the same order
- Removed the wait added to fix the Firefox spurious diff for the `Add a new Operator - required errors` spurious diff. It made it happen less but it still popped up sometimes and was the only diff that showed when I pushed the fixtures updates. I am going to propose we add it to the `Permentantly ignored diffs` as suggested in the [Happo docs here](https://docs.happo.io/docs/ignoring-diffs). We test in 4 different browsers so losing this screenshot in Firefox should be safe. If you look in the sidebar to …
=> test: add extra assertion to fix flakey breadcrumb screenshot tests

.github/actions/dev-env-setup/action.yml, .github/workflows/codeql.yaml, .github/workflows/scan-code-trivy.yaml, .github/workflows/test.yaml, .github/workflows/update-manifests.yaml
#159
Updated our actions, now none of our workflows have these depreciated warnings under them:
=> chore: update depreciated github actions

.github/workflows/test.yaml, .gitignore, helm/cas-registration/Chart.lock, helm/cas-registration/Chart.yaml, helm/cas-registration/templates/mailhog/mailhog-ingress.yaml, helm/cas-registration/templates/mailhog/mailhog-route.yaml, helm/cas-registration/values-dev.yaml, helm/cas-registration/values-test.yaml, helm/cas-registration/values.yaml
Adds mailhog to the dev & test environments to ensure test emails are not actually delivered outside of our environment.
This implementation was pulled mostly from what we're doing in CIIP. It may need tweaking once we have CHES set up if there are any differences in that setup from what we have in CIIP.
=> Chore: mailhog

shipit.yml
Since the deploy.sh script won't work to deploy giraffe stuff anyway, this is an alternative fix to #1368. It just calls make install & we can figure out a combined deploy strategy later.
=> chore: alternative fix to 1368

deploy.sh, shipit.yml
- Re-adds using the deploy.sh script in shipit.yml
- Updates deploy.sh to parse a reporting-specific environment from shipit into an environment that can be used by helm to deploy to openshift
=> chore: deploy reporting with specific shipit environment

.github/actions/dev-env-setup/action.yml
Not sure if this was related to our other recent CI issues though I still had issues with multiple failing CI steps due to missing node_modules dependencies. I noticed we are retrieving the cache but not installing it if it doesn't exist.
Might have been something with the recent NX merge that finally caught us out on this. Looks like any PR that changes the `yarn.lock` is failing now, this seems to fix it.
Failing run: https://github.com/bcgov/cas-registration/actions/runs/8713164323
Passing run in the same PR with this fix applied: https://github.com/bcgov/cas-registration/actions/runs/8713247399
=> fix: install yarn dependencies in github actions if cache doesn't exist

.github/actions/local-app-run/action.yml, .github/workflows/test.yaml, bc_obps/.env.example, bc_obps/bc_obps/settings.py, bc_obps/common_utils/email/email_service.py, bc_obps/common_utils/tests/test_email_service.py, bc_obps/poetry.lock, bc_obps/pyproject.toml, helm/cas-registration/templates/backend/deployment.yaml
Created an EmailService for sending emails using CHES API.
See backend .env.example - there's some new env vars needed for local setup. To get the secret values, see the updated backend .env file in 1Password.
Have also added the relevant secrets to our Secrets in Github.
Note: most of the unit tests in `test_email_service.py` are simply mocking the calls to `EmailService`, so actual emails aren't being sent as part of CI (or pytests when running tests locally). However, I've included a unit test and marked it with `skip` - if you want to run the test locally and actually send an email, simply comment out the `@pytest.mark.skip` line (please also remember to change the value of `real_recipient` in the test to your own email address; my inbox is already at breaking point).
=> Email_Service

.github/workflows/test.yaml
Looks like their DockerHub images went down, so switching to GHCR images since I saw they are hosted there as well:
https://www.zaproxy.org/blog/2023-06-13-ghcr-docker-images/
Fixed run here: 
https://github.com/bcgov/cas-registration/actions/runs/8790774852/job/24123733697?pr=1443
=> fix owasp-zap scan ci issue

client/app/api/auth/[...nextauth]/route.ts, client/app/components/form/FormBase.tsx, client/app/components/navigation/Profile.tsx, client/app/components/routes/profile/User.tsx, client/app/components/routes/select-operator/Page.tsx, client/app/utils/actions.ts, client/app/utils/customTransformErrors.ts, client/app/utils/getUUIDFromEndpoint.ts, client/app/utils/getUserFullName.ts, client/app/utils/users/adminUserOperators.ts, client/package.json, client/tests/setup/global.tsx, client/tests/setup/mocks.ts, client/tests/utils/actions.test.ts, client/tests/utils/customTransformErrors.test.ts, client/tests/utils/getEnvValue.test.ts, client/tests/utils/getUUIDFromEndpoint.test.ts, client/tests/utils/getUserFullName.test.ts, client/yarn.lock
Implements #1234 
Added tests most of the functions in the `/utils` folder
Re-added the `vitest-fetch-mock` library and added it to our mocks where it can be imported as `fetch`.
Please let me know if you can think of useful scenarios I haven't tested, especially for the action handler which is probably the most important util tested here 🙇 
What is not tested:
- the `jsonSchema` folder. These json schema files should probably live elsewhere and we aren't likely to test them on their own. They will get tested when we get to each form and are being tested in our e2e tests.
- the `/users/adminUserOperators.ts` file. It will likely get completely removed in #1433 and some of it is completely redundant and left over from early in the project (the `transformedTileData` map doesn't do anything …
=> 1234 util tests

docs/helm-secrets-cas-pipeline.md
Add documentation on how to use the cas-pipeline repo to securely automate secret generation for external secrets like API Keys for external services.
=> docs: add documentation on secure secret automation with cas-pipeline

bc_obps/registration/api/user/user_app_role.py, bc_obps/registration/api/user/user_profile.py, bc_obps/registration/api/user_operator/is_approved_admin_user_operator.py, bc_obps/registration/tests/endpoints/user_operator/test_authorization.py, bc_obps/registration/tests/endpoints/user_operator/test_is_approved_admin_user_operator.py, client/app/api/auth/[...nextauth]/route.ts, client/app/utils/actions.ts
Addresses:
[1513](https://github.com/bcgov/cas-registration/issues/1513)
-  updated API endpoints to retrieve the `user_guid` from the Authorization header instead of the endpoint parameter
- updated `client/app/utils/actions.ts` to splice endpoint `user_guid` parameter
- API calls from `client/app/api/auth/[...nextauth]/route.ts\callback jwt` return correct JSON data
- updated API endpoint tests
- Validate app login process initializes app user session as expected:
```
cd bc_obps
make reset_db
make run
```  
```
cd client && yarn dev
```  
3. Navigate to `http://localhost:3000`
4. Click a "Log in with Business BCeID" button
5. Sign in to Keycloak using `bc-cas-dev`
6. **Expected …
=> 1513 API auth header consistency

bc_obps/bc_obps/settings.py
**Note:**
Sentry was not able to capture backend errors since we don't pass `DEBUG` env variable in our namespaces. This fix will run the sentry on the backend again.
=> Fix django sentry when not passing `DEBUG` env variable

Makefile, helm/cas-registration/templates/backend/job/reset-database.yaml
--dry-run flag was added to `make install` target. This caused shipit to only print the manifest on deploy rather than actually deploying
=> chore: remove --dry-run flag from makefile

bciers/apps/reporting/src/app/(authenticated)/authenticated/facilities/Operators.tsx, bciers/apps/reporting/src/app/(authenticated)/authenticated/facilities/page.tsx, bciers/apps/reporting/src/app/(authenticated)/authenticated/page.tsx, bciers/apps/reporting/src/app/page.tsx
Recreated this PR off develop after nx migration
card: https://github.com/bcgov/cas-reporting/issues/123
Adding a placeholder page to fetch and display operations and facilities for the user viewing the page. If a user without operators is signed in, the space after operators: will be blank.
To test:
navigate to /bc_obps/ in the terminal and follow the instructions in /docs/developer-environment-setup.md/ to get it running
in another terminal run yarn dev from /client/, open on localhost:3000 and sign in using BCeID. Go through first time setup with one of the accounts in the 1password (bc-cas-dev etc)
in another terminal access the django shell by navigating to /bc_obps/ and running python manage.py shell
in the django shell, modify the app_role value of your user from before. The …
=> chore: create placeholder page for API results, add BCeID login

.github/actions/local-app-run/action.yml, bc_obps/bc_obps/settings.py, bc_obps/registration/schema/operation.py, bc_obps/registration/tests/utils/helpers.py, bciers/.gitignore, bciers/apps/registration/e2e/poms/operation.ts, bciers/apps/registration/e2e/poms/operations.ts, bciers/apps/registration/e2e/utils/enums.ts, bciers/apps/registration/e2e/utils/pool.ts, bciers/apps/registration/e2e/utils/queries.ts, bciers/apps/registration/e2e/workflows/bceidbusiness/industry_user_admin.spec.ts, bciers/apps/registration/project.json, bciers/apps/registration/tsconfig.json, bciers/package.json, docs/developer-guide.md
card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=61490241
This PR revealed that the e2e test for creating and submitting an operation wasn't testing everything we thought it was.
This PR:
- steals @marcellmueller's work for getting the e2e tests running locally
- adds an assertion for the confirmation-of-submission message (the line of code we had for this previously was missing the assertion part)
- bypasses GCS when running in CI (so we don't have to set up GCS #718, which is an 8-pointer). @Sepehr-Sobhani and I looked at using a mock file, but it still hits the django endpoint and we get the GCS error
- adds the check that newly created operations are visible as the card describes
Note: most of the happo screenshots are flake; the one that isn't …
=> test: check that newly created operations are visible

bc_obps/bc_obps/settings.py
**Note:**
A while ago, we mistakenly used the Next.js Sentry DSN key instead of the Django DSN key, causing all Django-related errors to be directed to the Next.js project. Here is the fix for this issue.
=> Use Sentry Django DSN key instead of NextJS DSN key

bc_obps/poetry.lock
Updating this package the difficult way after dependabot's PR failed.
Happo failures = flake.
=> Chore: updated requests package manually because dependabot didnt work

.sonarcloud.properties, bciers/apps/registration/e2e/utils/enums.ts, bciers/apps/registration/e2e/utils/helpers.ts, bciers/apps/registration/e2e/workflows/bceidbusiness/industry_user.spec.ts, bciers/apps/registration/e2e/workflows/bceidbusiness/industry_user_admin.spec.ts, bciers/apps/registration/e2e/workflows/idir/cas_admin.spec.ts, bciers/apps/registration/e2e/workflows/idir/cas_analyst.spec.ts, docs/developer-guide.md
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=61334238
This PR:
- refactors .spec file code to use POMs and helper functions
- adds three stabilization functions to help with flakiness
- there were a couple of the screenshots that were flaky no matter how much stabilization I threw at them. I made sure to leave one screenshot in at least one browser everywhere and put notes about this in the docs
=> Fix happo flake

bc_obps/registration/api/v2/__init__.py, bc_obps/registration/api/v2/operations.py, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v2/_operations/test_operations_endpoint.py, bc_obps/service/operation_service_v2.py, bciers/apps/registration/app/components/datagrid/models/operationColumns.ts, bciers/apps/registration/app/components/datagrid/models/operationGroupColumns.ts, bciers/apps/registration/app/components/operations/OperationDataGrid.tsx, bciers/apps/registration/app/components/operations/Operations.tsx, bciers/apps/registration/app/components/operations/OperationsPage.tsx, bciers/apps/registration/app/components/operations/types.ts, bciers/apps/registration/app/operations/layout.tsx, bciers/apps/registration/app/operations/page.tsx, bciers/apps/registration1/app/utils/actions.ts, bciers/apps/registration1/tests/v2/operations/Operations.test.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=64781153
This one can't be fully completed until we have auth (can't confirm that only the allowed people can see stuff), so I'll do a follow up PR later.
This PR:
- new v2 operations endpoint to retrieve the p2 data
- new v2 schemas
- tests for ^
- new `page.tsx` file for p2
- new FE p2 files that handle operation grid columns. This resulted in new front-end components because I had to update the imports all the way up to the `page.tsx` file
- new version of the existing unit tests (coverage wasn't great, we have an epic to add more: https://github.com/bcgov/cas-registration/milestone/4)
- handles the internal grid as well because it ended up having almost the same requirements as the external one
Notes:
- there …
=> 1686 2 external operations grid

helm/cas-registration/templates/backend/job/terraform-apply.yaml
Fix to address the issue identified by Sepehr in the Terraform Job deployment. _Should_ have been counted against time-based quota rather than long-running.
=> fix: terraform job's template to be time-bound

bciers/apps/registration1/app/components/operations/OperationsForm.tsx, bciers/apps/registration1/tests/components/form/OperationsForm.test.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=59180231
This PR:
- shows a different confirmation message if the operation already has a BORO ID
- no changes needed to the email service--emails were already being sent conditionally based on application status (see cas-registration/bc_obps/service/operation_service.py)
To test:
- Make a new operation. You should get the original message.
- Edit an approved operation. You should get the new message.
=> 1322 confirmation message

docs/git-usage.md
Adds documentation to our docs folder on how the DST uses git
- Branching
- Rebase over merge
- Conventional commits & changelog
=> docs: add git-usage documentation for DST

bciers/apps/registration1/tests/shared/DataGrid.test.tsx, bciers/libs/shared/components/src/lib/datagrid/DataGrid.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=60748637
This PR adds some of the tests described in the card:
- rendering
- sorting
- url changes when paginating
I'm switching over to more high-priority work, so the card will go back into tech debt backlog after this PR is merged.
=> DataGrid vitest

bciers/apps/reporting/src/app/bceidbusiness/industry_user/report/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/report/page.tsx, bciers/apps/reporting/src/app/components/report/report.tsx, bciers/apps/reporting/src/app/components/routes/report/Page.tsx, bciers/libs/components/src/form/components/MultiStepHeader.test.tsx, bciers/libs/components/src/form/components/MultiStepHeader.tsx
Card: https://github.com/bcgov/cas-reporting/issues/236
Added a new report page featuring a multistep header with UI enhancements, addressing the requirements outlined in the card.
This initial implementation displays the multistep header without interactive functionality. Once the multistep form is integrated, this header will be fully interactive and functional.
=> 236 Report Overview Component 

bciers/Dockerfile, bciers/apps/dashboard/next.config.js, bciers/apps/dashboard/project.json, bciers/apps/registration/next.config.js, bciers/apps/registration/project.json, bciers/apps/reporting/next.config.js, bciers/apps/reporting/project.json, bciers/next.config.base.js, helm/cas-bciers/templates/common/frontend-env-configmap.yaml, helm/cas-bciers/templates/registration/route.yaml, helm/cas-bciers/templates/reporting/route.yaml
Addresses final part of bcgov/cas-reporting#273. Ensure that the Registration and Reporting applications deploy to and read from the correct paths in OpenShift. 
- Sets NextJS to build in standalone mode.
- This was found to set the proper paths when next applications fetch their first-fetches and assets, static or otherwise.
- Use standalone as container runtime.
- Update OpenShift routes to match internal service routes.
- NextJS handles routing to Reg and Rep when deployed locally, but we utilize OpenShift Routes (ingress) to handle routing to services and therefore pods.
> I've hand-changed Reporting and Registration's container image target in OpenShift to use this PR, and updated the routes to match.
1. Navigate to https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca/, login …
=> 273 Pathing fix

helm/cas-bciers/Chart.lock, helm/cas-bciers/templates/NetworkPolicy/admin-frontend-allow-from-openshift-ingress.yaml, helm/cas-bciers/templates/NetworkPolicy/caom-frontend-allow-from-openshift-ingress.yaml, helm/cas-bciers/templates/coam/deployment.yaml
I noticed that this failed in shipit, also updated dependencies as I got an error testing this with `helm template`
=> chore: fix coam helm deployment.yaml indentation

bciers/apps/dashboard/middlewares/withAuthorizationDashboard.test.ts, bciers/apps/dashboard/middlewares/withAuthorizationDashboard.ts, bciers/libs/components/src/navigation/Profile.tsx
Fixing IDIR login for new users. At some point the profile page was moved from `Registration` to `Administration`. The team decided that it was good to stay there. 
To test log in with IDIR using a fresh database, the profile redirect works and the user can fill out their information.
=> chore: fix profile urls

bc_obps/bc_obps/settings.py, bciers/apps/registration1/next.config.js, bciers/next.config.base.js
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=71304153
There are two issues here:
1. Files are below the size limit (currently 20mb locally and 1mb in dev/test/prod) but can't be submitted. This is because we had a limit on the body size, not the file size specifically, and sometimes the body has extra stuff in it (probably the dataurl?) that increases the size. This is fixed in this PR: I set a file size limit and increased the body size to give us a buffer.
2. Dev/test/prod has a body size limit of 1mb even though we've got it set much higher in the next config. I ~think the problem may be that the next configs aren't loaded properly in dev/test/prod (it's fine in local). There's a console.log in the next config for testing
=> 1964 upload bug

bciers/apps/registration1/app/api/auth/token/route.ts
Fix for [#1981](https://github.com/bcgov/cas-registration/issues/1981)
Thanks to a suggestion from Josh I updated the registration1 `route.ts` file to specify a cookie name and opened this PR to build an image. I then grabbed the `sha` of the image, changed the image file in the deployment from `latest` to the sha and cycled the pods so it would use this image. 
Now login seems to be working again in `/dev`. I'd like to get this merged in and do a proper deployment and double check that it's working as expected.
=> reg1 auth always redirects back to landing page after login

deploy.sh, shipit.yml
Added a deploy script to fix `reg1` shipit deployment. Now we will be able to deploy both our original `reg1` helm chart as well as the `bciers` helm chart through shipit.
To test this you can add `--dry-run` to the `make install` and `make install_reg1` commands then:
`sudo chmod +x deploy.sh`
Replace `prefix` here with our namespace prefix:
`OBPS_NAMESPACE_PREFIX=prefix ENVIRONMENT=reg1-dev ./deploy.sh`
The terminal should say `Running reg1 make target for dev environment...` and run the `make install_reg1` script.
=> chore: add deploy.sh script for shipit

bc_obps/reporting/api/reports.py, bciers/apps/reporting/src/app/bceidbusiness/industry_user/operations/page.tsx, bciers/apps/reporting/src/app/components/context/CurrentReportingYearContext.tsx, bciers/apps/reporting/src/app/components/datagrid/models/operationColumns.tsx, bciers/apps/reporting/src/app/utils/getReportingYear.ts, bciers/apps/reporting/tests/pages/operationsColumns.test.tsx
Addresses bcgov/cas-reporting#274. Adds the "Actions" column in the Reporting Dashboard with an action to Start or Continue a report.
- Adds _Action_ column to operations table.
- Adds a _CurrentReportingYear_ context provider.
0. Run `make reset_db` in your backend folder if required. 
1. Spin up your local server, log in. 
2. Navigate to `/reporting/operations`. You should see a list of operations. 
3. Click the **Start** action for _Operation 3_. After a few moments, you should be taken to a 404'd page with the address `operations/1/review-operator-data`, with `/1/` being the report number. 
4. Navigate to the previous page, then click the **Start** action for _Operation 5_. After a few moments, you should be taken to a 404'd page with the address `operations/2/review-operator-data`, …
=> feat: Add actions column to reporting operations dashboard

bc_obps/reporting/fixtures/mock/reporting_year.json, bc_obps/reporting/tests/service/test_reporting_year_service.py, bc_obps/service/reporting_year_service.py, bciers/apps/reporting/src/app/components/routes/operations/Page.tsx
Addresses bcgov/cas-reporting#238. This adds the _current_ reporting year to the reporting operations page. 
- Updates ReportingYearService to get current reporting year based on start/end reporting windows.
- Add fixture for 2023 (to cover for testing in current year) 
- Fetch from service and populate a header on the operations page.
0. Run `bc_obps/make reset_db` to ensure the new fixtures are loaded. 
1. Spin up a local instance (`bc_obps/make start_db && bc_obps/make run` + `yarn dev-all`). Login with `bc-cas-dev`. Navigate to `/reporting/operations` using your browser address bar. 
2. Check the header above the table, it should read `Reporting Year 2023` (unless you test this a year from now)
=> 238 reporting year

bc_obps/common/management/commands/load_fixtures.py
Fix for deployed version of bcgov/cas-reporting#238. Fixtures existed for reporting years, which loaded locally, but were not part of the common init that would load them when deployed.
=> 238 reporting year fixtures

bc_obps/common/management/commands/load_fixtures.py, bc_obps/reporting/migrations/0007_prod_data.py
Moves the `reporting`.`reporting_year` fixture mocks from `common`.`load_fixtures` into a `reporting` migration.
=> 238 reporting year migrations

helm/cas-bciers/values-dev.yaml, helm/cas-bciers/values-test.yaml, helm/cas-bciers/values.yaml, helm/cas-registration/values-dev.yaml, helm/cas-registration/values-test.yaml, helm/cas-registration/values.yaml
Last week we reduced the requests and limits of our frontend pods to fix the broken deployments which were hanging due to lack of resources. However this caused the apps to have lots of errors and run sluggish. Until we get more resources we will have to run 1 replica even if it's not ideal for testing.  
- Reduce replicas to 1
- Restore previous requests and limits
=> chore: adjust bciers and registration1 helm dev and test values

bciers/apps/registration1/Dockerfile, bciers/apps/registration1/next.config.js
[#1964](https://github.com/bcgov/cas-registration/issues/1964)
Finally got this working by copying some missing build files in registration1 Dockerfile, most importantly `next.config.js`. Also removed the inherited settings from the shared `next.config` that is in the `bciers` directory as I couldn't get this to work in e2e with the next config setting [output: standalone](https://nextjs.org/docs/pages/api-reference/next-config-js/output) that the rest of our apps use to containerize the app.
While we will need to figure out why that wasn't working in the near future, it was important to get this bug fixed in prod so I just modified the original Dockerfile so we could get this issue unblocked.
I've been trying to fix the unrelated nextjs permissions error when we noticed in the pod but …
=> Registration1 upload bug

bciers/apps/administration/app/error.tsx, bciers/apps/coam/app/error.tsx, bciers/apps/dashboard/app/error.tsx, bciers/apps/registration/app/error.tsx, bciers/apps/reporting/src/app/error.tsx, bciers/libs/components/src/error/ErrorBoundary.tsx, bciers/libs/components/src/error/ErrorPage.test.tsx, bciers/libs/components/src/error/ErrorPage.tsx
Addresses: 
[1982](https://github.com/bcgov/cas-registration/issues/1982)
- Shared ErrorBoundary across apps
- `bciers/libs/components/src/error/ErrorBoundary.tsx`
- `bciers/libs/components/src/error/Error.tsx`
- `bciers/apps/administration/app/error.tsx`
- `bciers/apps/coam/app/error.tsx`   
- `bciers/apps/dashboard/app/error.tsx`
- `bciers/apps/registration/app/error.tsx`
- `bciers/apps/reporting/app/error.tsx`
- `global-error.tsx` will be addressed [here](https://github.com/bcgov/cas-registration/issues/2044)
```
cd bc_obps
make reset_db
make run
```  
```
```  
1.  In `bciers/apps/administration/app/page.tsx` add temporary code `... export default …
=> chore: shared error boundary

helm/cas-bciers/values-test.yaml
Adds missing values for the `Administration` and `COAM` apps for test. Currently you can [log into test](https://cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca/) though since these were left out both of these apps are broken.
=> chore: add missing bciers helm test values

bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/app/components/contacts/ContactsDataGrid.tsx, bciers/apps/administration/app/components/facilities/FacilitiesForm.tsx, bciers/apps/administration/app/components/facilities/FacilityDataGrid.tsx, bciers/apps/administration/app/components/operations/OperationDataGrid.tsx, bciers/apps/administration/app/components/routes/facilities/Page.tsx, bciers/apps/administration/tests/components/contacts/ContactsDataGrid.test.tsx, bciers/apps/administration/tests/components/facilities/FacilitiesForm.test.tsx, bciers/apps/administration/tests/components/operations/OperationDataGrid.test.tsx, bciers/apps/administration/tests/routes/FacilitiesPage.test.tsx, bciers/libs/components/src/datagrid/cells/OperationsActionCell.tsx, bciers/libs/components/src/navigation/Bread.tsx
Addresses: 
[2026](https://github.com/bcgov/cas-registration/issues/2026)
- Updated breadcrumbs for UUID and numeric path segments
```
cd bc_obps
make reset_db
make run
```  
```
```  
3. Click button "Log in with Business BCeID"
4. Sign in to Keycloak using `bc-cas-dev`
5. Navigate to http://localhost:3000/administration/contacts
**Expected Results**   
- `Contacts` displays
- `Add Contact` button displays
6. Click button `Add Contact`
**Expected Results**   
- Contact form in edit mode displays
7. Complete the required form fields. 
8. Click button `Submit` 
**Expected Results**   
- Breadcrumbs displays the value …
=> chore: refactor breadcrumbs for uuid and number

bc_obps/registration/api/v1/e2e_test_setup.py, helm/cas-bciers/templates/backend/job/load-dev-data.yaml, helm/cas-registration/templates/backend/job/load-dev-data.yaml
The test-setup endpoint was truncating tables in the dev environment resulting in losing data that we expected to exist after deploy to dev. Truncating the data should be unnecessary here since we reset the db before deploy.
- Added a load_only boolean to the test-setup endpoint & set it to True in the call from helm
=> chore: update test-setup endpoint with load_only boolean

bciers/apps/administration/app/components/contacts/createContactSchema.ts, bciers/apps/administration/app/components/operations/OperationInformationPage.tsx, bciers/apps/administration/app/components/operators/Operator.tsx, bciers/apps/registration/app/components/operations/registration/FacilityInformationPage.tsx, bciers/apps/registration/app/components/operations/registration/RegistrationPurposePage.tsx, bciers/apps/registration1/app/components/operations/Operation.tsx, bciers/apps/registration1/app/components/userOperators/UserOperator.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user/activities/general_stationary_combustion/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/activities/general_stationary_combustion/page.tsx, bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/operations/OperationReview.tsx, bciers/libs/actions/src/actions.ts, bciers/libs/utils/safeJsonParse.ts
Getting a null or invalid JSON will currently crash the app. safeJsonParse handles the error more gracefully & just returns an empty set.
=> chore: replace all JSON.parse() calls with safeJsonParse

bciers/apps/administration/app/layout.tsx, bciers/apps/administration/app/not-found.tsx, bciers/apps/coam/app/layout.tsx, bciers/apps/coam/app/not-found.tsx, bciers/apps/dashboard/app/layout.tsx, bciers/apps/dashboard/app/not-found.tsx, bciers/apps/registration/app/layout.tsx, bciers/apps/registration/app/not-found.tsx, bciers/apps/reporting/src/app/layout.tsx, bciers/apps/reporting/src/app/not-found.tsx, bciers/libs/components/src/error/NotFound.tsx, bciers/libs/components/src/layout/RootLayout.tsx
#2060 
The metadata in the `RootLayout` wasn't working correctly as it was exporting from that file instead of being exported from the `layout`. 
To test this first run `yarn dev-all` in `develop` and see that the title isn't working:
Checkout this branch and run `yarn dev-all` and now the title is working:
=> chore: fix root layout metadata

bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/app/components/facilities/FacilitiesDataGrid.tsx, bciers/apps/administration/app/components/facilities/FacilityForm.tsx, bciers/apps/administration/app/components/facilities/types.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/registration/tests/components/operations/OperationRegistrationPage.test.tsx, bciers/apps/registration/tests/components/operations/registration/FacilityInformationForm.test.tsx, bciers/apps/registration/tests/components/operations/registration/FacilityInformationPage.test.tsx, docs/frontend/developer-guide.md
Addresses [2088](https://github.com/bcgov/cas-registration/issues/2088)
- Fixes `bciers/apps/administration/app/components/contacts/ContactForm.tsx`  to use PUT on subsequent edits after POST
- Added test `creates a new contact, edits it, and submits the updated contact` in `bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx`
- Fixes `bciers/apps/administration/app/components/facilities/FacilityForm.tsx`  to use PUT on subsequent edits after POST
- Added test `creates a new facility, edits it, and submits the updated facility` in `bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx`
- Fixes `bciers/apps/administration/app/components/facilities/FacilityForm.tsx` replace url in FacilityForm to contain all breadcrumb parameters
- Fixes …
=> Fix new form uses POST on subsequent edit\submit

bc_obps/reporting/api/activity_data.py, bc_obps/reporting/api/reports.py, bc_obps/reporting/fixtures/mock/facility_report.json, bc_obps/reporting/fixtures/mock/report.json, bc_obps/reporting/fixtures/mock/report_version.json, bc_obps/reporting/management/commands/load_reporting_fixtures.py, bc_obps/reporting/schema/facility_report.py, bc_obps/service/activity_service.py, bc_obps/service/report_service.py, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/[version_id]/facilities/[facility_id]/review/page.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReview.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReviewFormData.tsx, bciers/apps/reporting/src/app/components/facility/TaskListElements.ts, bciers/apps/reporting/src/data/jsonSchema/facilities.ts, bciers/apps/reporting/tests/components/FacilityReview.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/195
Added: Review Facility Information Page
Summary of Changes:
Created the ReviewFacilityData component.
Added new API routes:
Fetch facility data for a specific facility_id and report version.
Fetch all activities related to a specific facility_id.
Save facility data.
Updated activity_service to include get_all_activities method.
Updated report_service.
Created report_facility schema.
Added mock fixtures:
report
report_facility
report_version
Added APIs for:
Fetching all activities.
Getting report facility data by facility_id and report version.
Saving report facility data.
Local Testing Instructions:
Navigate to /bc_obps and run:
make reset_db
make run
to apply changes to the database.
Run the frontend using: yarn dev-all
Insert data …
=> Facility Review Information Page

helm/cas-bciers/templates/administration/deployment.yaml, helm/cas-bciers/templates/registration/deployment.yaml
some bad indents made it into a couple deployment yaml files, preventing helm from deploying properly. This should fix it, I tested the deploy with a --dry-run flag.
=> chore: fix indentation in deployment yaml files

bciers/apps/administration/app/page.tsx, bciers/apps/dashboard/app/dashboard/page.tsx, bciers/apps/dashboard/middlewares/withAuthorizationDashboard.test.ts, bciers/apps/dashboard/middlewares/withAuthorizationDashboard.ts, bciers/apps/dashboard/tests/routes/dashboard/page.test.tsx, bciers/package.json
Addresses [2058](https://github.com/bcgov/cas-registration/issues/2058)
- Internal cas user with `cas_pending` role is redirected to common dashboard displaying "pending approval" message.
```
cd bc_obps
make reset_db
make run
```  
```
```  
3.  From terminal  update your idir id to status "Pending"
```
psql
\c registration
UPDATE erc.user SET  app_role_id='cas_pending' WHERE  user_guid='your-guid-here';
```  
3. Click button "Log in with IDIR"
4. Sign in to Keycloak using your IDIR
**Expected Results**   
- Common dashboard with `Pending approval...` displays.
- Bread crumbs display `Dashboard`
- …
=> BCIERS\Dashboard - Internal user, pending approval, sees pending message

bc_obps/reporting/migrations/0010_combustion_for_line_tracing_data.py
One-line fix. Looks like a leftover copy-paste error in the migration
=> chore: 315 - load correct activity schema for gsc line tracing activity

bciers/apps/registration1/app/components/datagrid/DataGrid.tsx, bciers/apps/registration1/tests/components/datagrid/DataGrid.test.tsx, bciers/libs/components/src/datagrid/DataGrid.test.tsx, bciers/libs/components/src/datagrid/DataGrid.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=73893336
This PR:
- fixes bug in both reg1 and 2
- regression test with vitest
To test this, delete rows from database and then look at the data grid in the app.
Happo looks like flake to me, I'll re-run after rebasing/before merging.
=> 2051 fix undefined rows

bciers/apps/administration/app/components/profile/ProfileForm.tsx, bciers/apps/dashboard/app/dashboard/page.tsx, bciers/apps/dashboard/middlewares/withAuthorizationDashboard.test.ts, bciers/apps/dashboard/middlewares/withAuthorizationDashboard.ts, bciers/libs/utils/evalDashboardRules.ts, bciers/libs/utils/isInAllowedList.ts
Addresses [2167](https://github.com/bcgov/cas-registration/issues/2167)
-  Authenticated Internal User, without a user profile,  gets redirected to dashboard with pending message after submitting profile page
```
cd bc_obps
make reset_db
make run
```  
```
```
3. Ensure your user id is not in the db
```
psql
\c registration
DELETE FROM erc.user where user_guid='your-idir-user_guid"
```
2. Click button "Log in with IDIR"
3. Sign in to Keycloak using `your-idir-id`
**Expected results:** 
- Redirection to `http://localhost:3000/administration/profile`
4. Submit profile page
**Expected results:** 
-BCIERS dashboard …
=> 2167 fix bug cas_pending dashboard

bciers/apps/registration1/e2e/workflows/bceidbusiness/industry_user_admin.spec.ts, bciers/apps/registration1/e2e/workflows/idir/cas_admin.spec.ts, bciers/apps/registration1/e2e/workflows/idir/cas_analyst.spec.ts
#2182
Disables Datagrid e2e screenshots since they are very flaky. This won't completely solve our flaky screenshots but should significantly reduce them. There is a reg1 breadcrumb bug occasionally causes flakes: https://github.com/bcgov/cas-registration/issues/2116
Tech debt ticket for flaky Datagrid screenshots: https://github.com/bcgov/cas-registration/issues/2181
=> Disable Datagrid e2e screenshots

shipit.yml
Ignoring the happo check in shipit to avoid blocking automated deploy when snapshots are flaky.
Snapshots would already have been approved in PR review.
=> chore: shipit will ignore Happo 

.github/workflows/main.yaml, .github/workflows/retry-workflow.yaml, .github/workflows/zap-owasp.yaml
#2140 
This method seems to be commonly recommended as a way to re-run workflows on failure:
https://github.com/orgs/community/discussions/67654#discussioncomment-8038649
https://medium.com/@aarne.laur/retry-failed-github-actions-8661e7601c66
https://dev.to/logto/automatically-rerun-your-github-workflow-after-failure-26hi
However I discovered that you can't manually trigger workflows that don't exist yet in the default branch so I get a 404 error:
https://stackoverflow.com/a/78765950
Tried the same command with a workflow that exists in `develop`:
=> 2140 retry owasp zap

.github/workflows/zap-owasp.yaml
#2140
This took me awhile to figure out since the secondary rate limiting error was seemingly causing the job to fail, however it wasn't triggering the `failure()` condition. So after some trial and error I got the retry working well. The `!cancelled()` condition had to be added as the retry workflow was being called if I pushed an update which cancels the in progress pr.
If you want to test this it's pretty easy, though a little time consuming depending on how many tries it takes to trigger the rate limiting error. Just retry the `zap-scan` job. It will fail eventually, then you will see the retry job being called. It will also appear as a second workflow in our Action tab:
After that completes you will see the failed workflow restart:
=> 2140 retry workflow

bc_obps/reporting/json_schemas/2024/gsc_excluding_line_tracing/with_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_excluding_line_tracing/without_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_non_compression_non_combustion/field_gas_process_vent_gas_at_lfo.json, bc_obps/reporting/json_schemas/2024/gsc_non_compression_non_combustion/with_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_non_compression_non_combustion/without_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/field_gas_process_vent_gas_at_lfo.json, bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/with_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/without_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_solely_for_line_tracing/with_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_solely_for_line_tracing/without_useful_energy.json
Add missing field to all gsc fuel fields in the schemas
=> chore: add fuel classification field to gsc fuel fields

bciers/package.json, bciers/yarn.lock
No card, yarn audit CI fail prompted this PR. Updates vite and vitest; if I only update vite there are type errors.
=> chore: upgrade vite and vitest

.sonarcloud.properties, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v2/_operations/test_operation_id.py, bciers/apps/registration/app/components/operations/OperationRegistrationPage.tsx, bciers/apps/registration/app/components/operations/registration/enums.ts, bciers/apps/registration/tests/components/operations/OperationRegistrationPage.test.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=&pane=issue&itemId=76712500
This PR:
- removes the hardcoded "New Entrant" purpose and pulls the purpose (if there is one) from the db instead
- vitest
- endpoint test
- excludes our vitest directory from sonarcloud scan (this PR's tests set off a bunch of duplication warnings)
Note: There's an existing bug with the "Save and Continue" button for LFOs: https://github.com/orgs/bcgov/projects/122/views/2?filterQuery=facility&pane=issue&itemId=79778537. Operation 2 is our only mock LFO, so test with a different mock operation or make your own.
=> Make registration purpose conditional

bc_obps/common/fixtures/dashboard/administration/external.json, bc_obps/common/fixtures/dashboard/bciers/external.json
#2189
Conditionally show the Operations and Users & Access Requests tiles based on the User Operator status. The Users & Access Requests weren't part of this issue though it was suggested to take care of that in this as well.
Make sure to reset the db/load the new fixtures to test:
`make reset_db && make run`
- Log in as `bc-cas-user`
- BCIERS dashboard Administration tile has `Operations` & `Users and access requests` link
- Click `Administration` tile
- Administration dashboard has `Operations` tile & `Users and access requests` tile:
- Log in as `bc-cas-dev-secondary`
- BCIERS dashboard Administration tile does not have `Operations` & `Users and access requests` link
- Click `Administration` tile
-- Administration dashboard does not have `Operations` & `Users and access requests` tile: …
=> 2189 dashboard operations tile

bciers/apps/administration/app/bceidbusiness/industry_user/contacts/[contactId]/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user/contacts/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user/my-operator/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user/operations/[operationId]/facilities/add-facility/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user/operations/[operationId]/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/[contactId]/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/add-contact/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/contacts/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/my-operator/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/operations/[operationId]/facilities/add-facility/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/operations/[operationId]/page.tsx, bciers/apps/administration/app/idir/cas_admin/contacts/[contactId]/page.tsx, bciers/apps/administration/app/idir/cas_admin/contacts/page.tsx, bciers/apps/administration/app/idir/cas_analyst/contacts/[contactId]/page.tsx, bciers/apps/administration/app/idir/cas_analyst/contacts/page.tsx, bciers/apps/registration/app/bceidbusiness/industry_user/register-an-operation/[operation]/[step]/page.tsx, bciers/apps/registration/app/bceidbusiness/industry_user/register-an-operation/page.tsx, bciers/apps/registration/app/bceidbusiness/industry_user_admin/register-an-operation/[operation]/[step]/page.tsx, bciers/apps/registration/app/bceidbusiness/industry_user_admin/register-an-operation/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/facilities/[facility_id]/review/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/review-operator-data/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/facilities/[facility_id]/review/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/review-operator-data/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/page.tsx
=> chore: Wrap routes in suspense wrapper that haven't done so in child data components

.github/workflows/main.yaml, .github/workflows/test-nx-project-e2e.yaml
#2210 
Brianna pointed out that the `happo-skip` helper is failing on merge to main. I believe this is due to us passing in the last commit sha which works for pull requests, but doesn't seem to work here. Rather than debug this I think it's both easier and more safe to just run all e2e on merge so I moved up this issue.
Initially I used `github.event.pull_request.merged == 'true'` though I wanted to ensure this would run both on `develop` and `main` to ensure everything is good before deployment to dev/test.
=> 2210 run all e2e on merge to develop

bc_obps/registration/tests/utils/baker_recipes.py, bc_obps/reporting/api/__init__.py, bc_obps/reporting/api/facility_report.py, bc_obps/reporting/api/reports.py, bc_obps/reporting/tests/api/test_facility_report_api.py, bc_obps/reporting/tests/models/test_report_activity.py, bc_obps/reporting/tests/utils/baker_recipes.py, bc_obps/reporting/tests/utils/bakers.py, bc_obps/service/facility_report_service.py, bc_obps/service/report_service.py, bc_obps/service/tests/test_facility_report_service.py, bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/facilities/[facility_id]/review/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/facilities/[facility_id]/review/page.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReview.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReviewFormData.tsx, bciers/apps/reporting/tests/components/FacilityReview.test.tsx
There were some errors in how facility_id was being applied. 
It was being treated as a numeric where it is a UUID value, which had some cascading effects. 
This PR should fix that up. 
Also cleaned up the API a little bit by splitting out `facility-report` API/service stuff into its own directory & added some tests.
Easiest way to test this:
- Go to dashboard & create a report for Operation 3
- go to /reporting/reports/3/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/review (the facility ID associated with operation 3)
- There should be data in the form fields
- change some data & save
- reload the page
- see the data has changed
=> Chore: facility review fixes

bciers/apps/administration/middlewares/withRulesAppliedAdmin.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/administration/tests/components/operators/OperatorForm.test.tsx, bciers/libs/components/src/form/SingleStepTaskListForm.test.tsx, bciers/libs/components/src/form/SingleStepTaskListForm.tsx, bciers/libs/utils/enums.ts
Addresses [1983](https://github.com/bcgov/cas-registration/issues/1983)
- Updated `Snackbar` to display confirmation message for create action
- Added vitests
```
cd bc_obps
make reset_db
make run
```  
3.  From terminal command, start the app development server:
```
```
3. Sign in to Keycloak using `bc-cas-dev-secondary`
4. Click link `Administration\Select an Operator` 
5. Click link `Add Operator`
6. Compete the form
7. Click button `Submit`
**Expected results:** 
- Form displays snackbar with confirmation message
3. Sign in to Keycloak using …
=> chore: add create confirmation message

bciers/apps/dashboard/auth/auth.config.ts
- Updated auth.config to limit API call to `user-profile` only if token is missing `full_name`
```
cd bc_obps
make reset_db
make run
```  
```
```
3. Verify the `bc_obps` terminal has correct number of calls to `user-profile` from the auth.config 
BEFORE
AFTER
=> chore: update auth.config call to user-profile

bc_obps/reporting/json_schemas/2024/hydrogen_production/feedstock_material_balance_custom.json, bc_obps/reporting/tests/models/program_configuration_tests/test_hydrogen_production_2024.py, bciers/apps/reporting/src/app/components/activities/uiSchemas/hydrogenProduction.ts
card: https://github.com/bcgov/cas-reporting/issues/289
fixed hydrogen production activity page:-
fixed typo: Feedstock
Added "Annual Hydrogen Production" field
Added enum for  "Unit for Annual Feedstock amount"
=> chore:fixed hydrogen production activity page

.sonarcloud.properties, bc_obps/reporting/tests/models/program_configuration_tests/test_carbonates_use_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_fuel_combustion_mobile_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_excluding_line_tracing_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_other_than_non_compression_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_solely_for_line_tracing_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_refinery_fuel_gas_2024.py
Addresses bcgov/cas-reporting#330 | [project link](https://github.com/orgs/bcgov/projects/123/views/1?pane=issue&itemId=78665449). Adds tests for activities that were previously missing. 
- Python tests added for 
- Carbonates Use
- Mobile fuel combustion
- GSC excluding line tracing
- GSC other than non-compression
- GSC solely for line tracing
- Refinery fuel gas
- In the `/bc-obps` directory, start your DB (`make start_pg`) and Django (`make run`).
- Run `make pytest` and ensure tests pass.
=> chore: add missing tests for activities form configs

bc_obps/registration/api/v2/_operations/_operation_id/_registration/operation.py, bc_obps/registration/api/v2/_operations/_operation_id/_registration/submission.py, bciers/apps/registration/app/components/operations/registration/FacilityInformationForm.tsx, bciers/apps/registration/app/components/operations/registration/NewEntrantOperationForm.tsx, bciers/apps/registration/app/components/operations/registration/OperationInformationForm.tsx, bciers/apps/registration/app/components/operations/registration/OperationRepresentativeForm.tsx, bciers/apps/registration/app/components/operations/registration/OptedInOperationForm.tsx, bciers/apps/registration/app/components/operations/registration/RegistrationSubmissionForm.tsx, bciers/apps/registration/tests/components/operations/registration/NewEntrantOperationForm.test.tsx, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx, bciers/apps/registration/tests/components/operations/registration/OperationRepresentativeForm.test.tsx, bciers/libs/components/src/form/MultiStepBase.test.tsx, bciers/libs/components/src/form/MultiStepBase.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=80555060
This PR:
- adds broader error handling to MultiStepBase (previously it was only handling `response.error` errors)
- moved onSubmit error handling from individual form components to MultiStepBase (other error handling, e.g. fetching to populate a dropdown, is still handled in the form components and then the error is passed to MultiStepBase)
- ~move step 1 handling to the MultiStepBase so we don't have to do extra handling in the OperationInformationForm. Step 1 of _any_ workflow will always need to be handled specially because we won't ever have an id before create, but I didn't write a generic case--premature optimization evil and all that~ created new prop for handling step 1
- moves success confirmation …
=> 2256 error handling

bciers/libs/components/src/form/MultiStepBase.test.tsx
More vitests for card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=80555060
I had a test to check that old errors are cleared (code below), but I was having a lot of problems with it (details below) and my timebox ran out, so I've just cut it. I don't think it's a particularly important test because if the errors don't clear, it's only a visual problem. It doesn't affect form submission. 
Problems:
- if you run push up the up the other tests, CI is fine. Add the old errors test, fail. Remove the old errors test, STILL fail.
- one time got an actual error log. But every other time just got:
- code for the haunted test:
```
it("clear old errors", () => {
render(
<MultiStepBase
{...defaultProps}
disabled={false}
step={2}
schema={{
...testSchema,
title: "page2",
}} …
```
=> test: test error handling

bc_obps/reporting/json_schemas/2024/hydrogen_production/feedstock_material_balance_custom.json, bc_obps/reporting/migrations/0018_pulp_and_paper_production.py, bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_other_than_non_compression_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_gsc_solely_for_line_tracing_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_hydrogen_production_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_pulp_and_paper_production_2024.py, bc_obps/reporting/tests/models/program_configuration_tests/test_refinery_fuel_gas_2024.py, bciers/apps/reporting/next-env.d.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscOtherThanNonCompression.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/hydrogenProduction.ts
- Fix ui schemas I missed when adding the fuelType object to the schemas (GSC other than non-compression)
- Remove extraneous fields from pulp & paper methodologies for CO2
- Harmonize "Feedstocks" to be one word & capitalized consistently
- Fix copy-paste errors in test names
=> Chore: minor schema fixes

bc_obps/registration/api/v2/_operations/_operation_id/_registration/operation.py, bc_obps/registration/api/v2/_operations/_operation_id/_registration/submission.py, bc_obps/registration/schema/v1/operation.py, bc_obps/registration/tests/endpoints/v1/_operations/_operation_id/test_operation_update_status.py, bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/_registration/test_submission.py, bc_obps/registration/tests/utils/baker_recipes.py, bc_obps/service/operation_service_v2.py, bc_obps/service/tests/test_operation_service_v2.py, bciers/apps/registration/app/components/operations/registration/RegistrationSubmissionForm.tsx, bciers/apps/registration/tests/components/operations/registration/RegistrationSubmissionForm.test.tsx
card: https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=72007934
This PR:
- creates a service to only update the operation status if all the criteria are met
- lots of pytests
- bakers and helper functions for pytests
- design doesn't want an error shown on the FE (see the card's comments), so all I've done there is not show the confirmation message
- ^vitest for this
To test this PR, you can delete a bunch of the mock operation's data so it no longer meets the criteria. Or, create a new operation and edit the URL to go to the last page without filling out all the steps.
@Sepehr-Sobhani , I put in all the revisions and started updating the API tests but didn't finish. I also haven't done a manual check. -> Sep: ✅
=> Registration status

bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx, bciers/apps/registration1/app/components/form/MultiStepFormBase.test.tsx, bciers/libs/components/src/form/widgets/FileWidget.test.tsx, bciers/libs/components/src/form/widgets/MultiSelectWidget.test.tsx, bciers/libs/components/src/form/widgets/URLWidget.test.tsx
[ISSUE 2329](https://github.com/bcgov/cas-registration/issues/2329)
**NOTE:**
There is an issue with the "should allow clearing the combo box" test in the MultiSelectWidget.test file. It works fine when tested manually, but it seems like there is a problem with the props being passed to the widget itself. The test passes in the browser. This issue is captured in the following ticket: https://github.com/bcgov/cas-registration/issues/2365
=> 2329 add await to waitFor and UserEvent

bciers/package.json, bciers/yarn.lock
We are using the new yarn audit feature so we no longer need this package.
=> Remove unused improved-yarn-audit package

bc_obps/reporting/json_schemas/2024/carbonates_use/carbonates_use.json, bc_obps/service/form_builder_service.py, bciers/apps/reporting/src/app/components/activities/uiSchemas/carbonatesUseUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/fuelCombustionMobileUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscOtherThanNonCompression.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/hydrogenProduction.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/pulpAndPaperUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/refineryFuelGasUiSchema.ts
Card = reporting [#353](https://github.com/bcgov/cas-reporting/issues/353)
- Updated form_builder_service to have methodology field/data nested inside its own object
- Updated carbonates_use.json : removed methodology fields from the schema as it is getting added by the form builder
- Updated activity uiSchemas to account for the new schema structure. Also addressed errors that were showing from some fuelTypes fields not matching between schema and uiSchema.
To test locally: Go to -> http://localhost:3000/reporting/reports/6/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/review and make sure that the relevant existing activities are selected:
- ALL activities dealing with ```General stationary combustion```
- ```Fuel combustion by mobile equipment```
- ```Carbonate use```
- ```Hydrogen …
```
=> 353 methodology fields not flat with emission

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx
The formState was being persisted when navigating to different activity pages.
The dependency array for the useEffect() was throwing warnings across different activity because it was changing its shape depending on how many source types each activity has.
This PR should fix those issues. Though I think that useEffect() is probably doing too much & we should look into potentially splitting it up into different components. I think the way it is set up currently may have an effect on the [Load data ticket](https://github.com/bcgov/cas-reporting/issues/345)
=> fix: activity form state should not persist when switching activities

bc_obps/registration/api/v1/_facilities/facility_id.py, bc_obps/registration/api/v1/_operations/_operation_id/facilities.py, bc_obps/registration/schema/v1/facility_designated_operation_timeline.py, bc_obps/registration/tests/endpoints/v1/_facilities/test_facility_id.py, bciers/apps/registration/app/components/operations/registration/FacilityInformationForm.tsx, bciers/apps/registration/app/components/operations/registration/FacilityInformationPage.tsx, bciers/apps/registration/app/components/operations/registration/RegistrationSubmissionForm.tsx
[ISSUE 2349](https://github.com/bcgov/cas-registration/issues/2349)
[ISSUE 2336](https://github.com/bcgov/cas-registration/issues/2336)
[ISSUE 2354](https://github.com/bcgov/cas-registration/issues/2354)
=> Fix operation registration back navigation

bciers/apps/administration/app/components/operators/OperatorForm.tsx, bciers/apps/administration/app/components/profile/ProfileForm.tsx, bciers/apps/administration/tests/components/helpers/mockUseSession.ts, bciers/apps/administration/tests/components/operators/OperatorForm.test.tsx, bciers/apps/administration/tests/components/operators/OperatorPage.test.tsx, bciers/apps/administration/tests/components/userOperators/SelectOperatorPage.test.tsx, bciers/apps/dashboard/auth/auth.config.ts, bciers/apps/registration1/app/components/users/UserForm.tsx
Addresses [2383](https://github.com/bcgov/cas-registration/issues/2383)
- modified `bciers/apps/dashboard/auth/auth.config.ts` to conditionally update token if triggered by "update"
- modified `bciers/apps/administration/app/components/operators/OperatorForm.tsx` to call session token update on create
- modified legacy calls to update() to be  await update({ trigger: "update" });
- modified vitests for `bciers/apps/administration/tests/components/operators/OperatorForm.test.tsx`
```
cd bc_obps
make reset_db
make run
```  
```
```
3. Sign in to Keycloak using …
=> 2383 session token update

bciers/apps/administration/app/bceidbusiness/industry_user/select-operator/(request-access)/confirm/[id]/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user/select-operator/(request-access)/received/[step]/[id]/page.tsx, bciers/apps/administration/app/components/operators/OperatorForm.tsx, bciers/apps/administration/app/components/operators/OperatorPage.tsx, bciers/apps/administration/app/components/operators/getOperator.ts, bciers/apps/administration/app/components/userOperators/SelectOperatorConfirmPage.tsx, bciers/apps/administration/app/components/userOperators/SelectOperatorReceivedPage.tsx, bciers/apps/administration/app/idir/cas_admin/operators/[operatorId]/page.tsx, bciers/apps/administration/app/idir/cas_admin/operators/user-operator/[id]/[formSection]/page.tsx, bciers/apps/administration/app/idir/cas_analyst/operators/user-operator/[id]/[formSection]/page.tsx, bciers/apps/administration/tests/components/operators/OperatorForm.test.tsx, bciers/apps/administration/tests/components/operators/OperatorPage.test.tsx
Partially addresses: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=80445876&issue=bcgov%7Ccas-registration%7C1700
This PR:
- deletes placeholder files
- creates the internal view of the operator form (readonly, no edit button)
- types operatorId as a uuid instead of a string
- setting up the routing is blocked by #1699, so will leave #1700 open but blocked. Once 1699 is complete, will do another PR to hook everything together
Happo looks like flake to me
=> 1700 internal operator page

bc_obps/reporting/json_schemas/2024/carbonates_use/carbonates_use.json, bc_obps/reporting/json_schemas/2024/open_pit_coal_mining/activity.json, bc_obps/reporting/json_schemas/2024/open_pit_coal_mining/coal_exposed_during_mining.json, bc_obps/reporting/json_schemas/2024/open_pit_coal_mining/emission_factor_methodology_custom.json, bc_obps/reporting/migrations/0008_prod_data.py, bc_obps/reporting/migrations/0022_open_pit_coal_mining.py, bc_obps/reporting/migrations/0024_open_pit_coal_mining.py, bc_obps/reporting/tests/models/program_configuration_tests/test_open_pit_coal_mining.py, bc_obps/reporting/tests/models/test_methodology.py, bciers/apps/reporting/src/app/components/activities/uiSchemas/carbonatesUseUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/hydrogenProduction.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/openPitCoalMining.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/schemaMaps.tsx
Card: https://github.com/bcgov/cas-reporting/issues/339
Changes:-
- Adds backend config/migration for Open Pit coal mining activity.
- Adds frontend page and components for Open Pit coal mining activity.
- Added components for activity-specific pages and dynamic field rendering.
- Fixed typo(Emission and Equivalent Emission in Hydrogen Production and Carbonates use)
To test:-
- make reset_db to apply latest migrations.
- spin up the front, backend and postgres.
- Login, then navigate to http://localhost:3000/reporting/reports , select operation 3 -> press save and continue to go to review Facilities page-> select Open pit coal mining(from the list of activities) and press save & continue. 
- The Gas type dropdown options should change options available in the methodology field.
- The …
=> activity page- Open Pit Coal Mining

bc_obps/common/fixtures/dashboard/bciers/internal.json, bc_obps/common/fixtures/dashboard/registration/internal.json, bc_obps/common/fixtures/dashboard/registration/internal_admin.json
Ticket #2405 
feat: replaced Registration tile in BCIERS dashboard with Transfers (for internal users only)
Notes:
- renamed the "Registration" tile to "Transfers"
- replaced links in tile with links to view Transfers grid and to create a new transfer (these pages don't exist yet, so the links just take you to an error page)
- note that breadcrumb still includes "Registration" (consistent with wireframe)
- sign in to BCIERS with your IDIR
- (you may have to update your user profile first)
- with a user role of either cas_analyst or cas_admin, go to the main BCIERS dashboard
- should see this:
=> "Transfers" tile in BCIERS dashboard for internal users

bc_obps/reporting/migrations/0008_prod_data.py, bc_obps/reporting/migrations/0009_general_stationary_combustion_data.py, bc_obps/reporting/migrations/0010_combustion_for_line_tracing_data.py, bc_obps/reporting/migrations/0011_mobile_combustion_data.py, bc_obps/reporting/migrations/0012_gsc_other_than_non_compression.py, bc_obps/reporting/migrations/0013_refinery_fuel_gas_data.py, bc_obps/reporting/migrations/0014_carbonates_use.py, bc_obps/reporting/migrations/0015_gsc_non_compression_non_processing.py, bc_obps/reporting/migrations/0017_hydrogen_production.py, bc_obps/reporting/migrations/0018_pulp_and_paper_production.py, bc_obps/reporting/migrations/0024_open_pit_coal_mining.py, docs/frontend/activity-form-development-guide.md
Our form builder service was not finding a valid configuration after the changes in #2384 because valid_from will always be after the current report date until 2025. We can undo this change if we want to in January as the "2024" configuration now starts in 2023.
=> chore: change config.valid_from to 2023-01-01

bc_obps/common/tests/endpoints/auth/test_endpoint_permissions.py, bc_obps/registration/api/v1/_facilities/_facility_id/bcghg_id.py, bc_obps/registration/api/v2/_operations/_operation_id/bcghg_id.py, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v1/_facilities/_facility_id/test_facility_bcghg_id.py, bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/test_bcghg_id.py, bc_obps/registration/tests/utils/baker_recipes.py, bc_obps/service/facility_service.py, bc_obps/service/operation_service_v2.py, bc_obps/service/tests/test_facility_service.py, bc_obps/service/tests/test_operation_service_v2.py
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=80445811&issue=bcgov%7Ccas-registration%7C2152
This PR:
- creates services to issue a BCGHG ID
- tests the services and endpoints
- updates mock data so Operation 3 doesn't have a BCGHG ID
Notes:
- We don't have an internal facility page yet, so we're only able to test the "Issue BCGHG ID" button for operations. I've made a note in the internal facility page ticket to test the button at that point.
=> 2151 issue bcghgid service

bc_obps/common/tests/endpoints/auth/test_endpoint_permissions.py, bc_obps/registration/api/v2/_operations/_operation_id/_registration/operation_representative.py, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/_registration/test_operation_representative.py, bc_obps/service/operation_service_v2.py, bc_obps/service/tests/test_operation_service_v2.py, bciers/apps/registration/app/components/operations/registration/NewOperationRepresentativeForm.tsx, bciers/apps/registration/app/data/jsonSchema/operationRegistration/operationRepresentative.ts, bciers/apps/registration/tests/components/operations/registration/NewOperationRepresentativeForm.test.tsx, bciers/libs/components/src/form/theme/readOnlyTheme.ts, bciers/libs/components/src/form/widgets/OperationRepresentativeWidget.tsx, bciers/libs/components/src/form/widgets/index.ts, bciers/libs/components/src/form/widgets/readOnly/OperationRepresentativeWidget.test.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=81400225&issue=bcgov%7Ccas-registration%7C2299
This PR:
- new widget for operation reps
- vitests^
- new endpoint to remove a rep
- pytests^
I wasn't sure what to return from the endpoint since we don't need anything. I tried to return nothing (suggestions for something better?), but I'm getting {id: None}/{id: null} for some reason.
=> 2299 remove op rep

bc_obps/Dockerfile
The poetry version defined in the path of the Dockerfile drifted from what was defined in .tool-versions. This will get the version from .tool-versions to avoid this in the future.
=> chore: programatically get poetry version from file to avoid drift

helm/cas-bciers/templates/_helpers.tpl, helm/cas-bciers/templates/backend/deployment.yaml, helm/cas-registration/templates/_helpers.tpl, helm/cas-registration/templates/backend/deployment.yaml
I think there's also an issue with the superuser being in an init container & how we drop our database beforehand (which means the django auth admin tables don't exist).
This PR is just to fix the side effect of having envs in test/prod that reference a secret that isn't created in those environments, causing a container init config error on deploy. I created a stand-in secret in test to get around that for now. This PR makes those envs conditional on the dev environment.
=> chore: conditionally add superuser envs

bc_obps/common/fixtures/dashboard/bciers/external.json, bc_obps/common/fixtures/dashboard/registration/external.json
Reminder to devs when running this locally to test - you have to `make reset_db` for the updated tiles to take effect. Just adding this as a reminder because I consistently forget and then get confused why it isn't working.
**Registration dashboard:**
I updated the tile descriptions to match the updated wireframes, and set the Report an Event tile to always be hidden for the time being, since this page won't be available to external users as part of Reg2 MVP.
**Main dashboard:**
Hid the link to Report an Event from the "Registration" tile (for the same reason as above).
=> Task/update tile titles registration external user/2350

bciers/apps/administration/app/components/facilities/FacilityForm.tsx, bciers/apps/administration/app/data/jsonSchema/facilitiesLfo.ts, bciers/apps/administration/app/data/jsonSchema/facilitiesSfo.ts, bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/registration/tests/components/operations/registration/FacilityInformationForm.test.tsx
card: https://github.com/bcgov/cas-registration/issues/2269
This PR:
- makes the default readonly province British Columbia
- updates vitests
Happo diffs are flake
=> 2269: make facility province readonly BC

bciers/apps/administration/app/components/userOperators/cells/ActionColumnCell.tsx, bciers/apps/administration/tests/components/userOperators/AccessRequestDataGrid.test.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=80445874&issue=bcgov%7Ccas-registration%7C1716
This PR:
- adds a snackbar that shows anytime a user's access has changed
- changed the "Undo" button text to "Edit"
- vitests
=> 1719: add snackbar to external user access grid

bc_obps/common/fixtures/dashboard/administration/internal.json, bc_obps/common/fixtures/dashboard/administration/internal_admin.json, bc_obps/common/fixtures/dashboard/bciers/internal.json, bc_obps/common/tests/endpoints/auth/test_endpoint_permissions.py, bc_obps/registration/admin.py, bc_obps/registration/api/v2/user_operators.py, bc_obps/registration/fixtures/mock/admin/user_operator.json, bc_obps/registration/fixtures/mock/admin/user_operator_approved.json, bc_obps/registration/fixtures/mock/user_operator.json, bc_obps/registration/schema/v2/user_operator.py, bc_obps/registration/tests/endpoints/v2/test_user_operators.py, bc_obps/service/data_access_service/user_operator_service.py, bc_obps/service/error_service/handle_exception.py, bc_obps/service/tests/data_access_service/test_data_access_user_operator_service.py, bc_obps/service/tests/test_user_operator_service_v2.py, bc_obps/service/user_operator_service_v2.py, bciers/apps/administration/app/components/datagrid/models/userOperators/userOperatorColumns.ts, bciers/apps/administration/app/components/datagrid/models/userOperators/userOperatorGroupColumns.ts, bciers/apps/administration/app/components/userOperators/UserOperatorDataGrid.tsx, bciers/apps/administration/app/components/userOperators/UserOperatorsPage.tsx, bciers/apps/administration/app/components/userOperators/cells/UserOperatorStatusCell.tsx, bciers/apps/administration/app/components/userOperators/getUserOperatorsPageData.ts, bciers/apps/administration/app/components/userOperators/types.ts, bciers/apps/administration/app/idir/cas_admin/operator-administrators-and-access-requests/page.tsx, bciers/apps/administration/app/idir/cas_analyst/operator-administrators-and-access-requests/page.tsx, bciers/apps/administration/tests/components/userOperators/UserOperatorDataGrid.test.tsx, bciers/apps/administration/tests/components/userOperators/UserOperatorsPage.test.tsx, bciers/libs/testConfig/src/mocks.ts
[ISSUE 2160](https://github.com/bcgov/cas-registration/issues/2160)
**NOTE:**
- Updated the dashboard tiles and removed unnecessary ones.
- Added user operator tables to allow internal users to view access requests.
- Improved the data in the grid by updating the fixtures.
- Additionally, modified the Django admin tables for user and user-operator data models to enhance their usability.(non-related)
**TEST:**
Log in as an internal user. Click the Operator Administrators and Access Requests tile to view the data grid.
=> 2160 internal user can view access requests

bc_obps/common/management/commands/load_fixtures.py, bc_obps/common/tests/endpoints/auth/test_endpoint_permissions.py, bc_obps/registration/api/v2/_operations/_operation_id/_registration/operation.py, bc_obps/registration/fixtures/mock/multiple_operator.json, bc_obps/registration/fixtures/mock/operation.json, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v2/_operations/_operation_id/_registration/test_operation.py, bciers/apps/administration/app/data/jsonSchema/operationInformation/operationInformation.ts, bciers/apps/administration/tests/components/operations/OperationDataGrid.test.tsx, bciers/apps/registration/app/components/operations/registration/OperationInformationForm.tsx, bciers/apps/registration/app/components/operations/registration/OperationInformationPage.tsx, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx, bciers/libs/actions/src/api/getOperationRegistration.ts, bciers/libs/actions/src/api/getRegistrationPurposes.ts, bciers/libs/actions/src/api/index.ts, bciers/libs/components/src/datagrid/cells/operations/OperationsActionCell.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=80782303&issue=bcgov%7Ccas-registration%7C2270
This PR:
- fixes the links on the operation grid so they go to the right places (admin views, or beginning of reg flow)
- updates mock data to create an in-progress operation (Operation 5) with multiple operators (I was suspicious that the schema wasn't properly fetching multiple operators)
- if a registration is in progress, fetches existing data and pre-fills the first page of the form. Currently can't fetch registration purpose because there are multiple; this will be fixed in Andrea's PR. We can't fetch docs in our mock data because GCS isn't set up for CI
- This PR doesn't include a put route, so if you "continue" Operation 5, you're actually creating a new …
=> 2270 operation grid link

bc_obps/registration/fixtures/mock/operation.json, bc_obps/registration/models/operation.py, bc_obps/registration/tests/endpoints/v1/_operations/_operation_id/test_operation_update_status.py, bc_obps/registration/tests/models/test_operation.py, bc_obps/service/operation_service_v2.py, bc_obps/service/tests/test_operation_service_v2.py, bciers/apps/administration/app/components/operations/OperationInformationForm.tsx, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/registration/app/components/operations/registration/enums.ts, bciers/libs/components/src/form/widgets/BoroIdWidget.test.tsx, bciers/libs/components/src/form/widgets/BoroIdWidget.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=86401827&issue=bcgov%7Ccas-registration%7C2453
This PR:
- conditionally shows the boro id widget button only for regulated operations
- backend conditions on not creating boro ids for non-regulated operations
- updated mock data so we have Operation 19 eligible for BORO ID (needs to be registered and have an appropriate purpose)
- updated vitests and pytest
=> 2453 boro id restrictions

bciers/apps/registration/app/data/jsonSchema/operationInformation/registrationPurpose.ts, bciers/apps/registration/tests/components/operations/OperationRegistrationPage.test.tsx, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=82482715&issue=bcgov%7Ccas-registration%7C2337
This PR:
- conditionally show the regulated products dropdown based on whether the purpose is in the regulated operations array
- regression test
=> 2337 fix reg products

bciers/apps/reporting/src/data/jsonSchema/personResponsibleInfoText.tsx
Card: N/A
A quick PR , so that when user clicks on contact on Person Responsible page, it opens it in a new tab.
=> chore: added contact page to open in new tab

bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/facilities/[facility_id]/activities/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/facilities/[facility_id]/activities/page.tsx, bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/activities/ActivityInit.tsx, bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx, bciers/apps/reporting/src/app/components/facility/FacilityEmissionSummary.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReview.tsx, bciers/apps/reporting/src/app/components/operations/OperationReview.tsx, bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx, bciers/apps/reporting/src/app/components/products/ProductionDataForm.tsx, bciers/apps/reporting/src/app/components/reportInformation/nonAttributableEmissions/NonAttributableEmissionsForm.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx, bciers/apps/reporting/src/app/components/taskList/2_facilitiesInformation.ts, bciers/apps/reporting/src/app/components/verification/VerificationForm.tsx, bciers/apps/reporting/src/tests/components/additionalInformation/AdditionalReportingData.test.tsx, bciers/apps/reporting/src/tests/components/operations/OperationReview.test.tsx, bciers/apps/reporting/src/tests/components/operations/personResponsible/PersonResponsible.test.tsx, bciers/apps/reporting/src/tests/components/reportInformation/NonAttributableEmissions.test.tsx, bciers/apps/reporting/src/tests/verification/VerificationForm.test.tsx, bciers/libs/components/src/form/MultiStepFormWithTaskList.test.tsx, bciers/libs/components/src/form/MultiStepFormWithTaskList.tsx, bciers/libs/components/src/form/components/ReportingStepButtons.test.tsx, bciers/libs/components/src/form/components/ReportingStepButtons.tsx, bciers/libs/utils/src/serializeSearchParams.ts
-392
To Test:
- Login as bc-cas-dev
- start operation 3 report
- Freely navigate back or Save & Continue through the form
- Buttons should all work and disable if the page is read only, they should be at the bottom and change display based on saving state or redirecting state
- *Note: allocation of emissions page is not completed at the time of submitting this PR
=> 392 button tech debt

bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/sign-off/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/sign-off/page.tsx, bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx, bciers/apps/reporting/src/app/components/attachments/AttachmentsForm.tsx, bciers/apps/reporting/src/app/components/complianceSummary/ComplianceSummary.tsx, bciers/apps/reporting/src/app/components/datagrid/models/operations/operationColumns.tsx, bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReview.tsx, bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx, bciers/apps/reporting/src/app/components/operations/OperationReview.tsx, bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx, bciers/apps/reporting/src/app/components/products/ProductionDataForm.tsx, bciers/apps/reporting/src/app/components/reportInformation/nonAttributableEmissions/NonAttributableEmissionsForm.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx, bciers/apps/reporting/src/app/components/verification/VerificationForm.tsx, bciers/apps/reporting/src/data/jsonSchema/facility/facilityEmissionAllocation.tsx, bciers/apps/reporting/src/tests/components/additionalInformation/AdditionalReportingData.test.tsx, bciers/apps/reporting/src/tests/components/attachments/AttachmentsForm.test.tsx, bciers/apps/reporting/src/tests/components/complianceSummary/ComplianceSummary.test.tsx, bciers/apps/reporting/src/tests/components/dataGrid/model/operations/operationColumns.test.tsx, bciers/apps/reporting/src/tests/components/operations/OperationReview.test.tsx, bciers/apps/reporting/src/tests/components/products/ProductionDataForm.test.tsx, bciers/apps/reporting/src/tests/components/reportInformation/NonAttributableEmissions.test.tsx, bciers/libs/components/src/form/MultiStepWrapperWithTaskList.test.tsx, bciers/libs/components/src/form/MultiStepWrapperWithTaskList.tsx, bciers/libs/components/src/form/components/ReportingStepButtons.tsx
#2570
- fix: Fix reporting step buttons on attachments and allocation pages
- test: update tests after reporting step buttons update
```
cd bc_obps
make reset_db
make run
```  
```
```  
1. Navigate to http://localhost:3000
3. Navigate to http://localhost:3000/reporting/reports
- Reporting grid displays with rows having action buttons `Start` or  `Continue`
5. Click `Operator 3` row button `Start`
- Url does NOT display any query parameters  such as`..?reports_title=...1
- Router navigates to form: `Review operation information` 
- Form has buttons: `Back`; `Save`; `Save …
=> reporting buttons fixes

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx
Card: https://github.com/bcgov/cas-reporting/issues/439
Changes:- fixed url for buildSchema 
Since we were using join and when use .join() without a separator, the default separator is a comma (,), so adding a separator.
=> chore:fixed activity page bug

bc_obps/registration/fixtures/mock/operator.json
Is this going to break reg1 tests? No!
This PR changes some of the mock data operator's statuses to `Approved`. In reg2 all operators will be approved by default the moment they're created. However, the reg1 tests require some operators to be unapproved, so we have to leave some of the data in the old structure for them to pass.
=> chore: update operator mock data

.github/workflows/test-nx-project-e2e.yaml, .github/workflows/test-registration1-e2e.yaml, docs/developer-environment-setup.md, docs/frontend/testing/playwright.md, docs/frontend/testing/vitest.md
Removes the --with-deps flag when installing playwright in CI. This appears to have fixed the `libasound2` error on install
Relevant github issue: https://github.com/microsoft/playwright/issues/30368
=> test: playwright failures

bc_obps/common/tests/endpoints/test_openapi_docs.py, bc_obps/reporting/api/report_activity.py
[ISSUE 2619](https://github.com/bcgov/cas-registration/issues/2619)
=> 2619 fix api docs

bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx
card: https://github.com/bcgov/cas-reporting/issues/468
The problem: This bug was due to a precision issue. During testing, a user had all emissions showing as 100% allocated, but was prevented from saving by a validation error indicating an incorrect allocation. In fact, the validation was working as intended. There was an over-allocation of emissions. BUT the amount over was .000049% of the total. And because the percentage display only uses 2-digit precision, it still showed as just 100.00%.
The fix: This problem really only exists for values that are very slightly off 100%. If it is more substantially off, then it would not show 100.00% and the problem allocation would be obvious. So i have added some edge case handling. For values that are >100 and <100.01, display 100.01. And for …
=> Fix emission allocation bugs identified in UAT

bciers/apps/administration/app/components/contacts/createContactSchema.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/registration/app/data/jsonSchema/operationInformation/registrationPurpose.ts, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
[ISSUE 2624](https://github.com/bcgov/cas-registration/issues/2624)
=> fix: populate anyOf only if we have options

bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/app/components/contacts/ContactPage.tsx, bciers/apps/administration/app/data/jsonSchema/contact.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/libs/components/src/form/fields/ArrayFieldTemplate.tsx
[ISSUE 2563](https://github.com/bcgov/cas-registration/issues/2563)
=> 2563 users should not be able to add places assigned on the contacts form

bciers/apps/administration/app/bceidbusiness/industry_user/contacts/add-contact/page.tsx, bciers/apps/administration/app/components/contacts/ContactPage.tsx, bciers/apps/administration/app/components/contacts/ContactsPage.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=91260610&issue=bcgov%7Ccas-registration%7C2605
This PR:
- adds a `page.tsx` for add-contacts for the industry_user (reporter) role
- removes conditionality that only allowed admin industry users to add contacts
=> chore: give industry_user create access to contacts

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx, bciers/apps/reporting/src/app/components/additionalInformation/newEntrantInformation/NewEntrantInformation.tsx, bciers/apps/reporting/src/app/components/additionalInformation/newEntrantInformation/NewEntrantInformationForm.tsx, bciers/apps/reporting/src/app/components/complianceSummary/ComplianceSummaryForm.tsx, bciers/apps/reporting/src/app/components/complianceSummary/ComplianceSummaryPage.tsx, bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx, bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx, bciers/apps/reporting/src/app/components/operations/OperationReview.tsx, bciers/apps/reporting/src/app/components/operations/personResponsible/PersonResponsible.tsx, bciers/apps/reporting/src/app/components/operations/personResponsible/createPersonResponsibleSchema.ts, bciers/apps/reporting/src/app/components/products/ProductionDataForm.tsx, bciers/apps/reporting/src/app/components/reportInformation/nonAttributableEmissions/NonAttributableEmissionsForm.tsx, bciers/apps/reporting/src/app/components/reportInformation/nonAttributableEmissions/NonAttributatbleEmissions.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx, bciers/apps/reporting/src/app/components/taskList/1_operationInformation.ts, bciers/apps/reporting/src/app/components/taskList/3_additionalInformation.ts, bciers/apps/reporting/src/app/components/taskList/4_complianceSummary.ts, bciers/apps/reporting/src/app/components/verification/VerificationForm.tsx, bciers/apps/reporting/src/tests/components/complianceSummary/ComplianceSummaryPage.test.tsx, bciers/apps/reporting/src/tests/components/reportInformation/NonAttributableEmissions.test.tsx, bciers/libs/components/src/form/MultiStepFormWithTaskList.tsx, bciers/libs/components/src/form/MultiStepWrapperWithTaskList.tsx, bciers/libs/components/src/form/NavigationForm.tsx, bciers/libs/components/src/form/components/ReportingStepButtons.tsx
- Fixes the forms holding onto errors and prevending resubmissions when the server returned an error once.
- Refactored the navigation logic in a `NavigationForm` component, to avoid having to implement the funky `useEffect` everywhere it's needed
- Updated the various forms to do display server errors
- `submitHandler` needs to return a boolean to indicate whether the submission succeeded, server-side
Fixes:
- #461 the facility item improperly showing up on the operation review task list
=> Fix: form submit blocked after error

bc_obps/registration/api/v2/contacts.py, bc_obps/registration/schema/v2/contact.py, bc_obps/registration/tests/utils/baker_recipes.py, bc_obps/service/contact_service_v2.py, bc_obps/service/tests/data_access_service/test_data_access_contact_service.py, bc_obps/service/tests/test_contact_service_v2.py, bciers/apps/administration/app/components/contacts/ContactsDataGrid.tsx, bciers/apps/administration/app/components/contacts/types.ts, bciers/apps/administration/app/components/datagrid/models/contacts/contactColumns.ts, bciers/apps/administration/app/components/datagrid/models/contacts/contactGroupColumns.ts, bciers/apps/administration/tests/components/contacts/ContactsDataGrid.test.tsx, bciers/libs/components/src/datagrid/DataGrid.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=88763967&issue=bcgov%7Ccas-registration%7C2525
This PR:
- Puts the operator in the contacts grid. It's a m2m field so I've used the same strategy with `distinct` as we used in the transfers grid
- Enabled sorting and filtering for this colu,n--I didn't see any reason not to
- add more readable names to the baker recipes to help me debug, and I left them because they'll probably be helpful in the future too
=> Put operator and operation in contacts grid

bc_obps/common/fixtures/dashboard/administration/external.json, bc_obps/common/fixtures/dashboard/bciers/external.json, bciers/apps/administration/app/bceidbusiness/industry_user/transfers/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/transfers/page.tsx, bciers/apps/administration/app/components/transfers/ExternalTransferPage.tsx, bciers/apps/administration/tests/components/transfers/ExternalTransferPage.test.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=83628015&issue=bcgov%7Ccas-registration%7C2374
This PR:
- creates a page.tsx for both industry_user and industry_user admin
- adds links to the dashboard that are only accessible once a user is approved
- creates the transfers info page
- vitest for the transfers page
=> 2374 transfer instructions

bciers/libs/components/src/navigation/Bread.test.tsx, bciers/libs/components/src/navigation/Bread.tsx
Ticket [352](https://github.com/bcgov/cas-reporting/issues/352)
- Filter out App specific crumb via path segment transformation based on App pathnames  and crumb name-"Reports\\...\Facilities\\..."
```
cd bc_obps
make reset_db
make run
```  
```
```  
**Test for "Facilities" crumb in Nx Apps**
1. Navigate to http://localhost:3000
3. Navigate to **ADMIN App Facilities** route: http://localhost:3000/administration/operations/002d5a9e-32a6-4191-938c-2c02bfec592d/facilities?operations_title=Banana+LFO+-+Registered
- `Facilities` crumb displays in breadcrumbs  
4.  Navigate to **REPORTING App …
=> 352 filter out Report Facilities crumb from breadcrumb component

bc_obps/registration/api/v2/_contacts/contact_id.py, bc_obps/registration/api/v2/_operations/operation_id.py, bc_obps/registration/fixtures/mock/address.json, bc_obps/registration/fixtures/mock/contact.json, bc_obps/registration/fixtures/mock/operation.json, bc_obps/registration/fixtures/mock/operator.json, bc_obps/registration/schema/v2/contact.py, bc_obps/registration/schema/v2/operation.py, bc_obps/registration/tests/endpoints/v2/_contacts/test_contact_id.py, bc_obps/registration/tests/endpoints/v2/_operations/test_operation_id.py, bc_obps/registration/tests/utils/baker_recipes.py, bc_obps/service/contact_service_v2.py, bc_obps/service/operation_service.py, bc_obps/service/operation_service_v2.py, bc_obps/service/tests/test_contact_service_v2.py, bc_obps/service/tests/test_operation_service_v2.py, bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/app/components/operations/OperationInformationForm.tsx, bciers/apps/administration/app/data/jsonSchema/contact.ts, bciers/apps/administration/app/data/jsonSchema/operationInformation/administrationOperationInformation.ts, bciers/apps/administration/app/data/jsonSchema/operationInformation/administrationRegistrationInformation.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/administration/tests/components/contacts/ContactPage.test.tsx, bciers/apps/administration/tests/components/contacts/mocks.ts, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/administration/tests/components/operations/OperationInformationPage.test.tsx, bciers/apps/administration/tests/components/operations/mocks.ts, bciers/libs/components/src/form/fields/PlacesAssignedFieldTemplate.test.tsx, bciers/libs/components/src/form/fields/PlacesAssignedFieldTemplate.tsx, bciers/libs/components/src/form/fields/index.ts
https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=88758186&issue=bcgov%7Ccas-registration%7C2524
Notes: 
- I've used a url param to decide whether or not to show the alert on the contact page. As far as I could find online (e.g. https://medium.com/@awayyao/keep-page-state-between-page-navigation-in-nextjs-13-using-app-router-schema-f6eacd0300ad), the next router doesn't store any state or history. window.history doesn't store the previous url, and document.referer only gives the origin.
- Updated the mock data so that contacts are more representative of how the app works (e.g., operations can only have contacts that belong to their operators; all registered operations have to have a contact)
- because of ^, I noticed you can get to the operation administration page …
=> Replace operation rep

bc_obps/registration/schema/v2/contact.py, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/libs/components/src/form/fields/PlacesAssignedFieldTemplate.tsx
card: https://github.com/bcgov/cas-registration/issues/2524#issuecomment-2617049496
This PR:
- the contact page was throwing an error because places_assigned in the ninja schema is optional but didn't have a default value, added the default
- fixed the space in the places assigned widget when no places are assigned
=> 2524: fix places assigned display

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx
[518](https://github.com/bcgov/cas-reporting/issues/518)
- fixes activity saving for activities with no sourceType checkbox
=> fix activity saving for activities with no sourceType checkbox (e.g. mobile combustion)

bciers/apps/reporting/src/app/components/facility/FacilityEmissionSummaryForm.tsx, bciers/apps/reporting/src/app/components/facility/FacilityEmissionSummaryPage.tsx, bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/emissionsSummaryFactoryItem.ts, bciers/apps/reporting/src/data/jsonSchema/facilityEmissionSummary.ts, bciers/apps/reporting/src/tests/components/facility/FacilityEmissionSummaryPage.test.tsx
[422](https://github.com/orgs/bcgov/projects/123/views/15?pane=issue&itemId=89929470&issue=bcgov%7Ccas-reporting%7C422)
- **chore: Remove fog and reporting only emission fields from alloc of emissions and emission summary pages**
- **test: update tests for fog and roe**
=> 422 remove fog and reporting only fields

bciers/package.json, bciers/yarn.lock
See https://github.com/vitest-dev/vitest/security/advisories/GHSA-9crc-q9x8-hgqq 
There is a critical security vuln on the version of vitest we were using (although we prob weren't susceptible because we only run vitest on our own website).
Regardless, I've manually updated our vitest version to the latest using `yarn up vitest -i`
=> chore: upgrade vitest to 3.0.5 in response to CVE-2025-24964

bc_obps/reporting/migrations/0039_reportproductemissionallocation_and_more.py, bc_obps/reporting/models/report_product_emission_allocation.py, bc_obps/reporting/tests/models/test_report_product_emission_allocation.py, bc_obps/reporting/tests/service/test_report_emission_allocation_service.py, bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx
Card: https://github.com/bcgov/cas-reporting/issues/507
Updated model to expect 'Other'
Updated tests to use 'Other'
Added test to verify that 'Other' works and 'other' does not
Added validations and errors for methodology and methodology_description fields
=> 507 bug emission allocation fails with other

bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataForm.tsx, bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataPage.tsx, bciers/apps/reporting/src/app/components/additionalInformation/newEntrantInformation/NewEntrantInformationPage.tsx, bciers/apps/reporting/src/app/components/additionalInformation/operationEmissionSummary/OperationEmissionSummaryPage.tsx, bciers/apps/reporting/src/app/components/taskList/3_additionalInformation.ts, bciers/apps/reporting/src/tests/components/additionalInformation/AdditionalReportingData.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/563
Changes: 
1. Added operation type to additional Information tasklist, so that if the operation type is LFO, then only it should show operation emission summary page.
2. Passed operation type from New Entrant, Additional Reporting Data and operation emission summary page.
3. Fixed the test for Additional Reporting Data Form
=> chore: fixed the tasklist for additional Information

bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/field_gas_process_vent_gas_at_lfo.json, bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/with_useful_energy.json, bc_obps/reporting/json_schemas/2024/gsc_other_than_non_compression/without_useful_energy.json, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscOtherThanNonCompression.ts, bciers/libs/utils/src/customReportingActivityFormCalculations.test.ts, bciers/libs/utils/src/customReportingActivityFormCalculations.ts
This PR addresses the latest comment in [464](https://github.com/bcgov/cas-reporting/issues/464):
- **fix: improve mobile fuel annual amount calculator to fix reporting form 0 issues**
- **chore: add fuel description to gsc other than non activity form for dev site test feedback**
=> 464 uat part2

bc_obps/reporting/migrations/0039_reportproductemissionallocation_and_more.py, bc_obps/reporting/models/report_product_emission_allocation.py, bciers/apps/reporting/src/app/components/facility/calculateEmissionsData.ts, bciers/apps/reporting/src/data/jsonSchema/facility/facilityEmissionAllocation.tsx
Card: https://github.com/bcgov/cas-reporting/issues/507 (only the changes under "EDITED TO ADD". Other changes in this ticket have already been implemented)
- Added "Not Applicable" as an option to the Methodology dropdown menu
- Updated the "Calculator" option in the dropdown menu to be "OBPS Allocation Calculator"
- Changed how percentage allocated is displayed when the **_total emissions of a category are 0._**
- When 0 emissions are allocated: shows 100% (Changed from 0%). This makes it so that the good state is always 100%. When moving through each emission category, if it says 100% then it is good.
- When *ANY* emissions are allocated, shows '-99.99%'. This is (i hope) clearly an ERROR amount and, coupled with the error message ('all emissions must be allocated to 100%'), should …
=> 507 part2 allocation of emissions alterations

bc_obps/reporting/api/facility_report.py, bc_obps/reporting/json_schemas/2024/electricity_generation/1_fuel_combustion_electricity_gen.json, bc_obps/reporting/json_schemas/2024/electricity_generation/activity.json, bc_obps/reporting/migrations/0061_electricity_generation.py, bc_obps/reporting/service/report_facilities_service.py
Card: https://github.com/bcgov/cas-reporting/issues/564
Changes: 
sorted facilities by facility_name
To test:-
1. Login vi BCeId
2. Select an LFO operation on reports table and navigate to review facilties, you will see all the facilities sorted alphabetically like http://localhost:3000/reporting/reports/2/facilities/review-facilities-list
3. Navigate to http://localhost:3000/reporting/reports/2/facilities/report-information
=> chore: sorted facilities alphabetically

bc_obps/reporting/fixtures/mock/report.json
Stopgap until this ticket gets picked up: https://github.com/bcgov/cas-reporting/issues/378
Fixes our dev data by including a created_at value for the mock reports in the dev fixtures.
=> chore: add created_at values to mock report fixtures

bciers/apps/reporting/src/app/components/datagrid/models/facilities/getFacilityColumns.tsx, bciers/apps/reporting/src/app/components/datagrid/models/operations/operationColumns.tsx, bciers/apps/reporting/src/app/components/operations/cells/ActionCell.tsx, bciers/apps/reporting/src/app/components/operations/cells/MoreActions.tsx, bciers/apps/reporting/src/app/components/operations/cells/ReportingOperationStatusCell.tsx, bciers/apps/reporting/src/tests/components/dataGrid/model/operations/operationColumns.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/519
Changes:
1. Modifed Action cells
2. Change heading from More to More Actions
3. Fixed the text colours
4. added button outline for actions cells
5. Modified the menu items in more actions
To test:
1. Go to http://localhost:3000/reporting/reports
2. manually change status of any report in report_version table to Submitted, and you will see submitted in status with green colour , in action the button text will be View Details and in more actions two options - Create Supplementary Report and Report History.(As of now we do not have functionality for view detail, but that will be capture in separate tickt)
3. For all the other status, in more action only Report History will be visible
=> chore: fixed report table

bciers/apps/administration/app/components/operations/OperationInformationForm.tsx, bciers/apps/administration/app/components/operations/OperationInformationPage.tsx, bciers/apps/administration/app/data/jsonSchema/operationInformation/administrationOperationInformation.ts, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/registration/app/components/operations/registration/ConfirmChangeOfRegistrationPurposeModal.tsx
card: #2169 
This is a second PR for the same card to fix some issues @fviduya found in QA. See the card's comments for more details, but TLDR the issues are:
- modal text said ALL of the data will be deleted when changing purpose, but fields that are still relevant to the new purpose stayed filled
- on the admin OperationForm, when switching from an EIO to another purpose, the form stayed stuck on the EIO fields and dropdown options
This PR:
- update the modal text to say SOME instead of ALL (desired behaviour is to keep stuff that's still relevant)
- fix the stuck EIO form. Did this by: When we first generate the rjsf schema (`formSchema`), we do that based on the existing registration purpose. However, if a user switches the purpose, we need the new purpose's schema, and we can't …
=> 2169 2 changing reg purpose

bc_obps/reporting/service/report_activity_save_service.py, bc_obps/reporting/tests/api/test_activity_data.py, bc_obps/reporting/tests/api/test_report_activity_endpoint.py, bc_obps/reporting/tests/service/test_report_activity_save_service/infrastructure.py, bc_obps/service/activity_service.py, bc_obps/service/form_builder_service.py, bc_obps/service/tests/test_service_utils.py, bc_obps/service/utils/constants.py, bc_obps/service/utils/get_report_valid_date_from_version_id.py
Card: https://github.com/bcgov/cas-reporting/issues/378
- Activity service: GET changed to use reporting_year_id instead of created_at
- activity_save_service: POST changed to use  reporting_year_id instead of created_at
- updated relevant tests to use reporting_year_id and hardcoded in a valid reporting_year, otherwise the model bakery try using the year -7643453423 (because the reporting_year is an int field, and not a date field)
- Updated name of supporting function (get_report_valid\_**year**\_from_version_id -> get_report_valid\_**date**\_...) to more accurately reflect the functions purpose.
The ticket included removing facility_id after the refactor since it would no longer be used. Work in (this)[https://github.com/bcgov/cas-reporting/issues/522] ticket likely mean it is still …
=> 378 refactor valid date away from created_at

bc_obps/reporting/migrations/0008_prod_data.py, bc_obps/reporting/migrations/0009_general_stationary_combustion_data.py, bc_obps/reporting/migrations/0010_combustion_for_line_tracing_data.py, bc_obps/reporting/migrations/0011_mobile_combustion_data.py, bc_obps/reporting/migrations/0012_gsc_other_than_non_compression.py, bc_obps/reporting/migrations/0013_refinery_fuel_gas_data.py, bc_obps/reporting/migrations/0015_gsc_non_compression_non_processing.py, bc_obps/reporting/migrations/0061_electricity_generation.py
Addresses:
[560](https://github.com/bcgov/cas-reporting/issues/560)
- Updated the reporting fuel unit fields names to be unique, based on gas_type and methodology, so fuel units display correctly reflecting the gas type and methodology selected.
```
cd bc_obps
make reset_db
make run
```  
```
```  
1. Navigate to http://localhost:3000
1. Navigate to `Activities` route, ex: http://localhost:3000/reporting/reports/1/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/activities
2. Select `General stationary combustion of fuel or waste with production of useful energy`
3. In section `Emission 1` change the gas type and …
=> Chore: 560 emissions fuel unit value

bc_obps/reporting/migrations/0018_pulp_and_paper_production.py, bc_obps/reporting/service/emission_category_mapping_service.py, bc_obps/reporting/service/report_activity_save_service.py, bc_obps/reporting/tests/models/program_configuration_tests/test_pulp_and_paper_production_2024.py, bc_obps/reporting/tests/service/test_report_activity_save_service/test_save_report_emission_categories.py, bciers/apps/reporting/src/app/components/activities/uiSchemas/pulpAndPaperUiSchema.ts
Card: https://github.com/bcgov/cas-reporting/issues/402
- added is_pulp_and_paper_woody_biomass function instead of handle_exception (as in the dev checklist). This function returns a bool rather than applying the category itself
- added a checkmark to activity page. The field and configurations for this were added to the original pulp_and_paper migration
- added a test for the expected outcome
1. Reset database, run migrations, run frontend and backends, log in.
2. Navigate to http://localhost:3000/reporting/reports/1/review-operator-data
3. add 'Pulp and Paper' to the Reporting activities field and click 'Save & Continue'
4. select a Person responsible and click 'Save & Continue'
5. Click 'Pulp and Paper production' on the task list
a. Methodology is either 'Solids-HHV' or 'Solids-CC' …
=> feat: add woody biomass emission exception for pulp and paper

bc_obps/reporting/schema/report_operation.py, bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/operationReviewFactoryItem.ts, bciers/apps/reporting/src/app/components/operations/OperationReviewForm.tsx, bciers/apps/reporting/src/app/components/operations/OperationReviewPage.tsx, bciers/apps/reporting/src/app/utils/constants.ts, bciers/apps/reporting/src/data/jsonSchema/operations.ts, bciers/apps/reporting/src/tests/components/operations/OperationReviewForm.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/499
Changes:-
1. Added check for registration purpose and conditionally render regulated products
2. Trade to accpet both string or null
3. Fixed test
To test:-
1. Go to http://localhost:3000/reporting/reports
2. Choose any operation with registration purspose as Electricity Import Operation, Reporting Operation or Potential Reporting Operation or manually set registration purpose for any operation to any of these.
3. You will not see regulated products on Review Operation Information
=> chore: fixed field error on review operation page

bciers/apps/reporting/src/app/components/verification/VerificationPage.tsx, bciers/apps/reporting/src/middlewares/withRulesAppliedReport.test.ts, bciers/apps/reporting/src/middlewares/withRulesAppliedReport.ts, bciers/apps/reporting/src/tests/components/verification/VerificationPage.test.tsx
Addresses changes required access to `operation_type` from the API `def get_report_operation_by_version_id`
[See change](https://github.com/bcgov/cas-registration/commit/10118b1d7d53fe5757a049247145bf432a847f3e)
- Updated to `VerificationPage`
- Updated to `withRulesAppliedReport.ts`
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
4. Click the **"Log in with Business BCeID"** button  
---
1. Navigate to: http://localhost:3000/reporting/reports/1/verification
✅  
1. Navigate to: http://localhost:3000/reporting/reports/2/verification
✅  
---
1. Navigate to: http://localhost:3000/reporting/reports/2/facilities/review-facilities …
=> chore: update access to `operation_type`

bc_obps/reporting/service/report_submission_service.py, bc_obps/reporting/tests/service/test_report_submission_service.py, bciers/apps/reporting/src/app/components/signOff/reportValidationMessages.ts
Addresses:  [601](https://github.com/bcgov/cas-reporting/issues/601)
- Added submission verification of report verification record when report needs verification
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
4. Click the **"Log in with Business BCeID"** button  
---
1. Click Start/Continue for an Operation with where Verification is needed, ex `Bugle SFO - Registered`
2. Navigate to `/sign-off` for operation where Verification is needed, ex: http://localhost:3000/reporting/reports/1/sign-off
3. Click `Submit`
✅  Error displays: "Verification information must be completed with this report.  Please complete the Verification …
=> chore: validate report verification on submit

bciers/apps/reporting/src/app/components/activities/uiSchemas/aluminumUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/cementProductionUISchema.ts
Addresses bug:
- Added JSON property `id` to activity uischemas that have an  `ui:order` property
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
4. Click the **"Log in with Business BCeID"** button  
---
2. Click `Continue` on a report `Bugle SFO - Registered`
3. Select `Reporting activities`: `Aluminum or alumina production`; `Cement production`
4. Click `Save & Close`
5. Navigate to activities, ex http://localhost:3000/reporting/reports/1/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/activities
6. Click `Aluminum or alumina production`
✅  No "id" error
7. Click …
=> Update Activity UI Schema: Add `id` to `ui:order` property

bc_obps/registration/fixtures/mock/operation.json, bciers/apps/reporting/src/app/components/attachments/AttachmentsForm.tsx, bciers/apps/reporting/src/tests/components/attachments/AttachmentsForm.test.tsx, bciers/libs/components/src/form/FormAlerts.tsx, bciers/libs/components/src/form/MultiStepWrapperWithTaskList.tsx, bciers/libs/components/src/form/NavigationForm.tsx
Addresses: 
[508](https://github.com/bcgov/cas-reporting/issues/508)
[611](https://github.com/bcgov/cas-reporting/issues/611)
Attachments form was submitted even if there were no pending files; such as, when there was no need for verification attachment or there was already a verification attachment, resulting in a "flashing" error at the top of the page before router navigation to sign-off page (see 508 screen-cast) 
- Updated `AttachmentsForm.tsx` to return on router navigation when no pending attachment; therefore, preventing form submit
- Updated `MultiStepWrapperWithTaskList.tsx` to display errors at the bottom of the page, similar to `MultiStepFormWithTaskList.tsx`
```sh
cd bc_obps
make reset_db
make run
```  
```sh …
```
=> Bug: Errors on attachments

bciers/apps/reporting/src/app/utils/getActivityFormData.ts, bciers/apps/reporting/src/app/utils/getActivityInitData.ts, bciers/apps/reporting/src/app/utils/getActivitySchema.ts, bciers/apps/reporting/src/app/utils/getAttachments.ts, bciers/apps/reporting/src/app/utils/getComplianceData.ts, bciers/apps/reporting/src/app/utils/getEmissionAllocations.ts, bciers/apps/reporting/src/app/utils/getFacilityReport.ts, bciers/apps/reporting/src/app/utils/getFacilityReportDetails.ts, bciers/apps/reporting/src/app/utils/getNewEntrantData.ts, bciers/apps/reporting/src/app/utils/getNonAttributableEmissionsData.ts, bciers/apps/reporting/src/app/utils/getOperationEmissionSummaryData.ts, bciers/apps/reporting/src/app/utils/getOperationFacilitiesList.ts, bciers/apps/reporting/src/app/utils/getOrderedActivities.ts, bciers/apps/reporting/src/app/utils/getRegistrationPurpose.ts, bciers/apps/reporting/src/app/utils/getReportAdditionalData.ts, bciers/apps/reporting/src/app/utils/getReportFacilityList.ts, bciers/apps/reporting/src/app/utils/getReportNeedsVerification.ts, bciers/apps/reporting/src/app/utils/getReportType.ts, bciers/apps/reporting/src/app/utils/getReportVerification.ts, bciers/apps/reporting/src/app/utils/getReportingOperation.ts, bciers/apps/reporting/src/app/utils/getReportingPersonResponsible.ts, bciers/apps/reporting/src/app/utils/getReportingYear.ts, bciers/apps/reporting/src/app/utils/getSummaryData.ts, bciers/libs/components/src/error/ErrorBoundary.tsx, bciers/libs/components/src/error/ErrorPage.test.tsx
Addresses: [597](https://github.com/bcgov/cas-reporting/issues/597)
- Updated `ErrorBoundary` message to be more user friendly instead of Next.js generic masked error details message
- Included the reference id of the Sentry log in the error message details
- Removed (production masked) error details in `utils` fetch functions
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
4. Click the **"Log in with Business BCeID"** button  
---
1. Navigate to reporting url using an incorrect report version id, ex:
- http://localhost:3000/reporting/reports/99/review-operation-information
- …
=> chore: 597 update error boundary message

bciers/apps/reporting/src/app/components/activities/customFields/FuelFieldComponent.tsx
Card: https://github.com/bcgov/cas-reporting/issues/540
A vey small PR to encode fuel name to handle `#` in URL as it was being treated as a  fragment identifier, causing data loss when sent in the query string
=> chore:fix fuel name query string

bc_obps/registration/fixtures/mock/operation.json, bciers/apps/registration/app/components/operations/registration/OperationInformationForm.tsx, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=100904556&issue=bcgov%7Ccas-registration%7C2971
This PR:
- pulls all the operation data when selecting and operation from the dropdown in the registration form (except multiple operators: https://github.com/bcgov/cas-registration/issues/2968)
- updates mock data to be more accurate (ops that are Not Started wouldn't have a purpose yet, etc.)
=> 2971 blank operation form fields

bc_obps/registration/schema/operation.py, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
card: https://github.com/bcgov/cas-registration/issues/2968
This PR:
- fixes multiple operators not being retrieved in the Operation Registration Form
- vitest for ^
=> fix: resolve multiple operators in ninja schema

bc_obps/registration/tests/test_utils.py, bc_obps/registration/utils.py, bc_obps/service/document_service.py, bc_obps/service/tests/test_document_service.py
Part of https://github.com/bcgov/cas-registration/issues/2123 and fixes: https://github.com/orgs/bcgov/projects/123/views/16?filterQuery=repo%3Abcgov%2Fcas-registration+-status%3Adone+uat&pane=issue&itemId=99417803&issue=bcgov%7Ccas-registration%7C2915
This PR:
- removes the files_have_the_same_hash function to improve performance
- I was unable to reproduce the UAT bug (check out https://github.com/bcgov/cas-registration/pull/3009 if you want to use the same data as the test env). However, this PR should fix it as I'm removing the function the error was coming from
=> chore: remove files_have_the_same_hash

bc_obps/reporting/migrations/0008_prod_data.py, bc_obps/reporting/tests/api/test_activity_data.py, bc_obps/reporting/tests/api/test_report_activity_endpoint.py, bc_obps/reporting/tests/service/test_compliance_service/infrastructure.py, bc_obps/reporting/tests/service/test_report_activity_save_service/infrastructure.py
Card: https://github.com/bcgov/cas-reporting/issues/578
In the prod_data migration, changed how the ReportingYear entries are created:
- Removed the load from fixtures
- Used the fixture values to generate entries based on the model
Also updated tests that were using the model bakery to create 2025 reporting_year
**** Notes
- All the datetime values are the same as the fixtures, except they have been made local time (PST/PDT) instead of UTC.
- 2025 and 2026 were added
- 2023 was kept in because (despite the fact that it will never be a reporting_year) a compliance migration creating compliance_periods uses 2023 as a fk, and I didn't want to mess with it.
=> Remove and replace fixtures for reporting_year in prod_data migration

bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx
This PR:
- adds the filePreview option to all document fields (boundary map, process flow, new entrant) in both admin and registration
=> chore: set file preview to true

helm/cas-bciers/templates/cronJobs/check-file-status.yaml
A quick fix to cause the Malware scanning bucket cronjob to trigger once every 5 minutes (per minimum defined by OpenShift). 
Will be working on a permanent solution.
=> fix: set status checking cronjob to once per 5 minutes

bc_obps/service/data_access_service/document_service.py, helm/cas-bciers/templates/cronJobs/check-file-status.yaml
The cronjob function to check the status of documents as they move through malware scanning is failing in OpenShift for two reasons: 
- Missing GCP application credentials.
- No 'user' being identified when updating the file status (and therefore the location to target) in the DB, so no update record could be added. 
This PR addresses both of those issues.
=> fix: malware scanning file status cronjob errors

bciers/apps/reporting/src/app/components/signOff/Success.tsx
Fixes #3043: Updates the format of timestamp at the end of reporting the same way Transfer page is formatted
=> 3043 make timestamps uniform

bc_obps/registration/fixtures/mock/operation.json, bciers/apps/reporting/src/app/components/additionalInformation/additionalReportingData/AdditionalReportingDataPage.tsx, bciers/apps/reporting/src/app/components/facility/FacilityReviewPage.tsx, bciers/apps/reporting/src/app/components/finalReview/FinalReviewForm.tsx, bciers/apps/reporting/src/app/components/taskList/navigationInformation.ts, bciers/apps/reporting/src/app/components/taskList/reportingFlows/sfoReportingOnlyFlow.ts, bciers/apps/reporting/src/app/components/taskList/taskListPages/3_additionalInformation.ts, bciers/apps/reporting/src/app/components/taskList/taskListPages/5_signOffSubmit.ts, bciers/apps/reporting/src/app/components/taskList/types.ts, bciers/apps/reporting/src/tests/components/attachments/AttachmentPage.test.tsx
Addresses: 
[645](https://github.com/bcgov/cas-reporting/issues/645)
[600](https://github.com/bcgov/cas-reporting/issues/600)
[598](https://github.com/bcgov/cas-reporting/issues/598)
[640](https://github.com/bcgov/cas-reporting/issues/640)
[644](https://github.com/bcgov/cas-reporting/issues/644)
- `SFO` flow has `LFO` pages
-  `navigationInformation.ts`  computed the page index based on the flow pages array, which included hidden (skipped) tasklist elements, resulting in a mismatch between the calculated page index and the actual visible task list and error on `Sign-off & Submit`
- Updated pages definitions in `sfoReportingOnlyFlow`
- Updated `navigationInformation.ts` to find page index from the filtered tasklistPages array rather than in the flowData pages. This way, if a page like …
=> fix: report flows

bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/activityFactoryItem.ts
Details on the bug & how to reproduce the path are in the [issue ticket](https://github.com/bcgov/cas-reporting/issues/591)
=> fix: only add source types from the formData to the query string

bciers/apps/reporting/src/app/bceidbusiness/industry_user/reports/[version_id]/submission/page.tsx, bciers/apps/reporting/src/app/bceidbusiness/industry_user_admin/reports/[version_id]/submission/page.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx, bciers/apps/reporting/src/app/components/signOff/SubmissionPage.tsx, bciers/apps/reporting/src/app/components/taskList/taskListPages/5_signOffSubmit.ts, bciers/apps/reporting/src/middlewares/constants.ts, bciers/apps/reporting/src/middlewares/withRuleHasReportRouteAccess.test.ts
Addresses: 
[649](https://github.com/bcgov/cas-reporting/issues/649)
After clicking `Submit Report` the report status becomes `Submitted` resulting in the `sign-off` route becoming an "unauthorized" route; so, the middleware redirects the user to the "authorized" route `/submitted`.
- Updated `SignOffForm` to route to new authorized route `submission`
- Updated `middleware` to a permit "Submitted" record routes: `submitted`:`submission`
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
2. …
=> Fix: 649 report submitted routing

bc_obps/.dockerignore, bc_obps/.env.example, bc_obps/Dockerfile, bc_obps/bc_obps/settings.py, bc_obps/bc_obps/storage_backends.py, bc_obps/common/management/commands/custom_migrate.py, bc_obps/registration/utils.py
[ISSUE 2542](https://github.com/bcgov/cas-registration/issues/2542)
Reduces the backend image size from **_2.5GB_** to **_900MB_**
**CHANGES:**
- Uses multi-stage build
- Uses python-<version>-slim image (This required adding some packages manually)
References to achieve this:
- https://dylancastillo.co/til/django-poetry-dockerfile.html
- https://www.docker.com/blog/how-to-dockerize-django-app/
- https://betterstack.com/community/guides/scaling-python/dockerize-django/#step-3-writing-a-dockerfile-for-your-django-app
- https://testdriven.io/blog/docker-best-practices/#use-multi-stage-builds
- https://hadolint.github.io/hadolint/
=> chore: 2542 reduce backend docker image size

bciers/libs/components/src/form/fields/NestedArrayFieldTemplate.tsx
Card: https://github.com/bcgov/cas-reporting/issues/622
- Removed the condition on rendering the delete button on NestedArray activity elements
- go to any activity form and see that there is a delete button shown for the first instance of any unit, fuel, emission field components
=> chore: allow delete of first element on activities

bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx, bciers/apps/reporting/src/app/components/signOff/reportValidationMessages.ts, bciers/apps/reporting/src/app/utils/reportValidationMessages.ts
Addresses: [634](https://github.com/bcgov/cas-reporting/issues/634)
- Transforms back-end errors such a `emission`; `fuelName`;s `gasType` into user friendly message.
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
2. Select operation `Bugle SFO - Registered` 
3. Click `Continue`
4. Navigate to activities, ex: http://localhost:3000/reporting/reports/1/facilities/f486f2fb-62ed-438d-bb3e-0819b51e3aff/activities
5. Select `General stationary combustion excluding line tracing\General stationary …
=> chore: add friendly message mapping

bciers/apps/reporting/src/app/components/datagrid/models/reportHistory/reportHistoryColumns.tsx, bciers/apps/reporting/src/tests/components/dataGrid/model/reportHistory /reportHistoryColumns.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/674
A small PR to show date of submission as "Not yet submitted" and Submitted by as "N/A" if the status is draft on Report History Page 
To test: 
Click on report history for a report with Draft status and you should see like
=> chore fixed updatedat and submitted by

bciers/apps/reporting/src/data/jsonSchema/operations.tsx
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
2. Select operation with `Registration Purpose` ==  `OBPS Regulated Operation`
3. Click `Start`
✅ 
2. Select operation with `Registration Purpose` ==  `Reporting Operation`
3. Click `Start`
✅
=> chore: fix operation_report_type typo

bciers/apps/reporting/src/app/components/activities/ActivityInit.tsx
Card: https://github.com/bcgov/cas-reporting/issues/593
There was an issue related to rendering forms in React where duplicate fields were being identified as the same, causing unexpected behavior. This was due to React's internal key handling during re-renders.
To fix this, I added unique key props to the form fields to ensure React correctly distinguishes between them during updates.
=> chore:fixed activity form issue

bc_obps/reporting/schema/report_history.py, bc_obps/reporting/service/report_history_dashboard_service.py, bc_obps/reporting/tests/service/test_report_history_dashboard_service.py
Card: https://github.com/bcgov/cas-reporting/issues/691
A small PR to fix how the version is generated
To test 
Create multiple report versions using supplementart reports and go to 
http://localhost:3000/reporting/reports/report-history/{report_id}
You should see like
=> chore: fixed report history page version number

bciers/libs/components/src/form/fields/NestedArrayFieldTemplate.test.tsx, bciers/libs/components/src/form/fields/NestedArrayFieldTemplate.tsx
Addresses: [677](https://github.com/bcgov/cas-reporting/issues/677)
- `Final Review` page `NestedArrayFieldTemplate` has hidden remove icon 
- Updated  `NestedArrayFieldTemplate` to hide  remove icons when form is `readOnly`
- Added tests to verify that Remove and Add buttons are rendered when form is NOT read-only.
- Added tests to verify that Remove and Add buttons are NOT rendered when form is read-only.
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
2. Select operation `Bugle SFO - …
=> chore: 677 Final Review hides activity array delete icons

bciers/apps/reporting/src/app/components/verification/VerificationForm.tsx, bciers/apps/reporting/src/app/components/verification/VerificationPage.tsx, bciers/apps/reporting/src/app/components/verification/createVerificationSchema.ts, bciers/apps/reporting/src/app/components/verification/createVerificationUISchema.ts, bciers/apps/reporting/src/data/jsonSchema/verification/supplementaryReportNote.tsx, bciers/apps/reporting/src/data/jsonSchema/verification/verification.tsx, bciers/apps/reporting/src/tests/components/verification/VerificationForm.test.tsx, bciers/apps/reporting/src/tests/components/verification/VerificationPage.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/482
Changes:
added info note for supplementary report(verification page)
Updated shcema and ui schema to have info note for supplementary report verification page. 
To Test:-
1. Create a supplementary report 
2. Go to verification page 
3. You wil see a note like
=> added info note for verfication page

bciers/apps/administration/app/components/operators/OperatorForm.tsx, bciers/apps/administration/app/components/userOperators/UserOperatorReviewForm.tsx, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/administration/tests/components/operators/OperatorForm.test.tsx, bciers/libs/components/src/form/SingleStepTaskListForm.test.tsx, bciers/libs/components/src/form/SingleStepTaskListForm.tsx
card: https://github.com/bcgov/cas-registration/issues/2743
This PR:
- makes button text conditional on FormMode in single step tasklist
- update vitests
- update `showCancelButton` prop name
=> 2743 back and cancel buttons

bc_obps/reporting/schema/facility_report.py, bc_obps/reporting/tests/api/test_facility_report_api.py, bc_obps/service/facility_report_service.py, bc_obps/service/report_service.py, bc_obps/service/tests/test_facility_report_service.py, bc_obps/service/tests/test_report_service.py
Follow up to #3114. Pretty much the same fix, just for report_products.
To test this work:
- Create a report with a couple regulated_products
- Go through the report and report data on the products
- Go back to the review operation page & remove one of the products from the set
- Confirm that the associated report_product record has been deleted
=> fix: report_product data should be deleted if product removed from report_operation

bc_obps/service/tests/test_user_operator_service.py, bc_obps/service/user_operator_service.py
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=102535049&issue=bcgov%7Ccas-registration%7C3038
This PR:
- there are two services to do with contacts when user_operators are  1) created or the 2) status changes. I think this bug only affects the case of status changes, but since the code was the same in both places, I updated it in both.
- updates the services to reset the contact info to the user's if it's been changed before the contact was approved (I ~think the only way this happens is mock data, or a user is approved, edited, and then unapproved)
- updates tests. I had to get rid of magic mock in one place because it doesn't create a real UUID
- sonar duplication is on tests so I'm not worried about it
=> Contact and user bug

bc_obps/reporting/schema/facility_report.py, bc_obps/reporting/tests/api/test_facility_report_api.py, bc_obps/service/facility_report_service.py, bc_obps/service/tests/test_facility_report_service.py
Fixes an issue introduced in #3193. regulated_products should not be part of the pydantic schema. The LFO flow was also failing because of the condition `if data.regulated_products..` because the schema does not have that attribute & it is not passed from the frontend via the API. Replaced that with `if hasattr(data, 'regulated_products')` as that value can be passed as part of the `save_report_operation` service function.
=> Chore: remove regulated products from pydantic schema

bc_obps/common/fixtures/dashboard/bciers/dev/external.json, bc_obps/common/fixtures/dashboard/bciers/prod/external.json, bc_obps/common/tests/endpoints/auth/constants.py, bc_obps/reporting/api/__init__.py, bc_obps/reporting/api/validate_user_reporting_access.py, bc_obps/reporting/service/reporting_dashboard_service.py, bc_obps/reporting/tests/api/test_validate_user_reporting_access_api.py, bc_obps/reporting/tests/service/test_reporting_dashboard_service.py, bc_obps/service/data_access_service/operation_service.py, bc_obps/service/tests/test_operation_service.py, bciers/apps/reporting/src/middlewares/withResponseReport.test.ts, bciers/apps/reporting/src/middlewares/withRuleHasRegisteredOperation.test.ts, bciers/apps/reporting/src/middlewares/withRuleHasRegisteredOperation.ts
Addresses: 
[657](https://github.com/bcgov/cas-reporting/issues/657)
- Prevents Registered Operation with reporting purpose ="Potential Reporting Operation" from accessing reporting app
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
---
3. Sign in to Keycloak using `bc-cas-dev-secondary`
**Expected results:** 
- NO Registration tile
- NO Reporting tile
4. Navigate to http://localhost:3000/reporting
**Expected results:** 
- Navigation re-routes to `Dashboard`
4. Navigate to http://localhost:3000/reporting/reports
**Expected results:** 
- Navigation re-routes to `Dashboard`
---
1. Navigate to …
=> chore: 657 Potential Reporting Operation Does Not Report

bc_obps/service/form_builder_service.py
Card: https://github.com/bcgov/cas-reporting/issues/711
When a supplementary report is created, an additional entry is added to the FacilityReport table for the same facility_id, but with a different report_version_id.
Previously, we were using .get(facility_id=...), which caused a MultipleObjectsReturned error due to the presence of multiple entries for the same facility.
This PR updates the query to include report_version_id as a filter to ensure that a single, specific FacilityReport is retrieved.
=> chore: fix fetching facility report with facility id and report version

bc_obps/service/report_service.py, bc_obps/service/tests/test_report_service.py
Card: https://github.com/bcgov/cas-reporting/issues/712
A small PR to remove operation type from sync
=> chore: remove operation type from sync

bc_obps/service/application_access_service.py, bc_obps/service/tests/test_application_access_service.py, bciers/apps/administration/app/components/buttons/RequestAccessButton.tsx
[ISSUE 3127](https://github.com/bcgov/cas-registration/issues/3127)
**TO TEST:**  
- Log in as `bc-cas-three`.  
- Select an operator where the Business BCeID does not match the one for the user (e.g., `Alpha Enterprises`).  
- Confirm the request access.  
- A message like the one below should appear.
=> Chore: 3127 Reword the BCeID error message when selecting an operator

bc_obps/common/fixtures/dashboard/bciers/dev/external.json, bc_obps/common/fixtures/dashboard/bciers/prod/external.json
Card: N/A
A small PR to remove "View Past Submission" from reporting tile on the dashboard
To test:-
1. make loadfixtures
2. go to http://localhost:3000/dashboard
3. You will only one linke under reporting(Submit Annual Report)
=> chore: removed link and text for past submissions from reporting tile

bciers/apps/reporting/src/app/components/signOff/createSignOffSchema.ts
Quick fix to add "/" in supplementary report sign-off page. The wireframe originally didn't have the statement as "and/or", verified with Zoey that it's supposed to be "and/or"
Statement that will be updated:
I understand that, by submitting these changes, I am creating a new version of this annual report that will, effective immediately, be the annual report for the reporting and or compliance period that it pertains to.
To be changed to:
I understand that, by submitting these changes, I am creating a new version of this annual report that will, effective immediately, be the annual report for the reporting **and/or** compliance period that it pertains to.
=> chore: fix additional statement in supplementary report

bciers/apps/registration/app/data/jsonSchema/operationInformation/registrationPurpose.ts, bciers/apps/registration/tests/components/operations/registration/OperationInformationForm.test.tsx, bciers/libs/utils/src/customTransformErrors.ts
card:https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=105741444&issue=bcgov%7Ccas-registration%7C3178
Notes:
- In a `oneOf` schema, it appears when the docs say exactly one schema must match, that means required fields too. So we will always get a `must be const` error on registration purpose if activities or products are missing. To deal with this, I moved to if/then. This makes activities and products appear on the page on initial load. Zoey is okay with this.
- There's some interaction between the form (state-related?) and the MultiStepWidget that's producing weird behaviour. Only the last widget on the page that uses the widget gets a value of []. The other keys don't even show in the form data. E.g. {activities: []}. This means that activities correctly gets the …
=> 3178 missing validation

bciers/apps/reporting/src/app/components/activities/uiSchemas/aluminumUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/carbonatesUseUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/cementProductionUISchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/coalStorageUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/common.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/fuelCombustionMobileUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscNonCompressionNonProcessingUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/gscOtherThanNonCompression.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/hydrogenProduction.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/industrialWastewaterProcessingUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/leadProductionUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/limeManufacturingUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/openPitCoalMining.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/pulpAndPaperUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/refineryFuelGasUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/storageOfPetroleumProductsUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/zincProductionUiSchema.ts, bciers/libs/components/src/form/fields/MethodologyFieldTemplate.tsx
Card: https://github.com/bcgov/cas-reporting/issues/571
- Created MethodologyFieldTemplate that sets the "description" value to the desired warning note if the selected methodology should display a warning : ```* By selecting {methodology}, you may be contacted by Ministry staff to
verify compliance``` if the ```methodology``` is "Alternative Parameter Measurement Methodology" or
"Replacement Methodology"
- Replaced InlineFieldTemplate with MethodologyFieldTemplate in all activity uischemas
```description``` is a field that is already checked by the InlineFieldTemplate for displaying notes on a field. That is why all the MethodologyFieldTemplate does is set that ```description``` value.
I tried some other methods around trying to inject the ```description``` property into the formSchema. …
=> added warning note for certain methodologies

bciers/apps/reporting/src/app/components/attachments/AttachmentsForm.tsx
Addresses: 
[746](https://github.com/bcgov/cas-reporting/issues/746)
- Adding missing note in supplementary report attachments form
```sh
cd bc_obps
make reset_db
make run
```  
```sh
```  
1.  Navigate to reports table, http://localhost:3000/reporting/reports
2.  On `Bugle SFO - Registered`, click `Continue`
3. Complete all forms until `Attachments`
✅  
- No note
4. Complete all forms until `Sign-off`
5. On form `Sign-off` click button `Submit`
✅  
- Form is submitted
6. Navigate to reports table, …
=> chore: add attachment note

bc_obps/reporting/api/submit.py, bc_obps/reporting/schema/report_sign_off.py, bc_obps/reporting/service/report_sign_off_service.py, bc_obps/reporting/service/report_submission_service.py, bc_obps/reporting/tests/service/test_report_sign_off_service.py, bc_obps/reporting/tests/service/test_report_submission_service.py, bciers/apps/reporting/src/app/components/signOff/SignOffForm.tsx
Card: https://github.com/bcgov/cas-reporting/issues/663
Related Card: https://github.com/bcgov/cas-reporting/issues/451
Refactored report_sign_off_service to not use ninja schema data type that was also used by API. service data type has been uncoupled and is now defined within the service. 
Other changes were refactoring the data to and in the API to lower transformations away from the base formData.
=> refactor: uncouple report sign-off data type from api

bc_obps/common/tests/test_email_service.py, bc_obps/registration/emails.py, bc_obps/registration/enums/enums.py, bc_obps/registration/tests/test_emails.py, bc_obps/service/email/email_service.py, bc_obps/service/operation_service.py, bc_obps/service/tests/test_operation_service.py, docs/backend/data-models.md
card: https://github.com/bcgov/cas-registration/issues/3332
This PR:
- removes the `send_email` service (we weren't using)
- renames the email template enums for hopefully more clarity
- uses the new email template in operation_service
- pytests for ^
- tweak docs to explain how to test emails in local
I've also made a tech debt ticket with some nice-to-haves for emails: https://github.com/bcgov/cas-registration/issues/3336
=> 3332 end correct email template to confirm registration

bciers/apps/registration/app/components/operations/registration/FacilityInformationForm.tsx, bciers/apps/registration/app/components/operations/registration/FacilitySfoForm.tsx, bciers/apps/registration/tests/components/operations/registration/FacilitySfoForm.test.tsx
card #3202 
This PR:
- re-adds the code for PUT (necessary when navigating backwards through reg to avoid the "Operation can only have facility... error)
=> chore: support PUT for SFO in registration

bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/personResponsibleFactoryItem.ts
After taking a look at the components in dev, title is shown to be set to " ". This is only ever done in the `personResponsibleFactoryItem`. In this item, the jsonSchema is being directly set for the review page. I'm hoping that it is as simple as a shared object mutation and that this will fix dev and prod by referencing the schema with a deep copy.
=> fix: Attempt to fix personResponsible page in dev by ensuring factory item for review page doesn't overwrite jsonSchema

bc_obps/reporting/api/report_supplementary_version.py, bc_obps/reporting/tests/api/test_report_supplementary_version_api.py
Card: https://github.com/bcgov/cas-reporting/issues/760
Changes: 
Added check on create supplementary report, if registration purpose different in operation and report operation call create report version otherwise call create supplementary report version
=> chore: fixed supplementary report creation

bc_obps/service/form_builder_service.py, bciers/apps/reporting/src/app/utils/reportValidationMessages.ts
[475](https://github.com/bcgov/cas-reporting/issues/475)
just makes emission a required field
=> fix: insert 'require' array for emission field in reporting activity forms

bc_obps/service/data_access_service/operation_designated_operator_timeline_service.py, bc_obps/service/tests/data_access_service/test_data_access_operation_designated_operator_timeline.py, bciers/apps/administration/app/components/operations/OperationDataGrid.tsx, bciers/apps/administration/app/components/operations/OperationDataGridPage.tsx
card: https://github.com/bcgov/cas-registration/issues/3180
This PR:
- changes the service that pulls operation data for IRC users to not filter automatically on status
- use the status filter on the endpoint instead (sent via the front end grid component)
- I chose to do this^ to avoid making a new endpoint/service that was specific to filtering on the operation status. I don't ~think there's any problem with having the service fetch all operation statuses by default. If IRC users are allowed to see everything in transfers, then we aren't restricting it in the grid for security, just for convenience
- update pytests
=> 3180 transfers show all operations

bciers/libs/components/src/form/widgets/TextWidget.tsx
- **fix: Allow zeroes for numberfields**
- **chore: make style of numberfield widget consistent**
User can type and submit 0s again if the field allows and the border color is fixed
=> 758 numberfield fix

bc_obps/registration/models/rls_configs/operation.py, bc_obps/service/tests/test_transfer_event_service.py, bc_obps/service/transfer_event_service.py
card: https://github.com/bcgov/cas-registration/issues/3340
This PR:
- Updates_process_operation_transfer and removes contacts belonging to the original operator.
- Enhances tests to verify that the contacts are detached (but not deleted) correctly.
- Updates RLS configurations to include DELETE permission for the CAS_ANALYST role, supporting transfer operations.
=> 3340 transfers and contacts

bciers/apps/dashboard/auth/index.ts, bciers/libs/components/src/auth/SessionTimeoutHandler.test.tsx, bciers/libs/components/src/auth/SessionTimeoutHandler.tsx, bciers/libs/components/src/auth/throttleEventsEffect.ts, bciers/package.json, bciers/yarn.lock
card: https://github.com/bcgov/cas-registration/issues/3268
This card talks about two things:
- logout modal doesn't show
- user is not redirected after logout (Zoey's comment `The "you've been signed out" page doesn't always appear. I left the tab open yesterday on the final review page, and came back today to the tab and it was still on the final review page instead of on the "you've been signed out"`)
These problems are caused by having the app open in more than one tab. The non-active tab logs the user out of all tabs after 30 minutes but only redirects them from the tab the triggered the logout. This makes it seem like the modal never showed up (it did, but it was in the inactive tab). It also makes it seem like the user is still logged in when they're not because they're not …
=> 3268 2 logout redirect

bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx
Card: https://github.com/bcgov/cas-reporting/issues/720
```facility_total_emissions``` is a read only text field that shows the total of all emissions reported through activities. Despite being read only, the field is part of the schema and is therefore validated by the frontend form validator.
When there is ANY amount of emission data, the server responds with a decimal value like ```Decimal('1234.5678')```. In order to preserve accuracy, JS interprets this as a string, and so that is the type the schema was written to expect. BUT when there is NO emission data reported, the server responds with an int value of ```0```. And Javascript has no problem seeing this as a number. And so when you try to submit, validation fails because a number is where a string is expected.
To resolve, I just …
=> 720 convert facility_total_emissions to string for consistency

bc_obps/registration/fixtures/mock/bc_greenhouse_gas_id.json, bc_obps/registration/fixtures/mock/bc_obps_regulated_operation.json, bc_obps/registration/fixtures/mock/facility.json, bc_obps/registration/fixtures/mock/operation.json, bc_obps/registration/tests/endpoints/_operations/_operation_id/test_bcghg_id.py, bc_obps/service/operation_service.py, bc_obps/service/tests/test_operation_service.py
card: https://github.com/orgs/bcgov/projects/123/views/16?pane=issue&itemId=108763205&issue=bcgov%7Ccas-registration%7C3287
This PR:
- Introduces tests in TestGenerateBCGHGId to validate user access and proper BCGHG ID assignment for SFO and non-assignment for LFO.
- Wraps the generate_bcghg_id method in a transactional block and updates the facility’s BCGHG ID for SFO operations.
- Updates mock data so SFO facilities have the same BCGHG IDs as their operations. Also made Alien a draft because it can't be registered if it doesn't have a facility
Note that we don't show BCGHG ID on the SFO form (will be added in https://github.com/bcgov/cas-registration/issues/3286), so to test this, you'll have to temporarily add it, or check in the db.
=> chore: assign SFO operation BCGHGID to facility too

bciers/apps/reporting/src/app/components/facility/FacilityReviewForm.tsx, bciers/apps/reporting/src/tests/components/facility/FacilityReviewForm.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/717
- Added a check to FacilityReviewForm handleSubmit(): if there are 0 activities selected, prevent submission and display error "You must select at least one activity"
1. Log in as industry user
2. Navigate to Submit Annual Report(s)
3. Click Start for Banana LFO
4. Navigate all the way through the Review Facility Information page of Facility 1
5. Uncheck activities
6. Click Save & Continue
Expect : An error to show up saying "You must select at least one activity"
Previous behaviour: Would save and attempt to navigate to a non-existent activity form
=> 717 Prevent review facility submit with 0 activities

bc_obps/reporting/migrations/0106_update_electricity_generation.py, bc_obps/reporting/tests/models/program_configuration_tests/test_electricity_generation_2024.py
Card: https://github.com/bcgov/cas-reporting/issues/761
Fixed the methodology name changed Heat Input/Default EF to Measured Steam/Measured EF
=> chore: fixed methodology name

bciers/libs/components/src/auth/SessionTimeoutHandler.test.tsx, bciers/libs/components/src/auth/SessionTimeoutHandler.tsx
card #3268 
This PR:
- removes the refresh from the broadcast useEffect and uses getSession instead (we think refreshing in multiple tabs made update not work). Also updates the local state
- activityHandler doesn't run if the modal is open
- puts redirectTo back in. @Sepehr-Sobhani wasn't being logged out properly without it
=> 3268 3 logout redirect

bc_obps/reporting/tests/api/test_build_form_schema.py, bc_obps/service/form_builder_service.py, bc_obps/service/tests/test_form_builder_service.py, bciers/apps/reporting/src/app/components/activities/ActivityForm.tsx, bciers/apps/reporting/src/app/components/activities/uiSchemas/custom.tsx, bciers/apps/reporting/src/app/components/activities/uiSchemas/fallbackUiSchema.ts, bciers/apps/reporting/src/app/components/activities/uiSchemas/schemaMaps.tsx, bciers/apps/reporting/src/tests/components/activities/ActivityForm.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/754
Changes: 
1. Implemented logic to return a fallback schema when no valid ActivityJsonSchema is found for the specified activity_id.
2. Updated Activity form to check for fallbackSchema, if exist then update the form according and do not  mak a post request.
3. Updated tests
To test:-
1. Go to http://localhost:3000/reporting/reports
2. Start a report and select activities like Electronics manufacturing, Phosphorous acid Production or other activities which havent been implemented yet on http://localhost:3000/reporting/reports/1/review-operation-information. 
3. On activities page select this activities and you will see page like
=> chore: Added default page for activity not implemented

bciers/apps/reporting/src/app/components/changeReview/ChangeReviewPage.tsx, bciers/apps/reporting/src/app/components/finalReview/FinalReviewPage.tsx, bciers/apps/reporting/src/app/components/signOff/SignOffPage.tsx, bciers/apps/reporting/src/app/components/taskList/navigationInformation.ts, bciers/apps/reporting/src/middlewares/withRuleHasReportRouteAccess.ts
Cards: #780, #782
The problem: `pages` in `navigationInformation.ts` was a deep copy, so if a page was removed from navigation, it would then not get added back in. 
The fix: make a shallow copy of `pages` instead.
To test https://github.com/bcgov/cas-reporting/issues/780:
- create an operation with registration purpose "Reporting Operation", and register it
- create a new report for your operation, and first set the operation's total emissions to below 25k. Navigate all the way through to the Sign Off & Submit section, but don't submit yet. The "Verification" page should not appear because emissions < 25k.
- navigate back to the emissions reporting section, and edit the emissions to be above 25k. Then click through all the way to Sign Off & Submit
- you should now see the "Verification" …
=> Fix/reporting routes/780 782

helm/cas-bciers/templates/administration/route.yaml, helm/cas-bciers/templates/compliance/route.yaml, helm/cas-bciers/templates/dashboard/route.yaml, helm/cas-bciers/templates/registration/route.yaml, helm/cas-bciers/templates/reporting/route.yaml
Our routes were configured to send all requests to one pod in the service's endpoints list, making our HPA pointless. 
Disabling sticky sessions will allow our balancing method to come into effect and even out the load across all pods in the service's endpoints.
=> fix: disable sticky sessions in k8s routes to even out load among pods

bciers/libs/actions/src/actions.ts, bciers/libs/utils/src/actions.test.ts, bciers/libs/utils/src/getUUIDFromEndpoint.ts
card: https://github.com/bcgov/cas-registration/issues/3398
This PR:
- changes the wording of the endpoint is not allowed error 
- updates vitests
- I didn't want to use dangerouslySetInnerHtml, so checked with Patricia and having the link not hyperlinked is ok. If the reviewer has another fix though, would love to hear it! (It's impractical to transform the error on the FE like we did [here](https://teams.microsoft.com/l/message/19:81544b60877c4a5eb4fc7946ecbcb525@thread.tacv2/1743782396664?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=29821293-3244-455d-beae-e01d27762cfe&parentMessageId=1736798769019&teamName=External%3A%20CAS%20-%20Clean%20Growth%20Digital%20Service%20Team&channelName=Developers&createdTime=1743782396664&ngc=true) because this endpoint error can appear anywhere …
=> chore: update endpoint is not allowed error message

bciers/libs/testConfig/src/global.tsx, bciers/libs/testConfig/src/mocks.ts, bciers/libs/utils/src/sessionUtils.test.ts
card: https://github.com/bcgov/cas-reporting/issues/795
This PR:
- updates the vitests for sessionUtils, tech debt from #3408
=> sessionUtils vitests

bciers/apps/reporting/src/app/components/finalReview/reviewDataFactory/activityFactoryItem.ts, bciers/libs/components/src/form/fields/GasTypeCasNumberFieldTemplate.tsx
**Card:** [bcgov/cas-reporting #730](https://github.com/bcgov/cas-reporting/issues/730)
**Summary of changes:**
1. Fixed an issue on the Activity page where gasTypes were missing from the formContext in the final activityDataFactory. Now, gasTypes are correctly passed as part of the form context.
2. Updated the field template to properly display the CAS Registry Number:
3. On the Final Review page, the CAS Registry Number is displayed as plain text.
4. On the Activity page, it remains a disabled text field for input consistency.
**How to test:**
1. Navigate to the Final Review page.
2. Under Report Information > Emission, you should now see the CAS Registry Number displayed as plain text for the selected Gas Type.
=> chore: fixed cas regsitry number in final review page

helm/cas-bciers/values-dev.yaml, helm/cas-bciers/values-prod.yaml, helm/cas-bciers/values-test.yaml
Context: github alerted us to a potential password leak in our repo regarding our clientKey for Growthbook. Our clientKey isn't actually confidential, but since we're not using growthbook at the moment, I'm removing it from our yaml files anyway (but it hasn't been totally scrubbed from our repo, it will still appear in previous commits). 
A copy of our clientKey has been saved into our team 1Password for reference just in case.
-----
chore: removed growthbook clientKey from values.yaml for dev, test, and prod
=> Remove Growthbook clientKey from values.yaml

helm/cas-bciers/templates/NetworkPolicy/backendPostgresIngress.yaml, helm/cas-bciers/templates/backend/check-file-status-deployment.yaml
Fixes configuration of new file check deployment to be selectable independent from the backend. Adds additional network selectors so that the pod can properly access postgres.
=> chore: update selectors to avoid backend collision

bc_obps/registration/tests/test_utils.py, bc_obps/registration/utils.py, bc_obps/service/operation_service.py, bc_obps/service/tests/test_operation_service.py
Part of https://github.com/bcgov/cas-registration/issues/3055
This PR:
- moves the conditionality about ignoring document scan in CI/local to a helper
- uses the helper in operation_service
- pytests (operation_service already had tests for this (search monkeypatch), so the new ones are only for the util)
=> chore: util for checking document scan

bc_obps/common/tests/endpoints/auth/constants.py, bc_obps/compliance/api/_bccr/_accounts/_account_id/_compliance_report_versions/_compliance_report_version_id/compliance_units.py, bc_obps/compliance/dataclass.py, bc_obps/compliance/schema/apply_compliance_units.py, bc_obps/compliance/service/apply_compliance_units_service.py, bc_obps/compliance/service/bc_carbon_registry/bc_carbon_registry_api_client.py, bc_obps/compliance/service/bc_carbon_registry/bc_carbon_registry_service.py, bc_obps/compliance/service/bc_carbon_registry/utils.py, bc_obps/compliance/tests/api/_bccr/_accounts/_account_id/_compliance_report_versions/_compliance_report_version_id/test_compliance_units.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_utils.py, bc_obps/compliance/tests/service/test_apply_compliance_units_service.py, bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.tsx, bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/review-compliance-summary/ComplianceSummaryReviewPage.tsx, bciers/apps/compliance/src/app/data/jsonSchema/manageObligation/applyComplianceUnitsSchema.tsx, bciers/apps/compliance/src/app/widgets/ApplyComplianceUnitsWidget.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.test.tsx, bciers/apps/compliance/src/tests/components/widgets/ApplyComplianceUnitsWidget.test.tsx
[ISSUE 161](https://github.com/bcgov/cas-compliance/issues/161)
**Changes:**
- **New Endpoint for Compliance Unit Transfer**
- Added a POST API endpoint to apply (transfer) compliance units between BCCR accounts.
- Updated test constants and endpoint registration to include the new endpoint.
- **Data Model Enhancements**
- Introduced new dataclasses for transfer payloads and mixed units.
- **Service and Business Logic**
- Implemented service method for applying (transferring) compliance units, with:
- Quantity limit validation (cannot apply more than available).
- Construction of transfer payloads for downstream API.
- **API Client and Utility Improvements**
- Added a utility function (`log_error_message`) to extract and log detailed error messages from failed BCCR API responses.
🧪 **To …
=> feat: 161 transfer compliance units

bciers/apps/registration/app/components/operations/registration/NewOperationRepresentativeForm.tsx, bciers/apps/registration/tests/components/operations/registration/NewOperationRepresentativeForm.test.tsx
card: https://github.com/bcgov/cas-registration/issues/3130
This PR:
- forces a rerender when selecting a new contact. Without this, we see data for the wrong contact when switching between contacts if the new contact has null data for a field the previous contact did have data for
- regression test
- sonarcloud fail is fine; the random number generation is just for a rerender key, not for anything sensitive
=> 3130 operation rep bug

bc_obps/compliance/api/_bccr/_accounts/_account_id/_compliance_report_versions/_compliance_report_version_id/compliance_units.py, bc_obps/compliance/dataclass.py, bc_obps/compliance/schema/apply_compliance_units.py, bc_obps/compliance/service/bc_carbon_registry/apply_compliance_units_service.py, bc_obps/compliance/tests/api/_bccr/_accounts/_account_id/_compliance_report_versions/_compliance_report_version_id/test_compliance_units.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_apply_compliance_units_service.py, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/pay-obligation-track-payments/ObligationTrackPaymentsComponent.test.tsx
**[ISSUE 206](https://github.com/bcgov/cas-compliance/issues/206)**
Replace hardcoded outstanding balance in `apply_compliance_units_service` with dynamic value sourced from `ElicensingInvoice` model via the compliance obligation relationship chain.
---
- **`ApplyComplianceUnitsService.get_apply_compliance_units_page_data()`** - Enhanced method to dynamically fetch outstanding balance:
- Replaced hardcoded `outstanding_balance="16000"` with dynamic lookup
- Leverages existing `ComplianceObligationService.get_obligation_data_by_report_version()` method for robust data retrieval
- Service method includes elicensing data refresh before accessing invoice data
---
1. Log in as `bc-cas-dev`
2. Submit the **Bugle SFO - Registered** with excess emissions
1. Navigate to **Compliance Summaries** …
=> chore: 206 replace hardcoded outstanding_balance

bc_obps/common/tests/endpoints/auth/constants.py, bc_obps/registration/api/_contacts/contact_id.py, bc_obps/registration/api/contacts.py, bc_obps/registration/fixtures/mock/contact.json, bc_obps/registration/fixtures/mock/user.json, bc_obps/registration/tests/endpoints/test_contacts.py, bc_obps/service/contact_service.py, bciers/apps/administration-e2e/playwright.config.ts, bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/app/components/contacts/ContactsDataGrid.tsx, bciers/apps/administration/app/components/contacts/types.ts, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx, bciers/apps/administration/tests/components/contacts/ContactPage.test.tsx, bciers/apps/administration/tests/components/contacts/ContactsDataGrid.test.tsx, bciers/apps/compliance-e2e/playwright.config.ts, bciers/apps/dashboard-e2e/playwright.config.ts, bciers/apps/registration-e2e/playwright.config.ts, bciers/apps/reporting-e2e/playwright.config.ts, bciers/libs/actions/src/api/archiveContact.ts, bciers/libs/actions/src/api/index.ts, bciers/libs/components/src/form/SingleStepTaskListForm.tsx, bciers/libs/components/src/modal/SimpleModal.tsx, bciers/libs/testConfig/src/global.tsx, bciers/libs/testConfig/src/mocks.ts
card: https://github.com/bcgov/cas-registration/issues/1606
This PR:
- adds a delete button and conditional props to the SingleStepTasklist (currently the contact form is the only one with a delete button, but it looks like it's needed for https://github.com/bcgov/cas-registration/issues/3482 too, and it was clearer to add to that component vs. trying to wrestle it into ContactForm)
- modal when the delete button is clicked; text and buttons in the modal conditional on whether or not the contact is assigned places
- endpoint to archive contact
- snackbar on grid
- added bc-cas-dev and bc-cas-dev-secondary as contacts (more representative of real app; every user should have a contact record too unless someone later deletes it)
- pytests
- vitests
- added an env variable so we can make the …
=> Delete contacts 1606

bciers/apps/administration/app/components/contacts/ContactForm.tsx, bciers/apps/administration/tests/components/contacts/ContactForm.test.tsx
card #1606 
This PR is a follow up to the main PR to address this part:
- removes the "Delete Contact" button for reporters
=> chore: reporter does not see delete contact button

bciers/apps/reporting/src/app/components/activities/ActivityInit.tsx, bciers/apps/reporting/src/tests/components/activities/ActivityInit.test.tsx
Card: https://github.com/bcgov/cas-registration/issues/3538
**Issue**
When a user deselects a previously selected activity, the activityId may reference an activity that no longer exists in the orderedActivities array. This results in the find() method returning undefined, causing currentActivity to be undefined and leading to runtime errors when the component expects a valid activity object.
```
if (activityId) {
currentActivity = orderedActivities.find(
(obj: ActivityData) => obj.id === activityId,
);
}
```
**Fix**
Added a fallback to ensure currentActivity is always defined. If the requested activity is not found, we now default to the first activity in the array:
```
if (activityId) {
currentActivity = orderedActivities.find(
(obj: ActivityData) => obj.id === activityId,
);
}
if …
```
=> chore: added check for activity Id and tests

bc_obps/compliance/service/bc_carbon_registry/apply_compliance_units_service.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_apply_compliance_units_service.py
https://github.com/bcgov/cas-compliance/issues/265
This PR:
- put a negative in front of the adjustment value in the apply compliance unit service (if we're applying units, the balance is always going to go down)
- pytest to check that the apply service is called with a negative number
=> 265 fix outstanding balance calculation

.sonarcloud.properties, bc_obps/compliance/service/compliance_dashboard_service.py, bc_obps/compliance/tests/service/test_compliance_dashboard_service.py
card: https://github.com/bcgov/cas-compliance/issues/239
This PR:
- adds a condition to show the excess emissions delta for supplementary reports (vs. the excess emissions of the original report) on the compliance summary page
- pytests for ^
Notes:
- sonar fails are on duplication in tests; if the reviewer agrees, I'll dismiss
- I didn't do the DC about changing the ninja schema because I don't think I need to--I'm still using the excess_emissions alias
To test:
- create a supplementary report with higher emissions than the original report. You should see a new row in the summaries grid with the new excess emissions and equivalent value in its grid and on its summary page
- currently, nothing's built to handle supplementary reports with lower emissions, so the only way to test that case …
=> 239 excess emissions value

bc_obps/compliance/service/compliance_invoice_service.py, bc_obps/compliance/tests/service/test_compliance_invoice_service.py
[ISSUE 269](https://github.com/bcgov/cas-compliance/issues/269)
Follow-up to (https://github.com/bcgov/cas-compliance/issues/265)
🐞 Bug Fix: Incorrect Amount Due Calculation When Generating Compliance Invoice
Overview
Resolved an issue where, after an industry user applied compliance units to an obligation, the Generate Compliance Invoice action would incorrectly calculate a higher "Amount Due"—adding the value of applied compliance units on top of the original obligation amount, instead of properly subtracting it.
🔧 Fix Summary
- Updated invoice calculation logic:
- Ensured amount due is correctly reduced by the value of applied compliance units
- Reviewed and updated relevant service/function responsible for the calculation before invoice generation
- Added regression checks to confirm …
=> fix: invoice amount should properly handle adjustments

bc_obps/compliance/dataclass.py, bc_obps/compliance/service/compliance_invoice_service.py, bc_obps/compliance/templates/invoice.html, bc_obps/compliance/tests/service/test_invoice_template.py, bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/download-payment-instructions/PaymentInstructionsDownloadComponent.tsx, bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/pay-obligation-track-payments/ObligationTrackPaymentsComponent.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/download-payment-instructions/PaymentInstructionsDowloadComponent.test.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/pay-obligation-track-payments/ObligationTrackPaymentsComponent.test.tsx
[ISSUE 124](https://github.com/bcgov/cas-compliance/issues/124)
[ISSUE 272](https://github.com/bcgov/cas-compliance/issues/272)
This PR implements the display of voided invoices with a visual watermark to clearly indicate their voided status.
- **File**: `bc_obps/compliance/service/compliance_invoice_service.py`
- Enhanced `generate_invoice_pdf` method to detect voided invoices
- Added logic to determine `invoice_is_void` based on invoice's `is_void` status and compliance report version status being `OBLIGATION_FULLY_MET`
- **File**: `bc_obps/compliance/templates/invoice.html`
- Added CSS styles for watermark display with 45-degree rotation and low opacity
- Added conditional watermark rendering when `invoice_is_void` is true
**Issue**: …
=> Feat 124 display voided invoice

bciers/libs/actions/src/actions.ts, bciers/libs/utils/src/actions.test.ts
Potential fix for [https://github.com/bcgov/cas-registration/security/code-scanning/145](https://github.com/bcgov/cas-registration/security/code-scanning/145)
To fix the issue, we need to sanitize the `endpoint` parameter before using it in the error message. A simple and effective approach is to ensure that the `endpoint` value is safely escaped or explicitly converted to a string using a `%s` specifier in the log message. This prevents any unintended behavior caused by malicious input. Additionally, we should validate the `endpoint` value to ensure it conforms to expected patterns (e.g., a valid URL or path).
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 145: Use of externally-controlled format string

bc_obps/compliance/schema/compliance_report_version.py, bc_obps/compliance/tests/api/_compliance_report_versions/test_compliance_report_version_id.py, bc_obps/compliance/tests/api/test_compliance_report_versions.py
https://github.com/bcgov/cas-compliance/issues/173
=> fix: let operation name in compliance summary grid take from reporting rather than admin

bc_obps/compliance/service/supplementary_version_service.py, bc_obps/compliance/tests/service/test_supplementary_version_service.py, bciers/package.json, bciers/yarn.lock
card: https://github.com/bcgov/cas-compliance/issues/248
This PR:
- adds NoChangeHandler
- pytests for ^
- slight refactor of the existing pytests to make a reusable setup method
=> 248  - Compliance/Handle supplementary version case where the new version doesn't change the obligation or earned credits

bc_obps/compliance/service/compliance_invoice_service.py, bc_obps/compliance/tests/service/test_compliance_invoice_service.py, bciers/apps/compliance/src/app/components/layout/CompliancePageHeading.tsx, bciers/apps/compliance/src/tests/components/layout/CompliancePageHeading.test.tsx
Part 2 of ticket [173](https://github.com/bcgov/cas-compliance/issues/173)
This changes the operation name to be pulled from reporting in the:
- Compliance obligation review page
- Compliance invoice
To Test:
- continue a report with obligation not met
- change the name
- go to compliance and manage obligation of the compliance report
- report name in title should be new name
- click generate invoice
- invoice should contain edited operation name as well
=> 173 operation name should be derived from reporting

bciers/apps/administration/tests/components/facilities/FacilityForm.test.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/pay-obligation-track-payments/ObligationTrackPaymentsComponent.test.tsx, bciers/apps/registration/tests/components/transfers/TransferDetailForm.test.tsx, bciers/libs/components/src/form/widgets/readOnly/ReadOnlyDateWidget.test.tsx, bciers/libs/components/src/form/widgets/readOnly/ReadOnlyDateWidget.tsx
[278](https://github.com/bcgov/cas-compliance/issues/278)
- **fix: change date widget format to Mon DD, YYYY**
- **test: update test for datewidget to display in mmm dd, yyyy format**
*** this PR also changes anything related to the date widget:
- transfer detail form
- facility form
**To Test:**
- sign off on a report with an obligation
- navigate to pay obligation page
- payment received date should be in the format Mon DD, YYYY
=> date format update mmm dd, yyyy

bc_obps/compliance/service/bc_carbon_registry/apply_compliance_units_service.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_apply_compliance_units_service.py
Fixes an issue with how the earned credit limit/cap was being calculated.
The issue:
When an adjustment is made via a supplementary report. It should be considered when calculating the 50% limit, but not count against the cap remaining (adjustments made when applying credits should lower the cap remaining, not supplementary adjustments).
The fix:
Updated the get adjustments function to differentiate between those two adjustment types and fetch them in the appropriate places in the function logic.
=> chore: correct calculation for earned credit cap limit

bc_obps/compliance/fixtures/production/compliance_periods.json
Updates the fixtures in the production directory to be correct:
- removes the compliance period for reporting year 2023
- updates the deadline date to nov 30 2025 for reporting year 2024
=> chore: update compliance_period prod fixtures to be correct

bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationForm.tsx, bciers/apps/reporting/src/app/components/facility/FacilityEmissionAllocationPage.tsx, bciers/apps/reporting/src/tests/components/facility/FacilityEmissionAllocationForm.test.tsx
Card: https://github.com/bcgov/cas-reporting/issues/719
- if operation is an SFO, filter the schema to remove "Not Applicable" from the enums of methodology options.
1. Run the project and log in as bc-cas-dev
2. Start or continue a report for an OBPS regulated operation that is an SFO (eg. Bugle SFO)
3. Progress through the report to the allocation-of-emissions page
4. Click the Methodology dropdown selector
- Expect to see: 'Not Applicable' is NOT an option.
5. [Optional] Pick an LFO and progress through the report for any facility. Get to the allocation-of-emissions page and see that 'Not Applicable' IS still a methodology option (as expected).
=> remove 'Not applicable' allocation methodology for SFOs

bc_obps/compliance/service/compliance_dashboard_service.py, bc_obps/compliance/tests/service/test_compliance_dashboard_service.py
card: https://github.com/bcgov/cas-compliance/issues/299
This PR:
- removes supplementary reports with no obligation no earned credit status from the grid
- pytests to ensure this works^
=> 299 hide unactionable supplementary reports

.pre-commit-config.yaml
This PR:
- adds additional dependencies to bandit in pre-commit to get past pbr error, e.g. https://github.com/bcgov/cas-registration/actions/runs/17213663266/job/48837263110?pr=3709
=> chore: fix bandit dependencies in CI

bc_obps/compliance/service/compliance_invoice_service.py, bc_obps/registration/fixtures/mock/address.json
card: https://github.com/bcgov/cas-compliance/issues/224
This PR:
- uses operator.mailing_address instead of physical address in the invoice service
- there was a duplicate address in the fixtures which made it harder to see which address was being used, so I updated the fixtures to be unique
=> 224 - use operator mailing instead of physical address on invoices

dags/bc_obps_test_migrations.py
Fixes an issue in the DAG template `helm_options is undefined` when running the DAG to test migrations. 
Jinja templating language can't directly access the `HELM_OPTIONS` _Python_ variable, so using the existing params `helm_options` is now set there.
=> fix: jinja template in dag can't directly use python var

bc_obps/compliance/api/_bccr/_accounts/_account_id/_compliance_report_versions/_compliance_report_version_id/account_id.py, bc_obps/compliance/dataclass.py, bc_obps/compliance/service/bc_carbon_registry/account_service.py, bc_obps/compliance/service/bc_carbon_registry/apply_compliance_units_service.py, bc_obps/compliance/service/bc_carbon_registry/schema.py, bc_obps/compliance/tests/api/_bccr/_accounts/test_account_id.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_apply_compliance_units_service.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_bc_carbon_registry_api_client.py, bc_obps/compliance/tests/service/bc_carbon_registry/test_bc_carbon_registry_service.py, bciers/apps/compliance/src/app/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/manage-obligation/apply-compliance-units/ApplyComplianceUnitsComponent.test.tsx
Fixes ticket https://github.com/bcgov/cas-compliance/issues/226 by implementing proper ownership validation for BCCR Holding Account IDs in the "Apply Compliance Units" functionality. Previously, users could enter any BCCR Holding Account ID and apply units even if they didn't own the associated compliance sub-account, leading to units being deducted but not properly reflected in BCIERS or BCCR.
- **Added `validate_holding_account_ownership()` method** in `BCCarbonRegistryAccountService`
- Validates that a holding account owns the compliance sub-account for a given operation
- Handles both existing sub-accounts (via `masterAccountId` comparison) and new operations (via compliance account lookup)
- **Integrated ownership validation** into `ApplyComplianceUnitsService`:
- **Schema …
=> chore: verify ownership of sub-account in BCCR

bciers/apps/compliance/src/app/components/compliance-summary/request-issuance/internal/track-status-of-issuance/InternalIssuanceStatusDeclinedNote.tsx, bciers/apps/compliance/src/app/components/compliance-summary/request-issuance/internal/track-status-of-issuance/InternalTrackStatusOfIssuanceComponent.tsx, bciers/apps/compliance/src/tests/components/compliance-summary/request-issuance/internal/track-status-of-issuance/InternalIssuanceStatusDeclinedNote.test.tsx
card: https://github.com/bcgov/cas-compliance/issues/304
This PR:
- the wording of internal declined note on the track status of issuance page is conditional based on how the declined happened (analyst requested supp report vs. director declined). This PR adds that conditionality
- update vitests
=> 304 - internal declined note is conditional

bc_obps/reporting/service/report_review_changes_service.py, bciers/apps/reporting/src/app/components/changeReview/templates/EmissionAllocationChangeView.tsx, bciers/apps/reporting/src/app/components/changeReview/templates/FacilityReportChanges.tsx
Fixed the following issues:-
1. Allocation of Emissions:- If methodology was changed, it wasnt visible on review chanegs page
2. Non-attributable emissions:- edited chanegs werent visible
3. If Registration purpose is changed for an operation and a supplementary report is created  it should just show
=> chore: fixed minor changes in review changes page

bciers/apps/reporting/src/app/components/finalReview/finalReviewFields.ts
**Card:** https://github.com/bcgov/cas-reporting/issues/876
**Issue:** Fuel excluded emission values (CO2 emissions from excluded woody biomass, Other emissions from excluded biomass, Emissions from excluded non-biomass) were showing incorrect values.
**Fix:**
- Updated reportNewEntrantFields to preserve the original array index when generating keys for emission categories.
- Replaced use of the filtered array index with originalIndex so values always map correctly.
- Applied the same logic consistently for basic, fuel excluded, and other excluded emissions.
=> chore: fixed new entrant fields in final review

.github/workflows/release-charts.yaml
Addresses problems with the Airflow test dag created in #3478 by adding a release workflow for the helm charts.
=> chore: add release workflow for helm charts

helm/cas-bciers/Chart.lock, helm/cas-bciers/Chart.yaml
Quick fix to roll back to old version of DAG trigger chart until Airflow 3 is in place.
=> fix: dag trigger chart should use APIv1 until update

helm/cas-bciers/Chart.lock, helm/cas-bciers/Chart.yaml
Updates the `cas-logging-sidecar` version used. This version now uses a [custom docker image build](https://github.com/bcgov/cas-pipeline/pull/130), replacing the deprecated Bitnami image.
=> chore: update logging sidecar to version using CAS image

bciers/apps/dashboard/app/api/auth/token/route.ts, bciers/apps/dashboard/middleware.ts, bciers/libs/utils/src/environmentDetection.test.ts, bciers/libs/utils/src/environmentDetection.ts
This is to prevent middleware vitest tests from failing locally.
=> chore: add environment detection utilities and integrate in middleware and token APIs

bc_obps/compliance/service/compliance_report_version_service.py
One line fix: Cast the decmial credited_emissions to integer before comparing with zero
=> chore: fix zero comparison for earned_credits to avoid records where amount is zero

bc_obps/compliance/service/supplementary_version_service.py, bc_obps/compliance/tests/service/test_supplementary_version_service.py
card: https://github.com/bcgov/cas-compliance/issues/350
This PR:
- changes the IncreasedCreditHandler so it now handles cases when there is already an earned credits record that has been approved or declined NEW! or have been requested (status is either issuance requrested or changes required) (https://github.com/bcgov/cas-compliance/issues/343 handles if credits were never requested)
- pytests the approved and declined cases
- pytests that the correct handler is used
=> 350: IncreasedCreditHandler works when credits have already been approved/declined/requested

bc_obps/compliance/service/elicensing/elicensing_obligation_service.py, bc_obps/compliance/tasks.py, bc_obps/compliance/tests/service/elicensing/test_elicensing_obligation_service.py
[ISSUE 307](https://github.com/bcgov/cas-compliance/issues/307)
**New Methods Added:**
- `_is_invoice_generation_date_reached()` - Checks if the current date has reached or passed the invoice generation date
- `_is_invoice_generation_date_today()` - Checks if the current date exactly matches the invoice generation date
- `generate_invoices_for_current_period()` - Main method that orchestrates invoice generation for the current period
- `_get_obligations_for_invoice_generation()` - Retrieves obligations eligible for invoice generation
**Refactored Methods:**
- `handle_obligation_integration()` - Extracted date checking logic into separate helper methods for better maintainability
**New Scheduled Task:**
- Added `ElicensingObligationService.generate_invoices_for_current_period` to the …
=> feat: automated task to generate invoices on a specific-date

bc_obps/compliance/service/supplementary_version_service.py, bc_obps/compliance/tests/service/test_supplementary_version_service.py
card: https://github.com/bcgov/cas-compliance/issues/355
This card:
- handler for the case where a supp report decreases the earned credits and the previously requested credits were already declined
- pytest for this case^
=> 355 decrease handler

bc_obps/registration/schema/operation_timeline.py, bc_obps/registration/tests/endpoints/test_operations.py, bc_obps/service/data_access_service/operation_designated_operator_timeline_service.py, bciers/apps/administration/app/bceidbusiness/industry_user/operations/page.tsx, bciers/apps/administration/app/bceidbusiness/industry_user_admin/operations/page.tsx, bciers/apps/administration/app/components/operations/OperationDataGridPage.tsx, bciers/apps/administration/app/components/operations/OperationInformationForm.tsx, bciers/apps/administration/app/components/operations/OperationInformationPage.tsx, bciers/apps/administration/app/components/operations/OperationLayouts.tsx, bciers/apps/administration/app/components/operations/OperationPage.tsx, bciers/apps/administration/app/components/operations/types.ts, bciers/apps/administration/app/data/jsonSchema/operationInformation/MissingRepresentativeAlertFieldTemplate.tsx, bciers/apps/administration/app/data/jsonSchema/operationInformation/operationInformation.ts, bciers/apps/administration/app/idir/cas_admin/operations/page.tsx, bciers/apps/administration/app/idir/cas_admin/operators/[operatorId]/operator-details/operations/page.tsx, bciers/apps/administration/app/idir/cas_analyst/operations/page.tsx, bciers/apps/administration/app/idir/cas_analyst/operators/[operatorId]/operator-details/operations/page.tsx, bciers/apps/administration/app/idir/cas_director/operations/page.tsx, bciers/apps/administration/app/idir/cas_director/operators/[operatorId]/operator-details/operations/page.tsx, bciers/apps/administration/app/idir/cas_view_only/operations/page.tsx, bciers/apps/administration/app/idir/cas_view_only/operators/[operatorId]/operator-details/operations/page.tsx, bciers/apps/administration/tests/components/operations/OperationDataGridPage.test.tsx, bciers/apps/administration/tests/components/operations/OperationInformationForm.test.tsx, bciers/apps/administration/tests/components/operations/OperationInformationPage.test.tsx, bciers/apps/administration/tests/components/operations/OperationLayouts.test.tsx, bciers/apps/administration/tests/components/operations/OperationPage.test.tsx, bciers/libs/components/src/form/fields/AlertFieldTemplateFactory.tsx
Card: https://github.com/bcgov/cas-registration/issues/3370
Updated Operations datagrid and information components to alert external users when a "Registered" operation does not have any operation representatives.
- Updated operations api to return contacts array
- Updated Operations Layout (datagrid) and Information components to show missing representative alerts
- created a new parent component for the operations grid and layout to keep the data fetching out of the route page files.
In order to see these alerts, an operation needs to not have any Operation Representative. This means an entry in operation_contacts table. The easiest way to have an operation WITHOUT a representative is to delete entries from this table. I chose to remove the 2 contacts for 'Banana LFO - Registered' …
=> 3370 alert assign op rep

.github/workflows/release-charts.yaml
Small change to set the Chart Release action to only run for the `migration-test` charts and _not_ the core `cas-bciers` chart.
💊 Side effects may include the chart releaser actually working.
=> chore: only release migration-test charts

bciers/apps/compliance-e2e/tests/example.spec.ts
Additional work for #3900 to remove the `example.spec.ts` to prevent CI from failing, and happo from taking screenshots.
=> chore: remove compliance example e2e test
